### ISSUE TITLE
Question: sampling 

### ISSUE THREAD

**Issue by mimisikai** [HelenaLC/CATALYST#100]
Hey Helena, 

This isn't a issue, but just a question on how FlowSOM/Catalyst handling the sampling. 
We all know that, at least in the Cytobank, when running FlowSOM, we need to decide the event sampling, most cases are using Equal sampling, but some of them may need Proportional sampling or Use all events due to very limited cell events for some samples. 

I wonder, when Catalyst starts to cluster the samples, how the sampling thing? Can users control this parameter? 

And, when you showing the cluster abundance et al differential comparison analyze, I assume those groups should be have equal events. However, if in some scenario, we cannot bring the equal event for each group, how can we make the statistical comparison meaningful?.

Thanks,
Joe

**Comment by HelenaLC** [comment]
1. `CATALYST`'s `cluster` function does currently not implement a downsampling procedure, and I'm not sure it will. I think that cells not assigned a cluster are quite "useless" as in: They will not be used for differential state (DS) and abundance (DA) analysis, and will not appear in any visualizations besides the diagnostic plots prior to clustering. Thus, I suggest to downsample the data yourself after some basic diagnostics. 

```
# for equal sampling (fixed number of cells per sample)
cs <- split(seq_len(ncol(sce)), sce$sample_id)
cs <- lapply(cs, function(u) sample(u, min(100, length(u))))
sce <- sce[, unlist(cs)]

# for proportional sampling (fixed number of cells in total)
cs <- sample(ncol(sce), 10000)
sce <- sce[, cs]
```

2. Non-equal group-sizes will not affect DA analysis, as this is performed on *relative* abundances, not the absolute cell counts. Similarly for DS analysis, there's a normalisation step that accounts for differences in sample sizes. Naturally, however, larger populations and groups will have more power. So it's probably inaccurate to say *don't* affect differential testing; but it is not required for all groups to have an equal number of events.
