### ISSUE TITLE
prepData function removing some of my fluorescence channels 

### ISSUE THREAD

**Issue by christianAA880** [HelenaLC/CATALYST#103]
Hello! 

I have been testing the Catalyst package with the sample data and it works amazing! 

However, when i try to generate  a sce from my fcs file which is a 26 color panel, the prepData function keeps removing the same 4 channels and storing it in int_colData. Not sure how to move that information back to SCE's assay data. Any help is very much appreciated, thank you!

**Comment by christianAA880** [comment]
nvm. I just removed the 
 # grep non-mass channels
and 
  # store & exclude from assay data
source code from the prepData function and it seemed to work.

**Comment by HelenaLC** [comment]
Hey Christian-
Glad you could work around it. Just to add though: yes, this is totally(!) a bug for FACS data and I already fixes this locally. It will be available with the next release, so that hopefully you should be able staying up to date rather than using a forked version :)

**Comment by LaurenReich** [comment]
Hello!
I'm having the same problem, I have a panel of 10 colors but prepData is removing 3 of them. I'm not sure how to get them back (or why they're being excluded) and I have the most updated version of Catalyst.
Any help would be greatly appreciated!
[2020.02.12 panel_export.xlsx](https://github.com/HelenaLC/CATALYST/files/4697111/2020.02.12.panel_export.xlsx)
<img width="675" alt="plot1" src="https://user-images.githubusercontent.com/64659808/83169620-4beb0280-a0e1-11ea-8d4e-8072296b53e0.png">
[prepData markdown.pdf](https://github.com/HelenaLC/CATALYST/files/4697105/prepData.markdown.pdf)

**Comment by HelenaLC** [comment]
Setting keyword(ff)[[“$CYT”]] <- “FACS” should fix it. (For each flowFrame)- 
Basically, the function will move (not remove, but move to an internal slot) non-mass channels for CyTOF data. Usually, the cytometry is stored in the flowSet- In your case, I’m guessing your data is missing this info. Let me know if that fixes it :) 
And sorry for this issue... I am not sure what is the best way to handle non-mass channels in CyTOF, but keep them in FACS...

**Comment by LaurenReich** [comment]
Sorry, I'm very new to R. I'm writing this: 
keyword(fs[1], "$CYT") <- "FACS", (assuming I'd continue with the other flow frames in the set fs[2], etc.), but I'm getting the following error:
Error in `keyword<-`(`*tmp*`, "$CYT", value = "FACS") : 
  unused argument ("$CYT")
Am I interpreting your answer wrong? Thank you!

**Comment by LaurenReich** [comment]
Sorry, I'm very new to R. I've tried both this:
keyword(fs[1])[["$CYT"]] <- "FACS"  (assuming I'd continue with the other flow frames in the set fs[2], etc.)
with the error:
Error in .local(object, keyword, ...) : 
  argument "keyword" is missing, with no default

So I tried this:
keyword(fs[1], "$CYT") <- "FACS", but I'm getting the following error:
Error in keyword<-(*tmp*, "$CYT", value = "FACS") :
unused argument ("$CYT")
Am I interpreting your answer wrong or missing something? Thank you!

**Comment by HelenaLC** [comment]
I think it should be keyword(fs[[i]])[[“$CYT”]] - fs[1] returns a list of length 1, fs [[1]] is the first element of that list: a flowFrame.

**Comment by LaurenReich** [comment]
Thanks for the clarification! It worked perfectly :)
