### ISSUE TITLE
How to create a SCE from a flowFrame

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#104]
Hi Helena

I´m trying to use cytof-wf independently on every batch of my dataset to produce umap figures for every batch. The problem is that some of the batches have only one fcs, when I try to run the pipeline I get this error:

sce <- prepData(ffL727, panel, md, features = panel$fcs_colname, md_cols = list(file = "file_name", id = "sample_id", factors = c("condition", "patient_id","batch")))

Error in prepData(ffL727, panel, md, features = panel$fcs_colname, md_cols = list(file = "file_name", : Invalid argument 'x'; should be either a flowSet or a character string specifying the path to a directory containing a set of FCS files. 

How can I use prepData to create a SCE from a single flowFrame? Should I use a different function?

Thank you for your help

Regards
Juan

**Comment by HelenaLC** [comment]
I think prepData(flowSet(flowFrame), ...) should do it. Let ne know if not.

**Comment by algebio** [comment]
Hi Helena

Thank you, it works but I got a different error now:

sce <- prepData(flowSet(ffL727), panel, md, features = panel$fcs_colname, md_cols = list(file = "file_name", id = "sample_id", factors = c("condition", "patient_id","batch"))) 

Error in validObject(.Object) : 
  invalid class “SummarizedExperiment” object: 
    nb of cols in 'assay' (98004) must equal nb of rows in 'colData'
    (5978244)

I had used premessa to delete some channels, so I also tried with the original fcs and got a different error:

sce <- prepData(flowSet("ff1.fcs"), panel, md, features = panel$fcs_colname, md_cols = list(file = "file_name", id = "sample_id", factors = c("condition", "patient_id","batch"))) 

Error in flowSet("ff1.fcs") : All additional arguments must be flowFrames

Ideally I'd rather to use the processed from premessa but I don't know if it's malpractice. I'll  follow your advice.

**Comment by SamGG** [comment]
Hi,
if you want to create a flowSet from a file, the function is read.flowSet("my_directory_of_FCS_files"). Read the doc in flowCore package.
Best.

**Comment by algebio** [comment]
Hi Sam

Thank you for your help. The problem is that we had used cytof-workflow for the rest of our paper's figures and I'd like to do this figures with the same pipeline if possible.

I have tried with read.flowset and it does create it as you said but I think I need to use prepData in order to construct a SingleCellExperiment to be used in the rest of the pipeline, otherwise it complains. Example:

sce = read.flowSet("ff1.fcs")
n_cells(sce)
 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘n_cells’ for signature ‘"flowSet"’

**Comment by HelenaLC** [comment]
SCE stands for SingleCellExperiment. When you read in the file as a flowSet, that is not an SCE. You should read it in, and then call prepData. I.e. 

fs <- read.flowSet(...)
sce <- prepData(...)

Also, for what it’s worth: CATALYST has supported a complete preprocessing pipeline for 3 years... before permessa existed. Not sure if there any major differences, but thought I’d mention this in case you’re unaware.

**Comment by algebio** [comment]
Hi Helena

I'm happy to use CATALYST only, but I still have the problem of how to use the pipeline in those batches with one single fcs. Yesterday I tried the following:

On a fcs where I removed empty channels with premessa (I don't know if this is malpractice because I'm learning all this by myself)

sce <- prepData(flowSet(ffL727), panel, md, features = panel$fcs_colname, md_cols = list(file = "file_name", id = "sample_id", factors = c("condition", "patient_id","batch")))

Error in validObject(.Object) :
invalid class “SummarizedExperiment” object:
nb of cols in 'assay' (98004) must equal nb of rows in 'colData'
(5978244)

On a fcs file without removing any channel:

sce <- prepData(flowSet("ff1.fcs"), panel, md, features = panel$fcs_colname, md_cols = list(file = "file_name", id = "sample_id", factors = c("condition", "patient_id","batch")))

Error in flowSet("ff1.fcs") : All additional arguments must be flowFrames

**Comment by HelenaLC** [comment]
As mentioned by Sam & in my previous message, you cannot call `flowSet` on and FCS file. Have you tried this?
```
fs <- read.flowSet("ff1.fcs")
sce <- prepData(fs, ...)
```

**Comment by algebio** [comment]
Hi Helena and Sam

It works. I can´t express how grateful I´m for your help.

Regards
Juan
