### ISSUE TITLE
[REQ] Interactive Cluster Merging with shinyDendro

### ISSUE THREAD

**Issue by MikhaelManurung** [HelenaLC/CATALYST#106]
Hi Helena,

For the clustering of CyTOF data, I tend to over cluster and then merge the similar clusters. However, it is difficult and time-consuming to do it manually. To make my life easier, I applied [shinyDendro](https://github.com/exaexa/shinyDendro) to interactively merge my clusters. It worked really well for me.

![sce_all_pma_hc40_merge](https://user-images.githubusercontent.com/10704760/82043472-f0b21c80-96ab-11ea-91f8-dea0c851ed67.png)

Perhaps this is something that can be added to the already awesome `CATALYST`?

Best regards,
Mikhael

**Comment by HelenaLC** [comment]
Hm, watching the youTube demo- this looks really nice. But: What exactly did you have in mind? I think it wouldn't be beneficial to reimplement something that already exists, also considering the amount of additional dependencies it would required to embed a Shiny app solely for this purpose.
