### ISSUE TITLE
Error in prepData()

### ISSUE THREAD

**Issue by adam2o1o** [HelenaLC/CATALYST#107]
Hi, 
I get the following error when running prepData():

`Error in as[is.na(as)] <- panel$fcs_colname[is.na(as)] : 
  replacement has length zero`

I checked the source code for the function and it looks like the function is calling "panel$fcs_colname", which assumes I have a column called fcs_colname in the panel data.

`    # replace problematic characters

    as <- panel[[panel_cols$antigen]]
    as[is.na(as)] <- panel$fcs_colname[is.na(as)] `

**Comment by HelenaLC** [comment]
You are correct- it should be 
```
as <- panel[[panel_cols$antigen]]
as[is.na(as)] <- panel[[panel$channel]][is.na(as)]
```
instead. I have push a fix to the GitHub master branch, and am closing the issue for my own record. It will go to Bioc once a few other developments are finished. Thanks for spotting this!
