### ISSUE TITLE
What is panel_use from and for?

### ISSUE THREAD

**Issue by SamGG** [HelenaLC/CATALYST#108]
Hi,
I am currently writing a small wrapper to use a simple matrix as input in order to get a sce object and to use the very nice plots of CATALYST.
could you explain me the panel_use field?
https://github.com/HelenaLC/CATALYST/blob/20126afb55d67784b46f80dc36544121445b1327/R/prepData.R#L152
Best.

**Comment by markrobinsonuzh** [comment]
Hi Samuel,

If practically all the datasets we get, we have extra columns in the `flowSet` (e.g., barcode channels, after the samples have been de-barcoded) and this is just a way to specify which channels get used in the downstream object ..

Here is an example from `example(prepData)` ..

```
prepDt> rowData(sce)
DataFrame with 61 rows and 4 columns
        channel_name marker_name marker_class use_channel
         <character> <character>     <factor>   <logical>
BC1            Y89Di         BC1        state        TRUE
Vol1          Ru96Di        Vol1        state        TRUE
Vol2          Ru98Di        Vol2        state        TRUE
Vol3          Ru99Di        Vol3        state        TRUE
Vol4         Ru100Di        Vol4        state        TRUE
...              ...         ...          ...         ...
DNA2         Ir193Di        DNA2        state        TRUE
cisPt1       Pt194Di      cisPt1        state        TRUE
cisPt2       Pt195Di      cisPt2        state        TRUE
Pb208Di      Pb208Di     Pb208Di        none        FALSE
```

**Comment by SamGG** [comment]
Thanks a lot.
