### ISSUE TITLE
CATALYST for Flow-cytometry Data

### ISSUE THREAD

**Issue by vivek-verma202** [HelenaLC/CATALYST#109]
Hi Helena,
Thank you so much for CATALYST!

I am planning to use CATALYST - Diffcyt pipeline for compensated 15-color flowcytometry data. Apart from using 150 as arcsinh transformation cofactor, is there anything else that should be different from [Differential discovery with CATALYST](https://bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html)?

In addition, is there a way to normalize for the batch-effect in flow data?

Thank-you once again and stay safe!

**Comment by markrobinsonuzh** [comment]
Hi @vivek-verma202,

Perhaps @HelenaLC has some further comments on this .. but beyond the arcsinh cofactor, I don't think there is too much you need to change to do the differential discovery with HD flow data. I would of course double check that cofactor=150 puts all the channels on a good scale .. different channels might benefit from different cofactors, but I haven't explored a way to do this in an semi-automatic way.

Re: normalizing for batch effect, there are ways of course, and here are two recent articles about it:

https://www.biorxiv.org/content/10.1101/2020.05.09.085621v2
https://onlinelibrary.wiley.com/doi/full/10.1002/cyto.a.23904

Those could/would happen outside of CATALYST, but you could continue with the downstream analyses after these operations.

Best, Mark

**Comment by HelenaLC** [comment]
Not much too add from my side as I haven't worked with FACS myself. But I second what Mark said, I think that besides the transformation, all should work analogous to CyTOF. Maybe one thought re clustering-

Depending on how many colors you have (I've seen datasets with <10), you might want to consider focusing on a lower resolution clustering. I.e., the default parameters will cluster the data into 100 SOM clusters, and 2-20 metaclusters. I can imagine that with fewer parameters (e..g, 10 vs. 40 in CyTOF), this might lead to some overclustering, and that a lower number of clusters could be more reasonable. But, as I said, this depends on how many parameters (colors) you're measuring.

**Comment by SamGG** [comment]
Nothing to add, just to point a last recent reference about batch effect
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6803429/

**Comment by vivek-verma202** [comment]
Thanks a lot!
