### ISSUE TITLE
How to plotAbundances by a condition equal to something

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#111]
Hi Helena

I'm working with a dataset with samples from different tissues, diseases and conditions. My dataset looks like this:
file_name | sample_id | condition | patient_id | disease | tissue |  

with 2 conditions (stimulated and unstimulated) and several diseases and tissues

I have created a sce with all the dataset and I would like to plot abundances and do the differential analysis comparing different sce subsets when tissues == something and condition == something else, for example: PB stim vs PB unstim, spleen stim vs PB stim, spleen stim between patients, etc

I have tried to modify the function plotAbundances(sce, k = "meta20", by = "sample_id", group_by = "tissue") but I can't find the way.

Could you please give me some guidance on how I could do these kind of comparisons?

Regards
Juan

**Comment by HelenaLC** [comment]
Have a look at ?filterSCE - you can filter the SCE and plot different subsets with all plotting functions.

**Comment by algebio** [comment]
GOLD!

Thank you Helena
