### ISSUE TITLE
Identifying Outliers

### ISSUE THREAD

**Issue by vivek-verma202** [HelenaLC/CATALYST#113]
Hi,
I am working on human PBMC data of more than 200 samples and found that CATALYST-DIFFCYT results are sensitive to outliers (as would any linear model would be).
For example:
When a marker's expression looks like:
![CD8a](https://user-images.githubusercontent.com/33168572/84308843-36d49180-ab2d-11ea-928a-3749f3b1ad36.jpg)
I am assuming it is because of few outliers with extreme values. 
If that's true, how can I:
1. identify sample_id with the extreme values
2. exclude cells with extreme values for a particular marker
3. Further standardize the expression?

Similarly, 
when it comes to identifying samples with extreme proportion of specific clusters:
![clust](https://user-images.githubusercontent.com/33168572/84309963-e78f6080-ab2e-11ea-9bf2-b71012501a91.jpg)

Is there a way to know their sample_ids?
Sample_id wise plotabundance is good when we have less samples and clusters are not rare, as mere eyeballing would work but not otherwise.

Thanks in advance!

**Comment by vivek-verma202** [comment]
I guess the following heatmap can provide us with some hints on clusters that are sample-specific (instead of being biologically relevant, second-part of the question above: identifying sample_ids with extreme cluster proportions)
```
pheatmap(as.matrix(table(cluster_ids(sce, "meta10"), sample_ids(sce))),
         scale = "row", fontsize = 8)
```
![image](https://user-images.githubusercontent.com/33168572/84420126-9000fb80-abe7-11ea-8476-39cd0060ee1c.png)
We can appreciate that something was not right with the sample_id "F107" just by eyeballing the figure above. Of course, that "something" could be clinical or technical and *"researcher discretion advised"* for any future actions.

**Comment by markrobinsonuzh** [comment]
It's true, (log) linear models can indeed be sensitive to outliers. There is a robust version of `edgeR`, but I don't think it's exposed in `diffcyt`. In general, if you use `limma` for DA and DS, it should be somewhat less sensitive to outliers (because it's on the log scale).

To find the sample_ids, one thing you might try is to recompute the proportions that `plotAbundances` does, using:
```
ns <- table(cluster_ids(sce, "meta20"), sample_ids(sce))
fq <- prop.table(ns, 2) * 100
```
(replace `meta20` with whatever level of resolution or merging that you are using).

**Comment by vivek-verma202** [comment]
Thanks Mark, how can I identify cells and sample_ids of extreme marker expression?

**Comment by markrobinsonuzh** [comment]
For extreme marker expression, maybe try:
```
plotExprHeatmap(sce, features=rownames(sce), scale="never")
```
(you can play with the other options of `scale` and maybe `features = type_markers(sce)` ..)

This may lead to dropping samples before running clustering.

To look for outliers in the proportions (from above), nothing off-the-shelf comes to mind. But, one idea: calculate a robust mean and variance (e.g., median and MAD) for each row (cluster) of `fq`. Then, calculate row-wise (x-median)/sqrt(MAD) and look for extreme positive/negative values .. failing all that, you might break in to the wrapper and run a robust version of the limma-DA analysis (e.g., `lmFit(.., method="robust")` .. 

Overall, if this is a recurring theme, we'll need to think more about having something more bespoke for it.

**Comment by vivek-verma202** [comment]
Thanks a lot!
