### ISSUE TITLE
Error in prepData: unused argument (transform = FALSE)

### ISSUE THREAD

**Issue by zl7515** [HelenaLC/CATALYST#114]
Hi,

I would want to turn off the transform in function prepData but received the following error:

unused argument (transform = FALSE)

Thanks in advance for your help.

Allen

**Comment by HelenaLC** [comment]
Please post the output of `sessionInfo()`.

**Comment by zl7515** [comment]
> Please post the output of `sessionInfo()`.

Thank you for reminding me. I forgot to update Rstudio to the latest version
