### ISSUE TITLE
Unable to use package CATALYST, "package or namespace load fail"

### ISSUE THREAD

**Issue by LaurenReich** [HelenaLC/CATALYST#118]
Hi,

I'm having trouble using CATALYST, which I haven't had a previous issue with. I can install it fine with Bioconductor (I originally received the same error but after changing mirrors the error went away), but loading the package gives the following 

> Error: package or namespace load failed for ‘CATALYST’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/Users/reichln/Library/R/4.0/library/CytoML/libs/CytoML.so':
>   dlopen(/Users/reichln/Library/R/4.0/library/CytoML/libs/CytoML.so, 6): Symbol not found: __ZN7cytolib15GatingHierarchy6gatingERNS_12MemCytoFrameEmbb
>   Referenced from: /Users/reichln/Library/R/4.0/library/CytoML/libs/CytoML.so
>   Expected in: flat namespace
>  in /Users/reichln/Library/R/4.0/library/CytoML/libs/CytoML.so

Thanks! It's preventing me from moving any further and driving me crazy. I don't have this problem with any other package for this pipeline.
I'm using R 4.0.0 and macOS Mojave v 10.14.6

**Comment by HelenaLC** [comment]
I've been having the same issue since last week... However, it is not a problem with `CATALYST` but a `CytoML`. It should be resolved in the next couple days. See also the discussion here: https://github.com/RGLab/CytoML/issues/103
