### ISSUE TITLE
How to get the percentages from plotAbundances function (Figure 20)

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#120]
Hi Helena

How could I get a table with the percentages of every population in every sample? Basically the same info we get with the bar chat after plotAbundances(sce, k = "merging1", by = "sample_id") but in numbers so we can reference them in the paper.

Regards
Juan

**Comment by HelenaLC** [comment]
**option 1:**

You can extract a tidy-format `data.frame` from the plot via
```
p <- plotAbundances(sce, 
    k = "merging1", 
    by = "sample_id")
p$data
```

**option 2:**

You can compute the cluster-compositions for each sample manually via
```
n_cells <- table(
    sample = sce$sample_id, 
    cluster = cluster_ids(sce, "merging1"))
prop.tabile(n_cells, margin = 1)
```

**Comment by algebio** [comment]
Thank you so much, Helena.

You should write a book with all these tricks, I'll happily pay every single penny you ask for it!

Regards
Juan
