### ISSUE TITLE
Sort by condition in "PlotDiffHeatmap"

### ISSUE THREAD

**Issue by j-leffler** [HelenaLC/CATALYST#124]
Hi,

Thank you for a great package! I am testing cluster abundances based on several conditions (atopy, sex etc) in my data set. However, then I create heatmaps of the results (PlotDiffHeatmap) the findings are hard to visualise as the heatmap columns show up in the same order. Is it possible to sort the DiffHeatmap based on factors in my "experiment_info" instead of what appears to be based on the patient id? Cheers!

**Comment by HelenaLC** [comment]
Thanks for the compliment. 2 thoughts:
- When `col_clust = FALSE`, the column order is determined by the `sample_id`'s factor levels. So one option would be to reorder these depending on the comparisons you'd like to visualize.
- Independently, when doing pairwise comparisons, including all conditions might over-crowd the plot, and it might be preferable to limit the heatmap to the conditions being compared. E.g., you could loop through each pair of contrasts, and subset the 2 conditions of interest using `filterSCE(sce, condition %in% c("a", "b") / c("a", "c") / ...)`.

**Comment by HelenaLC** [comment]
Noted as a feature request! Closing this for now.

**Comment by j-leffler** [comment]
thanks for your help on this!
