### ISSUE TITLE
`prepData` with `transform = FALSE` gives an error

### ISSUE THREAD

**Issue by sameetmehta** [HelenaLC/CATALYST#126]
Hi,
Thank you for writing this package.  It has been a life saver. 
I have a large CyToF data set.  I have used an external method to normalize and batch correct my data.  So I want to ingest the data using `prepData` function, but I do not want it to "normalize" the data.  When I call `prepData` with `transform = FALSE`, it give me an error saying it is an "unused" argument.
Please advise.

**Comment by markrobinsonuzh** [comment]
Dear @sameetmehta 

Can you give a `sessionInfo()`?

My guess is that you have an older version of `CATALYST` .. assuming you are running R 4.0.x, a `BiocManager::install("CATALYST")` will get you the latest version (at the moment, 1.12.2)

Best, Mark

**Comment by sameetmehta** [comment]
Yes, you are correct.  My bad. I am closing the issue.
