### ISSUE TITLE
“plotDiffHeatmap” issue

### ISSUE THREAD

**Issue by Clovernana** [HelenaLC/CATALYST#130]
Hello，
I have read the artile about CyTOF workflow.But when I tried some of this code, the errors occured here.And the code and errors are displayed below.
![image](https://user-images.githubusercontent.com/50875585/89619779-22104200-d8c1-11ea-8a9a-3602d684e9b1.png)
![image](https://user-images.githubusercontent.com/50875585/89623646-8df5a900-d8c7-11ea-9101-3436abe0b633.png)

And I use the R 4.0.2 version in windows system.
It seems that there are some differences between the article and  the code example in R help.
![image](https://user-images.githubusercontent.com/50875585/89623577-6c94bd00-d8c7-11ea-9d23-6d4c646fa7f5.png)

Could you help me check the error?Is it because of the different  R versions?

Best wishes!
Clover

**Comment by markrobinsonuzh** [comment]
First thing: can you give the output of `sessionInfo()` so that we know what version of `CATALYST` (maybe `diffcyt`) that you are working with?

**Comment by sorjuela** [comment]
the code was updated (maybe not yet in the workflow), now you would have to run something like:
`plotDiffHeatmap(x=sce, y = rowData(ds_res4$res))`

**Comment by Clovernana** [comment]
OK,thank you for your  prompt response.Now I make it.
