### ISSUE TITLE
plotClusterHeatmap

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#132]
Dear Helena,
In the previous versions of the package you included plotClusterHeatmap() function in which through the split_by parameter the user could get separated heatmaps for example for different condition which was very beneficial and helpful specially that one could see the freq differences between each cluster in different conditions! Unfortunately this function is deprecated in the new version and through the new functions you have provided its not possible to get separate heatmaps for example per sample ids or conditions to make a comparison! Is there a way to draw such heatmaps other than splitting my data?

**Comment by HelenaLC** [comment]
Yes, this has indeed been deprecated to simplify the already rather complex plotting function, and allow more flexibility (as I'll try to explain): You can generate any series of heatmaps yourself by combining a loop (or `lapply`), `filterSCE` (to subset the data of interest), and `plotExprHeatmap`, `plotFreqHeatmap` and `plotMultiHeatmap`(which have replaced `plotClusterHeatmap`). Here a couple examples:
```
hms <- lapply(levels(sce$condition), function(c) {
    # subset cells from condition 'c'
    sub <- filterSCE(sce, condition == !!c)
    # single heatmap cluster frequencies
    plotFreqHeatmap(sub, k = ...)
    # or, single heatmap of expressions by cluster
    plotExprHeatmap(sub, k = ..., features = NULL, by = "cluster_id", 
        bars = TRUE, perc = TRUE) # also include cluster frequencies
    # or, pair of heatmap analogous to previous output of 'plotClusterHeatmap'
    # (left: type-marker expressions, right: cluster frequencies)
    plotMultiHeatmap(sub, hm1 = "type", hm2 = "abundances")
    # etc. etc.
})
```
The above could be done for any type of heatmap, and any subset you are interested (e.g., you could filter for a subset of clusters via `filterSCE(sce, k = ..., cluster_id %in% c(...))`; exclude certain sample(s) via `filterSCE(sce, !sample_id %in% c(...))`; etc.). 

I am aware this might "look" more complicated, but hope that once you decide on what is interesting to look at and how to generate the respective plots, you are equipped with much more flexibility then in previous versions (especially with `plotMultiHeatmap` for combining `plotExpr-` and `plotFreqHeatmap`s).

*Note: Of course, the above works for ANY `plotX` function (not just heatmaps).
