### ISSUE TITLE
normalization problem when using full flow frame as reference file

### ISSUE THREAD

**Issue by prybakowska** [HelenaLC/CATALYST#137]
Hi,
I have some problem when using parameter "norm_to" in normCytof function, in CATALYST. If I use raw flowframe as a reference, my new normalized values will be much lower than before normalization. I took a look into the function and I can see that the bead mean for reference sample is really low when running:colMeans(exprs(ref)[, get_bead_cols(colnames(ref),+                                                beads)]),
I think this is because it is calculated for all the cells (not only beads), so then the bl factor is incorrect, when running:
slopes <- colSums(smooth0 * bl)/colSums(smooth0^2).
In the help for norm_to parameter it says:a flowFrame or character string specifying an FCS file from which to compute baseline bead intensities, and to which the input data should be normalized to. But shouldn't it be the normalized flow frame with beads only? Could you confirm that what I am saying make sense? I am working with R 4.0.2 and CATALYST 1.12.2 in linux.

Regards,
Paulina

**Comment by HelenaLC** [comment]
Dear Paulina, 
What you're saying makes sense and your understanding of the code is correct. I think the documentation on this also makes sense, though. `norm_to` expects, as is said, "[data] from which to compute baseline bead intensities". 
So yes, these should be beads only (!) as exported by a previous normalization run. E.g., suppose you use `normCytof` to normalize a set of samples A, this will return a set of beads (list element `res$beads`), which can in turn be used to normalize another set of samples B. 
I hope this clarifies things a bit and I'm not just telling you what you already know. Does the documentation make sense like this or do you have a recommendation of how it could be improved / made more clear?
