### ISSUE TITLE
Adding extra expression data to sce

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#139]
Dear Helena,
I am interested to show the avg expression of multiple markers on my UMAP and for that I have used the below code to calculate the avg expression
`mean.exp <- colMeans(x = daf@assays@data$exprs[marker_set, ], na.rm = TRUE)
mean.exp=as.matrix(mean.exp)
colnames(mean.exp)="score"
mean.exp=t(mean.exp)`
Unfortunately I am not sure how to add this extra layer of info to my SCE data! I was trying to convert it to a SCE object and then simply adding it to my SCE object but it didn't work! Can you please assist me in adding this information ?

Thanks a lot

**Comment by bioguy2018** [comment]
Dear Helena I kind of resolved my problem using following simple approach 
`sce <- SingleCellExperiment(assays = list(counts =mean.exp))
reducedDims(sce) <- reducedDims(daf)
plotDR(sce, dr = "UMAP", color_by = "score",assay = "counts",q = 0.1)`
But as you can see I have had to create another SCE object and copy paste my umap from my other SCE into it. I would be happy if you know me of better ways if possible

**Comment by HelenaLC** [comment]
Thanks for your patience and I'm glad you found a temporary solution. In principle, there is an easy way to do this via adding the means (or any other data) to the SCE's cell metadata (`colData(sce)$abc <- mean.exp` or, equivalently, `sce$abc <- mean.exp`), and then coloring cells by this (`plotDR(..., color_by = "abc")`). Unfortunately, there's currently an argument check in `plotDR` that will prevent this. Namely, `color_by` is expected to specify a non-numeric `colData` column. I will fix this with the next version, close the issue for now, and ping you here when the update is in!
