### ISSUE TITLE
Use my pre-defined clusters and skip cluster() function

### ISSUE THREAD

**Issue by SeadonXing** [HelenaLC/CATALYST#140]
I want to use CATALYST to perform DA analysis of my single-cell RNA-seq data.
I have a SingleCellExperiment object. Rows according to genes and Columns are cells. I have pre-defined the celltype/cluster for each cells.
The example you give 
" # construct SCE & run clustering
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce)"

My question is, if I don't want to perform clustring by cluster() function and use my own labels, how to couple with the downstream step "diffcyt".
The paramater "clustering_to_use = "meta20"" is related to the results of cluster(). It will raise errors if I ignore it.
Best

**Comment by HelenaLC** [comment]
While `cluster` wraps around `FlowSOM` only, any clustering algorithm can be in principle apply and incorporated into the `CATALYST`-`diffcyt` framework. Please check section *8.2 Using other clustering algorithms* in `CATALYST`'s vignette on differential discovery, [here](http://bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html).
