### ISSUE TITLE
Can this method be used for flow cytometry data?

### ISSUE THREAD

**Issue by hqu-arcus** [HelenaLC/CATALYST#143]
Hello,

Your package looks amazing and I know this is designed for mass cytometry data, I'm wondering if this could be used for flow cytometry data? Thanks!

**Comment by HelenaLC** [comment]
Yes, absolutely. Provided you have carried out a proper preprocessing, and have some kind of cluster annotations (the method implemented in `CATALYST` is `FlowSOM` but, in principle, any clustering algorithm could be used- see the vignette for how to do that), everything else should be applicable to flow!
