### ISSUE TITLE
prepData function error

### ISSUE THREAD

**Issue by nayaracleite** [HelenaLC/CATALYST#144]
I updated and I still get the error: 
Error in prepData(samples_filtered, panel, md, features = panel$fcs_colname) : all(setdiff(unlist(panel_cols), "marker_class") %in% names(panel)) is not TRUE

spot check that all panel columns are in the flowSet object
> all(panel$fcs_colname %in% colnames(samples_filtered))
[1] TRUE
[session_info.txt](https://github.com/HelenaLC/CATALYST/files/5267842/session_info.txt)

─ Session info ───────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.6      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-09-23                  

─ Packages ───────────────────────────────────────────────────────────────────────────────
 package              * version  date       lib source        
 abind                  1.4-5    2016-07-21 [1] CRAN (R 4.0.2)
 assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.0.2)
 backports              1.1.10   2020-09-15 [1] CRAN (R 4.0.2)
 base64enc              0.1-3    2015-07-28 [1] CRAN (R 4.0.2)
 beeswarm               0.2.3    2016-04-25 [1] CRAN (R 4.0.2)
 Biobase              * 2.48.0   2020-04-27 [1] Bioconductor  
 BiocGenerics         * 0.34.0   2020-04-27 [1] Bioconductor  
 BiocNeighbors          1.6.0    2020-04-27 [1] Bioconductor  
 BiocParallel           1.22.0   2020-04-27 [1] Bioconductor  
 BiocSingular           1.4.0    2020-04-27 [1] Bioconductor  
 bitops                 1.0-6    2013-08-17 [1] CRAN (R 4.0.2)
 blob                   1.2.1    2020-01-20 [1] CRAN (R 4.0.2)
 boot                   1.3-25   2020-04-26 [1] CRAN (R 4.0.2)
 broom                  0.7.0    2020-07-09 [1] CRAN (R 4.0.2)
 car                    3.0-9    2020-08-11 [1] CRAN (R 4.0.2)
 carData                3.0-4    2020-05-22 [1] CRAN (R 4.0.2)
 CATALYST             * 1.12.2   2020-07-02 [1] Bioconductor  
 cellranger             1.1.0    2016-07-27 [1] CRAN (R 4.0.2)
 circlize               0.4.10   2020-06-15 [1] CRAN (R 4.0.2)
 cli                    2.0.2    2020-02-28 [1] CRAN (R 4.0.2)
 clue                   0.3-57   2019-02-25 [1] CRAN (R 4.0.2)
 cluster                2.1.0    2019-06-19 [1] CRAN (R 4.0.2)
 codetools              0.2-16   2018-12-24 [1] CRAN (R 4.0.2)
 colorspace             1.4-1    2019-03-18 [1] CRAN (R 4.0.2)
 ComplexHeatmap         2.4.3    2020-07-25 [1] Bioconductor  
 ConsensusClusterPlus   1.52.0   2020-04-27 [1] Bioconductor  
 cowplot              * 1.1.0    2020-09-08 [1] CRAN (R 4.0.2)
 crayon                 1.3.4    2017-09-16 [1] CRAN (R 4.0.2)
 curl                   4.3      2019-12-02 [1] CRAN (R 4.0.1)
 cytolib                2.0.3    2020-06-09 [1] Bioconductor  
 CytoML                 2.0.5    2020-06-15 [1] Bioconductor  
 data.table             1.13.0   2020-07-24 [1] CRAN (R 4.0.2)
 DBI                    1.1.0    2019-12-15 [1] CRAN (R 4.0.2)
 dbplyr                 1.4.4    2020-05-27 [1] CRAN (R 4.0.2)
 DelayedArray         * 0.14.1   2020-07-14 [1] Bioconductor  
 DelayedMatrixStats     1.10.1   2020-07-03 [1] Bioconductor  
 diffcyt              * 1.8.8    2020-08-05 [1] Bioconductor  
 digest                 0.6.25   2020-02-23 [1] CRAN (R 4.0.2)
 dplyr                * 1.0.2    2020-08-18 [1] CRAN (R 4.0.2)
 drc                    3.0-1    2016-08-30 [1] CRAN (R 4.0.2)
 edgeR                  3.30.3   2020-06-02 [1] Bioconductor  
 ellipsis               0.3.1    2020-05-15 [1] CRAN (R 4.0.2)
 evaluate               0.14     2019-05-28 [1] CRAN (R 4.0.1)
 fansi                  0.4.1    2020-01-08 [1] CRAN (R 4.0.2)
 flowCore             * 2.0.1    2020-06-09 [1] Bioconductor  
 FlowSOM                1.20.0   2020-04-27 [1] Bioconductor  
 flowWorkspace          4.0.6    2020-06-11 [1] Bioconductor  
 forcats              * 0.5.0    2020-03-01 [1] CRAN (R 4.0.2)
 foreign                0.8-80   2020-05-24 [1] CRAN (R 4.0.2)
 fs                     1.5.0    2020-07-31 [1] CRAN (R 4.0.2)
 generics               0.0.2    2018-11-29 [1] CRAN (R 4.0.2)
 GenomeInfoDb         * 1.24.2   2020-06-15 [1] Bioconductor  
 GenomeInfoDbData       1.2.3    2020-09-18 [1] Bioconductor  
 GenomicRanges        * 1.40.0   2020-04-27 [1] Bioconductor  
 GetoptLong             1.0.2    2020-07-06 [1] CRAN (R 4.0.2)
 ggbeeswarm             0.6.0    2017-08-07 [1] CRAN (R 4.0.2)
 ggcyto                 1.16.0   2020-04-27 [1] Bioconductor  
 ggplot2              * 3.3.2    2020-06-19 [1] CRAN (R 4.0.2)
 ggrepel                0.8.2    2020-03-08 [1] CRAN (R 4.0.2)
 ggridges               0.5.2    2020-01-12 [1] CRAN (R 4.0.2)
 GlobalOptions          0.1.2    2020-06-10 [1] CRAN (R 4.0.2)
 glue                   1.4.2    2020-08-27 [1] CRAN (R 4.0.2)
 graph                  1.66.0   2020-04-27 [1] Bioconductor  
 gridExtra              2.3      2017-09-09 [1] CRAN (R 4.0.2)
 gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.0.2)
 gtools                 3.8.2    2020-03-31 [1] CRAN (R 4.0.2)
 haven                  2.3.1    2020-06-01 [1] CRAN (R 4.0.2)
 hexbin                 1.28.1   2020-02-03 [1] CRAN (R 4.0.2)
 hms                    0.5.3    2020-01-08 [1] CRAN (R 4.0.2)
 htmltools              0.5.0    2020-06-16 [1] CRAN (R 4.0.2)
 httr                   1.4.2    2020-07-20 [1] CRAN (R 4.0.2)
 igraph                 1.2.5    2020-03-19 [1] CRAN (R 4.0.2)
 IRanges              * 2.22.2   2020-05-21 [1] Bioconductor  
 irlba                  2.3.3    2019-02-05 [1] CRAN (R 4.0.2)
 jpeg                   0.1-8.1  2019-10-24 [1] CRAN (R 4.0.2)
 jsonlite               1.7.1    2020-09-07 [1] CRAN (R 4.0.2)
 knitr                  1.30     2020-09-22 [1] CRAN (R 4.0.2)
 lattice                0.20-41  2020-04-02 [1] CRAN (R 4.0.2)
 latticeExtra           0.6-29   2019-12-19 [1] CRAN (R 4.0.2)
 lifecycle              0.2.0    2020-03-06 [1] CRAN (R 4.0.2)
 limma                  3.44.3   2020-06-12 [1] Bioconductor  
 lme4                   1.1-23   2020-04-07 [1] CRAN (R 4.0.1)
 locfit                 1.5-9.4  2020-03-25 [1] CRAN (R 4.0.2)
 lubridate              1.7.9    2020-06-08 [1] CRAN (R 4.0.2)
 magrittr               1.5      2014-11-22 [1] CRAN (R 4.0.2)
 MASS                   7.3-53   2020-09-09 [1] CRAN (R 4.0.2)
 Matrix                 1.2-18   2019-11-27 [1] CRAN (R 4.0.2)
 matrixStats          * 0.56.0   2020-03-13 [1] CRAN (R 4.0.2)
 minqa                  1.2.4    2014-10-09 [1] CRAN (R 4.0.2)
 modelr                 0.1.8    2020-05-19 [1] CRAN (R 4.0.2)
 multcomp               1.4-13   2020-04-08 [1] CRAN (R 4.0.2)
 munsell                0.5.0    2018-06-12 [1] CRAN (R 4.0.2)
 mvtnorm                1.1-1    2020-06-09 [1] CRAN (R 4.0.2)
 ncdfFlow               2.34.0   2020-04-27 [1] Bioconductor  
 nlme                   3.1-149  2020-08-23 [1] CRAN (R 4.0.2)
 nloptr                 1.2.2.2  2020-07-02 [1] CRAN (R 4.0.2)
 nnls                   1.4      2012-03-19 [1] CRAN (R 4.0.2)
 openxlsx               4.2.2    2020-09-17 [1] CRAN (R 4.0.2)
 pillar                 1.4.6    2020-07-10 [1] CRAN (R 4.0.2)
 pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.0.2)
 plotrix                3.7-8    2020-04-16 [1] CRAN (R 4.0.2)
 plyr                   1.8.6    2020-03-03 [1] CRAN (R 4.0.2)
 png                    0.1-7    2013-12-03 [1] CRAN (R 4.0.2)
 purrr                * 0.3.4    2020-04-17 [1] CRAN (R 4.0.2)
 R6                     2.4.1    2019-11-12 [1] CRAN (R 4.0.2)
 RBGL                   1.64.0   2020-04-27 [1] Bioconductor  
 RColorBrewer           1.1-2    2014-12-07 [1] CRAN (R 4.0.2)
 Rcpp                   1.0.5    2020-07-06 [1] CRAN (R 4.0.2)
 RcppParallel           5.0.2    2020-06-24 [1] CRAN (R 4.0.2)
 RCurl                  1.98-1.2 2020-04-18 [1] CRAN (R 4.0.2)
 readr                * 1.3.1    2018-12-21 [1] CRAN (R 4.0.2)
 readxl                 1.3.1    2019-03-13 [1] CRAN (R 4.0.2)
 reprex                 0.3.0    2019-05-16 [1] CRAN (R 4.0.2)
 reshape2               1.4.4    2020-04-09 [1] CRAN (R 4.0.2)
 Rgraphviz              2.32.0   2020-04-27 [1] Bioconductor  
 rio                    0.5.16   2018-11-26 [1] CRAN (R 4.0.2)
 rjson                  0.2.20   2018-06-08 [1] CRAN (R 4.0.2)
 rlang                  0.4.7    2020-07-09 [1] CRAN (R 4.0.2)
 rmarkdown              2.3      2020-06-18 [1] CRAN (R 4.0.2)
 RProtoBufLib           2.0.0    2020-04-27 [1] Bioconductor  
 rstudioapi             0.11     2020-02-07 [1] CRAN (R 4.0.2)
 rsvd                   1.0.3    2020-02-17 [1] CRAN (R 4.0.2)
 Rtsne                  0.15     2018-11-10 [1] CRAN (R 4.0.2)
 rvest                  0.3.6    2020-07-25 [1] CRAN (R 4.0.2)
 S4Vectors            * 0.26.1   2020-05-16 [1] Bioconductor  
 sandwich               2.5-1    2019-04-06 [1] CRAN (R 4.0.2)
 scales                 1.1.1    2020-05-11 [1] CRAN (R 4.0.2)
 scater               * 1.16.2   2020-06-26 [1] Bioconductor  
 sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.0.2)
 shape                  1.4.5    2020-09-13 [1] CRAN (R 4.0.2)
 SingleCellExperiment * 1.10.1   2020-04-28 [1] Bioconductor  
 statmod                1.4.34   2020-02-17 [1] CRAN (R 4.0.2)
 stringi                1.5.3    2020-09-09 [1] CRAN (R 4.0.2)
 stringr              * 1.4.0    2019-02-10 [1] CRAN (R 4.0.2)
 SummarizedExperiment * 1.18.2   2020-07-14 [1] Bioconductor  
 survival               3.2-3    2020-06-13 [1] CRAN (R 4.0.2)
 TH.data                1.0-10   2019-01-21 [1] CRAN (R 4.0.2)
 tibble               * 3.0.3    2020-07-10 [1] CRAN (R 4.0.2)
 tidyr                * 1.1.2    2020-08-27 [1] CRAN (R 4.0.2)
 tidyselect             1.1.0    2020-05-11 [1] CRAN (R 4.0.2)
 tidyverse            * 1.3.0    2019-11-21 [1] CRAN (R 4.0.2)
 tsne                   0.1-3    2016-07-15 [1] CRAN (R 4.0.2)
 vctrs                  0.3.4    2020-08-29 [1] CRAN (R 4.0.2)
 vipor                  0.4.5    2017-03-22 [1] CRAN (R 4.0.2)
 viridis                0.5.1    2018-03-29 [1] CRAN (R 4.0.2)
 viridisLite            0.3.0    2018-02-01 [1] CRAN (R 4.0.1)
 withr                  2.3.0    2020-09-22 [1] CRAN (R 4.0.2)
 xfun                   0.17     2020-09-09 [1] CRAN (R 4.0.2)
 XML                    3.99-0.5 2020-07-23 [1] CRAN (R 4.0.2)
 xml2                   1.3.2    2020-04-23 [1] CRAN (R 4.0.2)
 XVector                0.28.0   2020-04-27 [1] Bioconductor  
 yaml                   2.2.1    2020-02-01 [1] CRAN (R 4.0.2)
 zip                    2.1.1    2020-08-27 [1] CRAN (R 4.0.2)
 zlibbioc               1.34.0   2020-04-27 [1] Bioconductor  
 zoo                    1.8-8    2020-05-02 [1] CRAN (R 4.0.2)

_Originally posted by @nayaracleite in https://github.com/HelenaLC/CATALYST/issues/141#issuecomment-697307973_

**Comment by HelenaLC** [comment]
This is a different error. It's saying the `panel_cols` (default `panel_cols = list(channel = "fcs_colname", 
        antigen = "antigen", class = "marker_class")`, whereas `marker_class` is optional) are not all present in you `panel`. Could you print `head(panel)` here?

**Comment by nayaracleite** [comment]
> head(panel)
  Antigen  fcs_colname marker_class
1    CD16     Bi209Di         type
2    Tbet     Dy161Di        state
3    CD69     Dy162Di        state
4    Ki67     Dy164Di        state
5    CD80     Er166Di         type
6   GATA3     Er167Di        state

> str(panel)
'data.frame':	35 obs. of  3 variables:
 $ Antigen     : Factor w/ 35 levels "Bcl2","C-Peptide",..: 7 35 17 32 18 26 6 2 27 16 ...
 $ fcs_colname : Factor w/ 35 levels "Bi209Di","Dy161Di",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ marker_class: Factor w/ 2 levels "state","type": 2 1 1 1 2 1 1 2 2 1 ...

**Comment by HelenaLC** [comment]
Unless you change panel_cols, it should be “antigen” not “Antigen”?

**Comment by nayaracleite** [comment]
Yeah, you are right. It worked now! thank you
