### ISSUE TITLE
3D UMAP

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#146]
Dear Helena,
Would be there any possibility to implement 3D visualization for UMAP and TSNE ? Can it already be done ? in the original umap package it can be done through n_components=3 but I donno how can it be translated in R and ggplot

Thank you!

**Comment by SamGG** [comment]
In my experience, 3 components aka 3D does not bring anything.
A simple google query links to http://www.sthda.com/english/wiki/impressive-package-for-3d-and-4d-graph-r-software-and-data-visualization which sounds great.
Best.
Samuel

**Comment by bioguy2018** [comment]
Dear Samuel,
Thanks for your reply but I am still wondering how can I initiate the calculation of the third dimension for umap because the umap function provided just does it for x and y! so I am not sure if I can use any global parameter or how is it.

**Comment by HelenaLC** [comment]
To clarify @SamGG's comment- more than 2 dimensions can bring something, but I would argue that 2D plots are already the optimal embedding of the data in 2 dimensions, and >2D-graphics viewed/printed in 2D are (by definition) suboptimal, unless they are interactive.

Regarding you're second point, yes, it is absolutely possible to compute and visualise (in 2D) more than 2 dimensions. For this, and other parameter alterations from the default, you can simply pass arguments to the according `scater::runX` function- see e.g. `?scater::runUMAP` for details. The number of computed dimensions is specified with `ncomponents`. Here's a minimal example:

```
library(CATALYST)
library(patchwork)
library(SingleCellExperiment)

# construct SCE
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- runDR(sce, dr = "UMAP", ncomponents = 3)

> head(reducedDim(sce))
          [,1]       [,2]      [,3]
[1,] -1.159457  1.5653234 -1.263525
[2,] -1.280189  3.2472646 -1.695209
[3,]  5.361231 -4.0154543 -2.516027
[4,] -1.225689  2.4848590 -1.969638
[5,] -1.690918 -0.7781659  2.037197
[6,]  2.096445 -0.3828274 -2.943704

plotDR(sce, color_by = "CD3", dims = c(1, 2)) +
plotDR(sce, color_by = "CD3", dims = c(1, 3)) +
plotDR(sce, color_by = "CD3", dims = c(2, 3)) +
plot_layout(nrow = 1, guides = "collect")
```
![image](https://user-images.githubusercontent.com/14542264/94704687-77585500-0340-11eb-8a6c-cbff796ba6fe.png)
