### ISSUE TITLE
Error in computeSpillmat() workflow

### ISSUE THREAD

**Issue by aaqib-ux** [HelenaLC/CATALYST#157]
After running computeSpillmat(), I was making sanity checks and all(sm >= 0 & sm <= 1) returned with False. Looking at sm matrix, I can see that Gd157Di has range 0-40. While other columns have range 0-1.
157Di is not in our panel, but in default isotope_list. How to get solve this problem.

**Comment by HelenaLC** [comment]
Sorry for the (2 year) delay... Not able to understand / reproduce this from the information given... Please be clearer (including session info, code, relevant outputs etc.) in the future!
