### ISSUE TITLE
Model is nearly unidentifiable: very large eigenvalue

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#160]
Hi Helena

I get a very long message (attached below) after running

ds_res2 <- diffcyt(sce, 
    formula = ds_formula2, contrast = contrast,
    analysis_type = "DS", method_DS = "diffcyt-DS-LMM",
    clustering_to_use = "merging1b", verbose = FALSE)

I have read in other [forums ](https://stats.stackexchange.com/questions/164457/r-glmer-warnings-model-fails-to-converge-model-is-nearly-unidentifiable)that I could solve this by changing some parameters. My two questions are:

How can I change in diffcyt() any of the recommended parameters if needed?
Do I need to change it or does this message mean that my data doesn't have any significant result and therefore I shouldn't change anything?

Thank you for your help.

Regards
Juan

Model failed to converge with max|grad| = 0.015349 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.00233629 (tol = 0.002, component 1)boundary (singular) fit: see ?isSingular
Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.00555007 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00742892 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00240135 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.0223681 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.0051913 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00238886 (tol = 0.002, component 1)boundary (singular) fit: see ?isSingular
Model failed to converge with max|grad| = 0.0199976 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.0389122 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.0047067 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00297547 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.0152538 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00844551 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.0313113 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.022935 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.0240415 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.00217955 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.0241478 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00663443 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00649518 (tol = 0.002, component 1)boundary (singular) fit: see ?isSingular
Model failed to converge with max|grad| = 0.055191 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.104247 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.0157847 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?boundary (singular) fit: see ?isSingular
Model failed to converge with max|grad| = 0.0102596 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?boundary (singular) fit: see ?isSingular 

[.....I have cut most of it....]

- Rescale variables?Model failed to converge with max|grad| = 0.00365807 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.00612798 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00824278 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00280907 (tol = 0.002, component 1)boundary (singular) fit: see ?isSingular
Model failed to converge with max|grad| = 0.00516716 (tol = 0.002, component 1)Model failed to converge with max|grad| = 0.00521023 (tol = 0.002, component 1)boundary (singular) fit: see ?isSingular
Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?Model failed to converge with max|grad| = 0.00921459 (tol = 0.002, component 1)boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular
Model failed to converge with max|grad| = 0.00678294 (tol = 0.002, component 1)Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular
boundary (singular) fit: see ?isSingular

**Comment by SamGG** [comment]
Hi,
While waiting for an answer from Helena, could you tell me if you checked the adequacy with your design? I mean, could you post your design, contrast and formula?
Best.

**Comment by algebio** [comment]
Hi Sam

Thank you for your quick answer.

md
file_name sample_id condition patient_id batch intervention week_of_life    trial_arm
1 P_31B_1.fcs     P_31B   Neonate       P_31   B_1            post          week_6    Intervention
2 P_32A_1.fcs     P_32A   Neonate       P_32   B_1             pre          week_3         Control
3 P_32B_1.fcs     P_32B   Neonate       P_32   B_1            post          week_7         Control
4 P_34A_1.fcs     P_34A   Neonate       P_34   B_1             pre          week_3         Control
5 P_35A_1.fcs     P_35A   Neonate       P_35   B_1             pre          week_3    Intervention
6 P_36A_2.fcs     P_36A   Neonate       P_36   B_2             pre          week_2         Control


ei <- metadata(sce)$experiment_info
(da_formula1 <- createFormula(ei, 
    cols_fixed = "trial_arm", 
    cols_random = "sample_id"))
(da_formula2 <- createFormula(ei, 
    cols_fixed = "trial_arm", 
    cols_random = c("sample_id", "patient_id")))

contrast <- createContrast(c(0, 1))

da_res1 <- diffcyt(sce, 
    formula = da_formula1, contrast = contrast,
    analysis_type = "DA", method_DA = "diffcyt-DA-GLMM",
    clustering_to_use = "merging1b", verbose = FALSE)
da_res2 <- diffcyt(sce, 
    formula = da_formula2, contrast = contrast,
    analysis_type = "DA", method_DA = "diffcyt-DA-GLMM",
    clustering_to_use = "merging1b", verbose = FALSE)

table(rowData(da_res1$res)$p_adj < FDR_cutoff)
table(rowData(da_res2$res)$p_adj < FDR_cutoff)
FALSE  TRUE 
   15          2 

FALSE  TRUE 
   16          1 


ds_formula1 <- createFormula(ei, cols_fixed = "trial_arm")
ds_formula2 <- createFormula(ei, 
    cols_fixed = "trial_arm", cols_random = "patient_id")

ds_res1 <- diffcyt(sce, 
    formula = ds_formula1, contrast = contrast,
    analysis_type = "DS", method_DS = "diffcyt-DS-LMM",
    clustering_to_use = "merging1b", verbose = FALSE)
table(rowData(ds_res1$res)$p_adj < FDR_cutoff)
ds_res2 <- diffcyt(sce, 
    formula = ds_formula2, contrast = contrast,
    analysis_type = "DS", method_DS = "diffcyt-DS-LMM",
    clustering_to_use = "merging1b", verbose = FALSE)
table(rowData(ds_res2$res)$p_adj < FDR_cutoff)



Let me know if I missed anything.

Regards
Juan

**Comment by HelenaLC** [comment]
One thing that's confusion to me is that your sample IDs contain B,A,B,A,A,A, the interventions are post,pre,post,pre,pre,pre, but then the trial arms are intervention,control,control,control,intervention,control - is this a mistake or is there no link between these different variables?

**Comment by HelenaLC** [comment]
In general though, this is a `diffcyt` warning/error and should not be posted here. I recommend moving it to https://github.com/lmweber/diffcyt/issues and closing this issue.

**Comment by algebio** [comment]
Hi Helena

You are right about the variables. A bit confusing but I didn't choose them. No link between them.

Thank you for your feedback. I'll do as recommended.

Regards
Juan
