### ISSUE TITLE
DiffHeatMap visualization (colors)

### ISSUE THREAD

**Issue by antoine4ucsd** [HelenaLC/CATALYST#165]
Hello
I am using your really nice package to analyze flowdata. 
In my differential analyses, I am comparing 1 condition (gender) across 75 patient_id : the heatmap looks great but given the number of colors assigned to all sample_id, the condition (M or F) have the same color assigned. I tried to make my own color panel with smthg like:
``
pal <- col_bin("RdYlBu", domain = 0:100);
test <-c("purple","gold",pal(sort(runif(75, 1, 100))))
``
but I was not successful so far. Any suggestions?

Also, do you have suggestion for differential expression analyses of continuous variables (i.e. not discrete such as treated/not treated, Female vs Male, etc)

thank you

**Comment by HelenaLC** [comment]
Thanks for the positive words. Could you post a screenshot of the heatmap you can now so I can get an idea of what looks / should look like?

**Comment by antoine4ucsd** [comment]
sure. see at the top: both conditions have the same color but the number of pid is large...thank you for being so responsive!
![Screen Shot 2020-12-05 at 10 41 06 AM](https://user-images.githubusercontent.com/18502631/101260717-94b1f280-36e6-11eb-9072-7a2a589e4429.png)

**Comment by antoine4ucsd** [comment]
Hello
just following up on my request. I am also trying to figure out how to extract the dataframe used to plot the exprdensity by clusters (plotClusterExprs function). is there a dedicated function? It should be straightforward but I can't figure this out.
thank you in advance

**Comment by HelenaLC** [comment]
Puh - much harder than I thought! 

1. I found the following workaround... don't ask me why it is that complicated, but it works...

```
library(CATALYST)
library(ComplexHeatmap)
library(diffcyt)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE) 

design <- createDesignMatrix(PBMC_md, cols_design=3:4)
contrast <- createContrast(c(0, 1, 0, 0, 0))

ds <- diffcyt(sce, design = design, contrast = contrast, 
    analysis_type = "DS", method_DS = "diffcyt-DS-limma",
    clustering_to_use = "meta20")

pal <- c(Ref = "black", BCRXL = "grey")
cm <- ColorMapping(
    name = "condition",
    colors = pal)

hm <- plotDiffHeatmap(sce, rowData(ds$res))

# this fixes the legend colors
hm@top_annotation@anno_list$condition@color_mapping <- cm

# this fixes the annotation colors
env <- hm@top_annotation@anno_list$condition@fun@var_env
env$color_mapping <- cm
hm@top_annotation@anno_list$condition@fun@var_env <- env

hm
```

![image](https://user-images.githubusercontent.com/14542264/101609864-c4733a00-3a07-11eb-85c0-4dbde7864415.png)

2. With the last release, I tried adding as much flexibility in setting options for scaling, coloring, clustering, annotation etc. as I could think of. But I forgot this one!! So, feel free to use the above as a super hacky workaround. But definitely I plan to add a `row/col_anno_pal` or similar to control this directly in `plotExpr/Freq/DiffHeatmap()`!

**Comment by HelenaLC** [comment]
Re extracting the `data.frame` underlying *any* `ggplot` (so not the `plotXHeatmap()` outputs, which are `ComplexHeatmap::Heatmap`s), you can simply use `.$data`

```
> data(PBMC_fs, PBMC_panel, PBMC_md)
> sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
> sce <- cluster(sce, verbose = FALSE)
> 
> p <- plotClusterExprs(sce, k = "meta8")
> df <- p$data
> head(df)
  sample_id condition patient_id cluster_id antigen expression avg
1    BCRXL1     BCRXL   Patient1 5 (19.12%)     CD3   3.943394  no
2    BCRXL1     BCRXL   Patient1 5 (19.12%)     CD3   1.314305  no
3    BCRXL1     BCRXL   Patient1  8 (5.62%)     CD3   1.312583  no
4    BCRXL1     BCRXL   Patient1  4 (7.06%)     CD3   2.934988  no
5    BCRXL1     BCRXL   Patient1 1 (24.21%)     CD3   1.184956  no
6    BCRXL1     BCRXL   Patient1 3 (14.98%)     CD3   2.003967  no
```

**Comment by antoine4ucsd** [comment]
Thank you so much for both detailed answers!

a
