### ISSUE TITLE
cluster dendrogram

### ISSUE THREAD

**Issue by antoine4ucsd** [HelenaLC/CATALYST#168]
Hello
is there a way to get cluster dendrogram as attached from the CATALYST::cluster output?

thank you!
![_test](https://user-images.githubusercontent.com/18502631/101718947-1ee7b700-3a57-11eb-8ee6-53a5db6a3298.png)

**Comment by HelenaLC** [comment]
This is a very vague question. A dendrogram as the above has to be computed on something, and doesn't just come with the clustering. For example, one could compute distances on median expression values across clusters, but here are other possibilities. So, I'd say that, yes, you can get such a dendrogram, but here are many ways of getting there. Here's one example (by default, this uses `hclust` with `method = "euclidean"` and 'linkage = 'average'' on median expression values):

```
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

plotExprHeatmap(sce, 
    features = "type", 
    by = "cluster_id")
```
![image](https://user-images.githubusercontent.com/14542264/203326293-b70f63aa-4a1a-427f-8118-3931b89c6cda.png)
