### ISSUE TITLE
Shiny: indicate metal involved when hovering a spillover value

### ISSUE THREAD

**Issue by schevrie** [HelenaLC/CATALYST#17]
In the spillover matrix (shiny app, compensation module, Spillover matrix tab), it is a bit difficult to identify the metal responsible for a given spillover value, since the rows and the columns are really close together. It would be great if the pair of metal related to any given spillover value could be indicated when hovering on them, as it is already done for the yield plot (Debarcoding/Yield Plot).

This would help identifying the relationships that could be worth checking to see if the spillover matrix is accurately correcting the sample.

**Comment by HelenaLC** [comment]
plotSpillmat now gives an interactive heat map displaying spillover, receiving and emitting channel.
