### ISSUE TITLE
Subcluster some of the clusters after running a FlowSOM clustering

### ISSUE THREAD

**Issue by mtrussart** [HelenaLC/CATALYST#170]
I would like to get some advices on how to subcluster some of the clusters after running a FlowSOM clustering and then merge the new subclusters found back to the main clustering. For example I am performing a 20 clusters analysis and I want to subcluster further the cluster 10 let’s say into 3 subclusters. Then I would like to merge those 3 new clusters back to the main 20 clusters and visualise the results using tsne coloured by clusters.
I had a look at the different functions using filterSCE and such, and I was wondering whether you have any suggestions on how to do that efficiently.

Thanks a lot,
Marie

**Comment by HelenaLC** [comment]
Dear Marie,
this is indeed not at all straightforward. I came up with 2 possible solutions, neither of which is as simple as I had thought at first. Briefly, 

- solution 1 renames & rearranges the cluster IDs & codes for the 1st and 2nd round of clustering to give an interpretable output: e.g., 1st round cluster 10 would be renamed to cluster 10.1 10.2 ...
- solution 2 is simpler to implement, however, less interpretable. Here, I shift the 2nd round cluster IDs to not overlap with the first round. E.g., SOM cluster 50 becomes 150 in the second round. Thus, we basically obtain 2 separate clusters that are merged together, but the relationship between 1st and 2nd clustering is less intuitive to follow.

I am not sure if this is the only and/or simplest way to achieve this and will think about it further. Ideally, when I (or anyone else) comes up with a more satisfying solution I would be happy to provide a function for this in the package, e.g. something like`recluster()`.

```
library(CATALYST)
library(patchwork)

# construct SCE
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)

# run clustering & dimension reduction
sce <- cluster(sce, verbose = FALSE)
sce <- runDR(sce, cells = 200)

# specify clustering & subclustering to use
k1 <- "meta10"
k2 <- "meta5"

# specify clusters to recluster
kids <- c(1, 2, 3)

# subset & recluster
sce$cell_id <- seq_len(ncol(sce))
sub <- filterSCE(sce, k = k1, cluster_id %in% kids)
sub <- cluster(sub, verbose = FALSE)

# SOLUTION 1: rearrange cluster IDs & codes
tmp <- sce

# construct new cluster IDs
old <- as.character(tmp$cluster_id[sub$cell_id])
new <- paste(old, sub$cluster_id, sep = ".")

tmp$cluster_id <- as.character(tmp$cluster_id)
tmp$cluster_id[sub$cell_id] <- new

# construct new cluster codes
codes_old <- cluster_codes(tmp)[, c("som100", k1)]
codes_new <- cluster_codes(sub)[, c("som100", k2)]

ss <- strsplit(unique(new), "\\.")
ss <- lapply(ss, as.numeric)
codes <- mapply(
    function(i, j) 
{
    c1 <- codes_old[i, ]
    c2 <- codes_new[j, ]
    data.frame(
        foo = paste(c1$som100, c2$som100, sep = "."),
        meta = paste(c1[[k1]], c2[[k2]], sep = "."))
}, 
    i = sapply(ss, .subset, 1),
    j = sapply(ss, .subset, 2),
    SIMPLIFY = FALSE)
codes <- do.call(rbind, codes)

# merge old & new cluster codes
names(codes) <- names(codes_old)
for (i in seq(ncol(codes_old)))
    codes_old[[i]] <- as.character(codes_old[[i]])
codes <- rbind(codes_old, codes)

# reorder factor levels
for (i in seq(ncol(codes))) {
    o <- order(as.numeric(unique(codes[[i]])))
    codes[[i]] <- factor(codes[[i]], unique(codes[[i]])[o])
}
metadata(tmp)$cluster_codes <- codes

plotDR(sce, color_by = k1) +
plotDR(tmp, color_by = k1) 
```
![image](https://user-images.githubusercontent.com/14542264/102338462-2b5a9b00-3f94-11eb-855d-80d625075f3d.png)
```
# SOLUTION 2: shift subclustering IDs
tmp <- sce

# construct new cluster IDs
old <- as.character(tmp$cluster_id[sub$cell_id])
new <- as.numeric(as.character(sub$cluster_id)) + 100

tmp$cluster_id <- as.character(tmp$cluster_id)
tmp$cluster_id[sub$cell_id] <- new
tmp$cluster_id <- factor(tmp$cluster_id, sort(unique(tmp$cluster_id)))

# shift cluster codes by number of clusters
codes_old <- cluster_codes(tmp)
codes_new <- cluster_codes(sub)

for (i in seq(ncol(codes_new))) {
    new <- as.numeric(as.character(codes_new[[i]]))
    new <- new + max(new)
    codes_new[[i]] <- factor(new, sort(unique(new)))
}

# give intuitive clustering names
codes <- rbind(codes_old, codes_new)
names(codes) <- paste0("sub", sapply(codes, nlevels))
metadata(tmp)$cluster_codes <- codes

plotDR(sce, color_by = k1) +
plotDR(tmp, color_by = "sub16") 
```
![image](https://user-images.githubusercontent.com/14542264/102338516-3b727a80-3f94-11eb-889d-d20b1e4685a1.png)
