### ISSUE TITLE
Extract abundance data

### ISSUE THREAD

**Issue by nvall** [HelenaLC/CATALYST#173]
Hi Helena,
Thank you for providing this great package!
Did you plan to implement a function to extract cluster abundance data to perform downstream analyses?

I developed the function below but maybe you have a better one.

>
>   x = SCE object in which abundance will be calculated
>   k = number of metaclusters (ex: "meta20", "meta10")
>   extract_method = abundance or number of cells

> extAbundances = function(x, k, extract_method = c("abundance","number") ) { 
>   
>   
>   ns = table(  cluster_id = cluster_ids(x, k),    sample_id = sample_ids(x))
> 
>   fq = prop.table(ns, 2) * 100
>   
>   if ( extract_method != "abundance" & extract_method != "number" ) { # if extraction method incorrect => message error
>     
>     cat(crayon::red$bold("not extracted: extract_method should be 'abundance' or 'number' \n") )
>     
>   }
>   
>   if (extract_method == "abundance") {
>     
>     Freq_extracted <<- as.data.frame.matrix( t( fq ) )    # get the table with relative number of events
>     
>     cat(crayon::green$bold( "Freq_extracted: the table with relative number of events \n"  ) )
>     cat(crayon::green$bold( "Data extracted: row=sample_id, columns=metacluster/cluster \n") )
>     
>   } 
>   
>   if (extract_method == "number") { 
>     
>     Numb_extracted <<- as.data.frame.matrix( t( ns ) ) # get the table with absolute number of events
>     
>     cat(crayon::green$bold( "Numb_extracted: the table with absolute number of events \n"  ) )
>     cat(crayon::green$bold( "Data extracted: row=sample_id, columns=metacluster/cluster \n") )
>     
>   } 
>   
> }
> 

Thanks for your help !
Nicolas

**Comment by HelenaLC** [comment]
Have you had a look at @lmweber’s [diffctyt](https://bioconductor.org/packages/release/bioc/html/diffcyt.html) package?

**Comment by nvall** [comment]
Thank you for your prompt answer. I've seen this package but I would like to extract these data to perform other types of analyses. Thanks again. Best.
Nicolas

**Comment by matoriab** [comment]
Hi Nicolas - just wanted to say thanks very much for this bit of code! Really, really helpful.
