### ISSUE TITLE
manual cluster merging

### ISSUE THREAD

**Issue by antoine4ucsd** [HelenaLC/CATALYST#174]
Hello
I am trying to do a manual cluster merging but I get the following error :

``
 plotDR(sce, "UMAP", color_by = "merging1", k = "meta50")
Error in plotDR(sce, "UMAP", color_by = "merging1", k = "meta50") : 
  length(reducedDims(x)) != 0 is not TRUE
``

What I did:
``
sce <- CATALYST::cluster(sce, features =NULL,
                            xdim = 10, ydim = 10, maxK = 50, seed = 1234)
``
length(unique(sce$cluster_id)) is 100 but I have 50 clusters with cluster_ids(sce, "meta50"))

My merging table is made of 50 clusters, not 100 (which might be the issue...)
``
head(merging_table1)
  original_cluster    new_cluster
1                1 CD3+ CD8+ CD4+
2                2 CD3+ CD8+ CD4+
3                3 CD3- CD8+ CD4+
4                4 CD3- CD8+ CD4+

dim(merging_table1)
[1] 50  2
``

however, I am attaching the new cluster at meta50...

``
sce <- mergeClusters(sce, k = "meta50", 
                     table = merging_table1, id = "merging1")
plotDR(sce2, "UMAP", color_by = "merging1", k = "meta50")
``
and I still have this error:

``plotDR(sce2, "UMAP", color_by = "merging1", k = "meta50")
Error in plotDR(sce2, "UMAP", color_by = "merging1", k = "meta50") : 
  length(reducedDims(x)) != 0 is not TRUE
``
for info 
``
glimpse(merging_table1)
Rows: 50
Columns: 2
$ original_cluster <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,…
$ new_cluster      <fct> CD3+ CD8+ CD4+, CD3+ CD8+ CD4+, CD3- CD8+ CD4+, CD3- CD8+ CD4+, CD3- CD8+ CD4+, CD3+ CD8+ CD4+…
``

I guess my error is coming from my misunderstanding of the number of clusters...Any thoughts???
footnote: are you aware of automated cell type identification like it exits for scRNAseq data (singleR pred package)?

thank you!!!

my sce object:

sce
class: SingleCellExperiment 
dim: 9 42990473 
metadata(4): experiment_info cluster_codes SOM_codes delta_area
assays(2): counts exprs
rownames(9): PD-1 CD3 ... CD8 CD4
rowData names(4): channel_name marker_name marker_class used_for_clustering
colnames: NULL
colData names(4): sample_id condition patient_id cluster_id
reducedDimNames(2): UMAP TSNE
altExpNames(0):

**Comment by antoine4ucsd** [comment]
fixed

**Comment by HelenaLC** [comment]
1. The clustering stored in the SCE's `colData` under `sce$cluster_id` are the `xdim = 10` x `ydim = 10` = 100 clusters (coming from the `FlowSom` clustering). If you want to access other clusterings, you should use the `cluster_ids()` accessor, e.g. the following would count the number of clusters in each of the clusterings:

```
clusterings <- names(cluster_codes(sce))
sapply(clusterings, function(k) {
    cluster_ids <- cluster_ids(sce, k)
    length(unique(cluster_ids))
})
```

2. The error in `plotDR()` says `length(reducedDims(x)) != 0 is not TRUE`, suggesting there are no dimensionality reductions available in the object. You can check this by simply printing the SCE (`show(sce)`), or checking for DRs explicitly with `reducedDims(sce)`. If there's nothing there, I'm guessing you didn't run `runDR()`.

3. If you run `mergeClusters()` with `k = "meta50"` and your merging table has 50 rows, that is correct! I see `sce` does have reduced dimensions, however, the code above says `plotDR(sce2)` - so my question is what is `sce2`?

**Comment by HelenaLC** [comment]
Closing this as I haven't heard back. Feel free to reopen the issue if it is still unresolved!
