### ISSUE TITLE
Setting min/max cell number thresholds for SCE

### ISSUE THREAD

**Issue by alpercevirgel** [HelenaLC/CATALYST#176]
Hey Helena, thanks for the beautiful pipeline! I have a question regarding the cell numbers in the SCE object. 

Before starting the analysis I would like to exclude fcs files with too few cell numbers and set a max limit of cell numbers for the fcs files with many events (to make sure that analysis will not be skewed by the fcs files with too many events). I checked the arguments in read.flowset and prepdata functions but couldn't find a solution. Do you know an easy way of doing this?

Many thanks.
Alper

**Comment by HelenaLC** [comment]
Not sure about `read.flowSet`, but doing this starting from the SCE is straightforward. Something like the following should do the trick:
```
# construct 'SingleCellExperiment'
sce <- prepData(...)

# set thresholds on number of cells
min_cells <- 1e3
max_cells <- 5e4

# tabulate number of cells in each sample
n_cells <- table(sce$sample_id)

# exclude samples with with less than 'min_cells' or more than 'max_cells'
rmv <- n_cells < min_cells | n_cells > max_cells
sce <- filterSCE(sce, sample_id %in% names(which(rmv)))
```

**Comment by HelenaLC** [comment]
Apologies if I misunderstood - I think you might want to downsample large samples rather then exclude them. In that case:
```
# exclude samples with with less than 'min_cells'
rmv <- n_cells < min_cells
sce <- filterSCE(sce, sample_id %in% names(which(rmv)))

# downsample samples with more than 'min_cells'
cells_by_sample <- split(seq(ncol(sce)), sce$sample_id)
cells_keep <- unlist(lapply(cells_by_sample, 
    function(.) sample(.,min(length(.), max_cells))))
sce <- sce[, cells_keep]
```

**Comment by alpercevirgel** [comment]
Thank you very much!
