### ISSUE TITLE
non-metal channels not identified when supplying marker panel

### ISSUE THREAD

**Issue by BenPVD** [HelenaLC/CATALYST#178]
Hi!

I am currently loading my Cytof dataset using Catalyst's `prepData` function. Unfortunately, non-metal channels are not correctly identified, as mentioned in the manual/vignette. Please see code below.

In option 1, I am loading the dataset without the marker panel (a separate data frame containing the information for all the metal channels), in option 2 a marker panel is supplied, leading to only two channels identified as non-metal channels ("altExps" and "reducedDims"). This leads to errors downstream of the Catalyst pipeline.

Any ideas what I might do wrong?
It seems like an odd behavior (possibly bug).

I was also printing out the dimensions of the assay data for comparisons.

Thanks much for your help!

```
marker_panel <- vroom::vroom(file = base::file.path("~", "panel.csv"))
#> New names:
#> * `` -> ...5
#> Rows: 56
#> Columns: 29
#> Delimiter: ","
#> chr [22]: fcs_colname, antigen, marker_class, channel, ...5, reactivity, instrument_type, ...
#> dbl [ 6]: channel_min, channel_max, imported_exp, active, label_product_id, tolerance_di
#> lgl [ 1]: kit_instrument_avail
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message

sample_panel <- vroom::vroom(file = base::file.path("~", "samples.txt"))
#> Rows: 19
#> Columns: 5
#> Delimiter: "\t"
#> chr [3]: sample_id, patient_id, file_name
#> dbl [2]: condition, concat
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message

# OPTION 1

sce_data_1 <- CATALYST::prepData(
  x = base::file.path("~/example"),
  # panel = marker_panel,
  md = sample_panel,
  features = NULL,
  FACS = FALSE,
  transform = TRUE,
  cofactor = 5
)

base::names(x = SingleCellExperiment::int_colData(x = sce_data_1))
#> [1] "Time"         "Event_length" "Center"       "Offset"       "Width"       
#> [6] "Residual"     "altExps"      "reducedDims"

base::dim(x = SummarizedExperiment::assay(x = sce_data_1))
#> [1]      56 4341756



# OPTION 2

sce_data_2 <- CATALYST::prepData(
  x = base::file.path("~/example"),
  panel = marker_panel,
  md = sample_panel,
  features = NULL,
  FACS = FALSE,
  transform = TRUE,
  cofactor = 5
)

base::names(x = SingleCellExperiment::int_colData(x = sce_data_2))
#> [1] "altExps"     "reducedDims"

base::dim(x = SummarizedExperiment::assay(x = sce_data_2))
#> [1]      56 4341756


Created on 2021-01-12 by the reprex package (v0.3.0)
```

**Comment by HelenaLC** [comment]
Dear Ben, 
maybe I'm missing something, but it looks to me like `prepData()` is doing when it's supposed to do.

1. Without the `panel` argument and `features = NULL`, all features are kept initially. Then, since `FACS = FALSE`, non-metal markers are moved to the object's `int_colData` slot.

2. When specifying a `panel` and `features = NULL`, only features listed under `marker_panel$fcs_colname` are retained: `marker_panel`'s `Rows: 56` and the output `sce_data_2` has 56 rows as well.

**Comment by HelenaLC** [comment]
Is this resolved? If so, please close the issue :) Otherwise, please let me know if there's still something that's unclear. Thanks!
