### ISSUE TITLE
shiny: Name is the browser tab is not correct

### ISSUE THREAD

**Issue by schevrie** [HelenaLC/CATALYST#18]
When opening Shiny in the browser: http://imlstaupo.uzh.ch:3838/CATALYSTLite/, It would be nicer if the name in the browser tab would be CATALYST only and not  CATALYST <i class=.....>

**Comment by HelenaLC** [comment]
Mark, is it possible to have it "CATALYST" instead of "CATALYSTLite"? I think this is what SC means...

**Comment by schevrie** [comment]
no, I mean the name in the title of the page
. 

A comment from Vito actually, and I agree with him that it would look better if only Catalyst was written.



-----HelenaLC <notifications@github.com> schrieb: -----
An: HelenaLC/CATALYST <CATALYST@noreply.github.com>
Von: HelenaLC <notifications@github.com>
Datum: 26.09.2017 10:59
Kopie: schevrie <stephane.chevrier@uzh.ch>, Author <author@noreply.github.com>
Betreff: Re: [HelenaLC/CATALYST] shiny: Name is the browser tab is not correct (#18)

Mark, is it possible to have it "CATALYST" instead of "CATALYSTLite"? I think this is what SC means...

**Comment by HelenaLC** [comment]
I don't get it... Title of what page? Where? Your original comment was "[... ]CATALYST only and not CATALYST", which doesn't make any sense.
