### ISSUE TITLE
Identifying number of cells per annotated cluster

### ISSUE THREAD

**Issue by LaurenReich** [HelenaLC/CATALYST#183]
The "plotAbundances" function is great to look at the difference in proportion between clusters, but what about the difference in cell number?

I've tried and failed to create data frames of what I want (my Single Cell Experiment is called scem):

> data.frame("cell" = row.names(scem@colData@nrows), "cluster" = scem@metadata$cluster_codes$cluster)
> Error in data.frame(cell = row.names(scem@colData@nrows), cluster = scem@metadata$cluster_codes$cluster) : 
>   arguments imply differing number of rows: 0, 100
I just don't think I fully understand how/where this data is stored in the sce to go this route.

I also tried to use sizeFactors() to parse out what I want, but I'm stuck. Has anyone tried to get this information? Coding rookie here. Thanks!

**Comment by nvall** [comment]
Hi,
If you want to extract number of cells from metaclusters or merged clusters by sample ids you should try this:

`extract_data = table(sample_ids (scem), clusters_ids (scem , "your cluster name: eg meta20 or merged") )`

The output is a table that can be transformed in a data frame and if you are interested in relative abundance you could create a new var that sum all events and divide each number of cells per cluster by the sum.

Hope it helps,
Nicolas

**Comment by LaurenReich** [comment]
> Hi,
> If you want to extract number of cells from metaclusters or merged clusters by sample ids you should try this:
> 
> `extract_data = table(sample_ids (scem), clusters_ids (scem , "your cluster name: eg meta20 or merged") )`
> 
> The output is a table that can be transformed in a data frame and if you are interested in relative abundance you could create a new var that sum all events and divide each number of cells per cluster by the sum.
> 
> Hope it helps,
> Nicolas

Thank you so much!! Could not figure it out for the life of me.
