### ISSUE TITLE
Alter metadata in established SCE

### ISSUE THREAD

**Issue by poconnel3** [HelenaLC/CATALYST#186]
Sorry if this is a silly question, but I can't find the answer in any of the documentation. 

How can I edit a metadata parameter in an already established SCE?

I need to change the names of all of the "sample_id" values. 

Thank you!

**Comment by nvall** [comment]
Hi,
This may not be the easiest or straightforward solutions, but I would load a dataframe/table with `old_ids` and corresponding `new_ids` then either loop the following:

1.  I append the new ids in the sce object from this command:  `colData(sce)` 

```
w = which( colData(sce)[  , "sample_id"] == "old_id1" # get all rows annotated with old_id1
colData(sce)[ w , "sample_id" ] = "new_id1" # append the new annotation to old_id1 rows
```

2. Or, if you want to keep all the `old_ids` you can create a new metadata option by using `sce$new_ids`, this solution will allow you to build ` table( sce$new_ids, sce$sample_id)` in which you will be able to check if your new sample_id have been correctly modified.

Nicolas

**Comment by poconnel3** [comment]
> Hi,
> This may not be the easiest or straightforward solutions, but I would load a dataframe/table with `old_ids` and corresponding `new_ids` then either loop the following:
> 
> 1. I append the new ids in the sce object from this command:  `colData(sce)`
> 
> ```
> w = which( colData(sce)[  , "sample_id"] == "old_id1" # get all rows annotated with old_id1
> colData(sce)[ w , "sample_id" ] = "new_id1" # append the new annotation to old_id1 rows
> ```
> 
> 1. Or, if you want to keep all the `old_ids` you can create a new metadata option by using `sce$new_ids`, this solution will allow you to build ` table( sce$new_ids, sce$sample_id)` in which you will be able to check if your new sample_id have been correctly modified.
> 
> Nicolas

Hi Nicolas, 

I tried this, but am unable to add in the new ids to the original sce. I get the error:

> colData(daf_X_clean)$new_ids <- md2$new_ids
Error in `[[<-`(`*tmp*`, name, value = c("ERAP1_KO_3", "WT_5", "WT_6",  : 
  36 elements in value to replace 938399 elements

Since it is trying to apply it to every cell in the sce with only a few sample_id names. 

Do you have any other ideas?

**Comment by poconnel3** [comment]
Thanks for the updated attempt Nicolas, but it is still not working. Even after playing with the syntax the loop still does not run. I am wondering if there is a Tidy solution to this? @HelenaLC

**Comment by HelenaLC** [comment]
Here you go ... note that, in this example, I purposefully don't replace all IDs to show that the code is robust in case you want to rename only a subset of samples.

```
> library(CATALYST)
> data(PBMC_fs, PBMC_panel, PBMC_md)
> sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
> 
> # unfactor sample IDs, 
> # else overwriting won't work
> sce$sample_id <- as.character(sce$sample_id)
> 
> # check current sample IDs
> table(sce$sample_id)

BCRXL1 BCRXL2 BCRXL3 BCRXL4   Ref1   Ref2   Ref3   Ref4 
   528    665    563    934    881    438    660    759 
> 
> # specify new <-> old sample IDs
> tbl <- data.frame(
+     old = paste0("Ref", seq(4)),
+     new = paste0("Ctrl", seq(4)))
> head(tbl)
   old   new
1 Ref1 Ctrl1
2 Ref2 Ctrl2
3 Ref3 Ctrl3
4 Ref4 Ctrl4
> 
> # match old to current & overwrite with new
> i <- match(sce$sample_id, tbl$old, nomatch = 0)
> sce$sample_id[i != 0] <- tbl$new[i]
> 
> # check new sample IDs
> table(sce$sample_id)

BCRXL1 BCRXL2 BCRXL3 BCRXL4  Ctrl1  Ctrl2  Ctrl3  Ctrl4 
   528    665    563    934    881    438    660    759 
```

**Comment by poconnel3** [comment]
Thanks for this solution @HelenaLC, it works, but not how I need it. I should have been more specific in my original question. 

I have 2 samples from each individual. One from CNS and one from spleen. I named them w/ the same sample_id originally since they are from the same individual, but this of course leads to issues when comparing samples from different locations since they do not have unique sample_ids. 

I need to create new sample_id names for all the samples from one location (CNS for example). 

So my metadata looks like this now:

> table(daf_WT$sample_id, daf_WT$location)
      
       spleen   CNS
  WT_1  91714 11419
  WT_2  92172 12467
  WT_3  92981 14589
  WT_4  92648 12777

Is there a way to do this since it would involve creating new sample_ids?

**Comment by HelenaLC** [comment]
1. Wouldn't it be simplest to just rerun `prepData` with the correct `panel` from the start? Seems not so clean to change this downstream in my opinion...
2. You could simply overwrite the affected IDs using something like
```
i <- grep("WT_[0-9]+$", sce$sample_id)
cd <- data.frame(colData(sce))
new <- with(cd, paste(sample_id, location, sep = "."))
sce$sample_id[i] <- cd[i]
```
which would result in changing the IDs you posted above to something like WT_1.spleen, WT_1.CNS, ...

**Comment by poconnel3** [comment]
That would have been easiest, but unfortunately I already did a large amount of analysis before I remembered this issue exists. 

That solution is a nice workaround though for those us who make silly mistakes like me.

**Comment by purisuto** [comment]
Hi Helena,

I have a follow up question.  I am able to add new metadata fields to an sce, but for some reason, when using `md <- ei(sce)` , these new fields do not show up.  I have tried looking in `ei()` using `trace(ei, edit = TRUE)` but I can't find the actual `ei()` function.  This would normally not be a problem, however `diffcyt()` needs the samples to be in the same order as `ei()` for making the design matrix.  My other function for extracting the metadata and Freq values does not put them in the same order as `ei()`.

Kind Regards,
David Priest

**Comment by purisuto** [comment]
One thing I noticed is that `ei()` may not give any metadata fields that were added later to an sce.

Best,
David

**Comment by SamGG** [comment]
`ei()` is an alias. It is defined to `e`xtract `i`nformation, not to set some. You should use the functions dedicated to the `sce` object to add information. Just my opinion.
https://github.com/HelenaLC/CATALYST/blob/54bd90dedcef529b59cf13aa72a84eb63e669af9/R/AllMethods.R#L82-L85

**Comment by purisuto** [comment]
Thanks for that reference to location of `ei()` function.  I was using `lapply()` to add extra metadata fields to an sce as detailed here (https://stackoverflow.com/questions/35636315/replace-values-in-a-dataframe-based-on-lookup-table).  The strange thing that I don't understand is that, while functions like `filterSCE` can see these updated fields `ei()` cannot.  I wonder if `ei()` is looking at slightly different information that does not get updated by `lapply()`  method?

**Comment by purisuto** [comment]
Sorry I wasn't clear with my comment.  Yes of course I know what `ei()` does.  I was asking whether `ei()` function be updated so that it gives metadata fields that have been updated instead of those that were originally compiled with the sce using `prepData()`?

**Comment by purisuto** [comment]
Thank you very much.  That's what I was missing.  Code below extracts metadata out of the sce.

`sce_get <- function(sce, meta = c("patient_id"))
  
{
  
# Make a data frame containing cluster abundances
ns <- table(sample_id = sample_ids(sce))
df <- as.data.frame(ns)
m <- match(df$sample_id, sce$sample_id)

  
# Extract any other metadata into the df data frame (replace the variables in c() with your own choices).
for (i in meta) df[[i]] <- sce[[i]][m]

return(df)
}`
