### ISSUE TITLE
Using a different clustering per cell

### ISSUE THREAD

**Issue by mtrussart** [HelenaLC/CATALYST#187]
I would like to know how to be able to use the features of CATALYST and plotting functions when I am using a different clustering for each cell than the one obtained from the package. In this case, I do not have a corresponding value in the codes as it does not use the som.
I am especially having some troubles with the k= "metaxx" parameter that I need to give to some function like plotExprHeatmap(). I would like to be able to select which clustering to use like I do for the tSNE plot for example, I have assigned the new clustering in the daf object as daf$new_cluster and I can do: plotDR(daf, "TSNE", color_by = "new_cluster").

Thanks a lot,
Marie

**Comment by HelenaLC** [comment]
Dear Marie,
For an example of how to incorporate e.g. `Phenograph` into `CATALYST`, see the corresponding section in the vignette on *using other clustering algorithms*: https://bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html#using-other-clustering-algorithms

In addition, I wrote a minimal example to i) run `FlowSOM` (i.e. `CATALYST::cluster`), and ii) add another arbitrary clustering:
```
library(CATALYST)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, maxK = 10, verbose = FALSE)

names(kids) <- kids <- names(cluster_codes(sce))

codes <- lapply(kids, 
    function(k) {
        kids <- cluster_ids(sce, k)
        factor(kids, sort(unique(kids)))
    })

codes <- data.frame(foo = seq(ncol(sce)), codes)
> head(codes)
  foo som100 meta2 meta3 meta4 meta5 meta6 meta7 meta8 meta9 meta10
1   1     55     1     1     3     3     4     5     5     6      7
2   2     92     1     1     3     3     4     5     5     6      7
3   3    100     2     3     4     5     6     7     8     9     10
4   4     56     1     1     2     1     3     4     4     4      5
5   5     33     1     1     1     1     1     1     1     1      1
6   6     39     1     2     2     2     2     3     3     5      6

tmp <- sce
tmp$cluster_id <- seq(ncol(tmp))
metadata(tmp)$cluster_codes <- codes

# these are identical
plotExprHeatmap(sce, k = "meta10", by = "cluster_id")
plotExprHeatmap(tmp, k = "meta10", by = "cluster_id")

# add some arbitrary cluster IDs
kids <- sample(seq(5), ncol(sce), TRUE)
kids <- factor(kids, sort(unique(kids)))

metadata(tmp)$cluster_codes$foo <- kids
plotExprHeatmap(tmp, k = "foo", by = "cluster_id")
```

**Comment by purisuto** [comment]
Will this work with Diffcyt?  I tried it and it runs without error, but does not give the same result as if the merging was used from unaltered cluster codes.  If I simply replace the cluster codes with a 1 column list of the unique values of a custom merging, it gives the following error:

```
Error in if (!all(rownames(top) == cluster_id)) { : 
  missing value where TRUE/FALSE needed
2.
testDA_edgeR(d_counts, design, contrast, trend_method, min_cells, min_samples, normalize, norm_factors) at <tmp>#94
1.
diffcyt(scefilt, clustering_to_use = "merging_combined", analysis_type = "DA", method_DA = "diffcyt-DA-edgeR", design = design, contrast = contrast, verbose = TRUE)
```

Basically, most of the custom merging we do is a concatenation of a phenotypic merging (with one set of type markers), with another merging (using a different set of markers like isotypes).  It would be good to be able to just use the column data for all CATALYST functions (I got working for plotDR and plotExprHeatmap) and diffcyt (which is too hard to change).

**Comment by SamGG** [comment]
For reference https://github.com/lmweber/diffcyt/issues/56

**Comment by HelenaLC** [comment]
If something’s off with `diffcyt` when passing clustering annotations from a different method, please post an issue there (referencing this one) as I am not the author of that package/familiar in detail with how the code handles different inputs.

**Comment by SamGG** [comment]
@HelenaLC Could you check that `tmp$cluster_id <- seq(ncol(tmp))` is correct? I feel values should range from 1 to 100. To be honest, I don't really understand the goal of the lapply section. I am trying to build a reproducible example based on your example to verify the connection with diffcyt.

**Comment by HelenaLC** [comment]
It is. At least in the example above this works when manual clusters are being assigned. I wonder if passing cluster IDs directly in `diffcyt` works? I.e., not relying on `cluster_codes`. I believe `diffcyt` has an argument to do this.

**Comment by SamGG** [comment]
`diffcyt` is a workhorse with a large number of options. If `clustering_to_use` is NULL (as default), `diffcyt` will rely only the `cluster_id` vector and ignore `cluster_codes`. If `clustering_to_use` is set (e.g. "meta20"), it will be used to get the clustering at this given metaclustering resolution.

From my recent readings, IIUC the example given above:

1. `nrow(cluster_codes)` ends up to be equal to `ncol(sce)`, in which case we loose the initial compactness of cluster_codes.
2. adding a foo clustering/column in cluster_codes should be avoided (especially as first column) because it could interfere with `cluster_ids()` that considers the 1st column being the high resolution clustering for any meta-clustering

https://github.com/HelenaLC/CATALYST/blob/f3e294ed9a4d3f300feb994bb381df6a6b2c8309/R/AllMethods.R#L145-L153

**Comment by SamGG** [comment]
From my recent readings and conclusions https://github.com/HelenaLC/CATALYST/issues/381#issuecomment-1880959200, I feel that cluster_ids and cluster_codes should be managed as a pair. Here are two proposals to simplify their management.

First, the following function could simplify setting a custom clustering, because frequently there is no metaclustering.

```
# k is the name of a high resolution clustering
# this could be a method such as `cluster_id<-` if this makes sense
set_cluster <- function(x, kids=NULL, k=NULL) {
  stopifnot(
    inherits(x, "SingleCellExperiment"),
    !is.null(kids),
    is.integer(kids) || is.factor(kids),
    length(kids) == ncol(x)
  )
  if (is.integer(kids))
    kids <- factor(kids)
  x$cluster_ids <- kids
  kcodes <- data.frame(custom = factor(levels(kids), levels = levels(kids)))
  if (!is.null(k))
    colnames(kcodes) <- k
  x$cluster_codes <- kcodes
}
```

Second, the following functions could permit to store and and switch among multiple clusterings.

```
# k is the name of a high resolution clustering
# each high resolution clustering (aka cluster_ids) is stored in a column of colData
# k_codes is a list to store each cluster_codes in the metadata slot
store_cluster <- function(x, k) {
  colData(x)[[k]] <- x$cluster_ids
  metadata(x)$k_codes[[k]] <- x$cluster_codes
}

use_cluster <- function(x, k) {
  # k is the name of a high resolution clustering
  x$cluster_ids <- colData(x)[[k]]
  x$cluster_codes <- metadata(x)$k_codes[[k]]
}
```

**Comment by purisuto** [comment]
It would be convenient in both Diffcyt and CATALYST to have an option in every function to simply use a clustering stored in the column data that bypasses any reference to cluster codes.  We are constantly making custom clustering (e.g. isotypes, AIM assay).
