### ISSUE TITLE
Question - How do I pull out specific clusters.

### ISSUE THREAD

**Issue by ammasakshay** [HelenaLC/CATALYST#191]
For example,

Supposing I have 20 clusters. I am interested in cluster 1,2,3,5,8.

The current way to do so is

```
 # store final clustering in cell metadata
sce$mm <- cluster_ids(sce, "meta10")
# convert to 'flowSet' with one frame per cluster 
(fs <- sce2fcs(sce, split_by = "mm"))
```

here meta10 selects cluster 1 to 10.

However I simply want 1,2,3,5 and 8.

Im assuming the way to do this would then be to create in names(cluster_codes(sce)) an object that has 1,2,3,5 and 8. I'm currently unaware on how to do so (or if it can be done.

Thanks

**Comment by HelenaLC** [comment]
```
sub <- filterSCE(sce, k = "meta10", cluster_id %in% c(1, 2, 3, 5, 8))
fs <- sce2fcs(sce, split_by = "meta10")
```

**Comment by ammasakshay** [comment]
So I'm still getting an error here

Error in .check_args_sce2fcs(args) : 
  is.null(u$split_by) || is.character(u$split_by) && length(u$split_by) ==  .... is not TRUE

**Comment by HelenaLC** [comment]
My apologies, yes, you need to add the IDs to split by into the cell metadata (`colData`) first. So correcting the code above:
```
sub <- filterSCE(sce, k = "meta20", cluster_id %in% c(1, 2, 3, 5, 8))
sub$meta20 <- cluster_ids(sub, "meta20")
fs <- sce2fcs(sub, split_by = "meta20")
```

**Comment by ammasakshay** [comment]
Thank you so much. It seems to be working.

```
sub <- filterSCE(scetype3, k = "meta12", cluster_id %in% c(1, 2, 7, 8, 11, 12))
sub$meta12 <- cluster_ids(sub, "meta12")
fs <- sce2fcs(sub, split_by = 'condition')

ids <- fsApply(fs, identifier)

ids

for (id in ids) {
  ff <- fs[[id]]                     # subset 'flowFrame'
  fn <- sprintf("clustered_sample_%s.fcs", id) # specify output name that includes ID
  fn <- file.path("...", fn)         # construct output path
  write.FCS(ff, fn)                  # write frame to FCS
}

```

The idea here is that I am only interested in a few specific clusters that make up a small subset of the total cell population. I want to recluster with only these cells and look at the marker expression of only these cells. Is what I've done alright?

In essence,

 Preprocessing -> Clustering -> Identifying specific clusters -> writing .fcs to each condition with ONLY the clusters of interest -> rerunning everything from the clustering step.

Thanks again!

**Comment by HelenaLC** [comment]
In principle, yes, that all looks correct to me! Here an additional note:

1. If you're interested in looking the the each cluster (1, 2, 7, ...) elsewhere, it's worth writing out separate FCS files.
2. Meanwhile, if you're aim is to re-analyse them, there's no need to do this, as you directly proceed with the subsetted data (`sub`), e.g.:

```
# analyse all data
sce <- prepData(...)
sce <- cluster(sce, ...)
sce <- runDR(sce, ...)
...

# subset clusters of interest
sub <- filterSCE(sce, cluster_id %in% ...)

# re-analysie subset
sub <- cluster(sub, ...)
sub <- runDR(sub, ...)
...
```

**Comment by ammasakshay** [comment]
This means I don't need to write them out to new .fcs files before I re-analyze. Thank you!
