### ISSUE TITLE
How does the scaling in plotExprHeatmap() work?

### ISSUE THREAD

**Issue by JiajiaChen1** [HelenaLC/CATALYST#194]
Hi Helena,

 The vignette says that data will be scaled using lower (q%) and upper (1-q%) quantiles as boundaries, but I am still unsure how it is computed. could you give me an example? 

  Thanks for your time!

**Comment by HelenaLC** [comment]
Internally, scaling uses the wrapper below ... Here, `margin = 1/2` determines whether to scale rows/columns. This will depend on the heatmap layout, but generally we scale each marker. `q = 0.01` is the quantile use to define boundaries: by default, these are lower (q = 1%) and upper (1-q = 99%). 

Say you have a marker with expression x = 0, 1, ..., 100. The 1/99% quantiles are 1/99. We subtract the 1% quantile x, and divide by the difference between quantiles (99-1=98). Finally, values < 0 and > 1 are set to 0 and 1, respectively. So we'd obtain

x = 0, 1, ..., 100
q1 = 1
q99 = 99

(x / q1) / (q99 - q1)
= (x / 1) / (99 - 1)
= [0, 1, ..., 100] / 98
= [0, 1/98, ..., 98/98, 99/98, 100/98]
= [0, 0, ..., 1, 1, 1]

As you can see in this (very simple) example, what this basically does it to *trim* values below/above q1/q99. So expression values falling below the 1% quantile are set to 0, those above the 99% quantile are set to 1. To get a better feel for this, you could apply the function below to some expression, and plot before vs. after scaling.

```
# ==============================================================================
# scale expression to values b/w 0 and 1 using 
# low (1%) and high (99%) quantiles as boundaries
# ------------------------------------------------------------------------------
#' @importFrom matrixStats rowQuantiles
#' @importFrom methods is
.scale_exprs <- function(x, margin = 1, q = 0.01) {
    if (!is(x, "matrix")) x <- as.matrix(x)
    qs <- c(rowQuantiles, colQuantiles)[[margin]]
    qs <- qs(x, probs = c(q, 1-q))
    qs <- matrix(qs, ncol = 2)
    x <- switch(margin,
        "1" = (x - qs[, 1]) / (qs[, 2] - qs[, 1]),
        "2" = t((t(x) - qs[, 1]) / (qs[, 2] - qs[, 1])))
    x[x < 0 | is.na(x)] <- 0
    x[x > 1] <- 1
    return(x)
}
```
