### ISSUE TITLE
Is it possible to connect paired samples with plotAbundances?

### ISSUE THREAD

**Issue by matoriab** [HelenaLC/CATALYST#197]
Hi Helena,

Thanks for this brilliant pipeline.

I have longitudinal patient samples and would like to check the abundances of my clusters in response to the first dose of treatment. 

I've been using the following code:

abundances_BLPC2 <- plotAbundances(sce_BLPC2, k = "meta20", by = "cluster_id", group_by ="timepoint", shape_by = "patient")

Here I subsetted my sce to include only the pre (BL) and post (PC2) timepoints. 

This works well, but ideally, in the plot I'd like to have a line connecting the paired samples, instead of plotting them individually and labelling them according to patient. Is this possible? I've been looking online but can't seem to find the answer. Thanks a lot for your time and help; it's much appreciated!

**Comment by HelenaLC** [comment]
Would you be willing to post the plot you currently get, so I can better understand what you’d like to get? In any case I’ll have a look!

**Comment by matoriab** [comment]
Here's what I currently get:

![pairedsamples_Helena](https://user-images.githubusercontent.com/81634303/114528202-b4cb6280-9c40-11eb-8b90-47cc19b99ee5.png)

And here's what I'd like the plot to look like, for each cluster:

![image](https://user-images.githubusercontent.com/81634303/114528347-d88ea880-9c40-11eb-807c-9bc0daac4740.png)

Thanks very much!

**Comment by HelenaLC** [comment]
Below 1) an example of how to add these connections to the plot. Alternatively, 2) you can extract the plotted data a DIO - the below isn't so pretty, but you can easily modify the aesthetic to your personal liking.

```
library(CATALYST)
library(ggplot2)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

p <- plotAbundances(sce, 
    k = "meta8", 
    by = "cluster_id", 
    group_by = "condition", 
    shape_by = "patient_id") +
    geom_path(lty = 3, aes(condition, group = patient_id))
```
![image](https://user-images.githubusercontent.com/14542264/114531606-57d5a980-9c4c-11eb-96b7-00d742b2fcac.png)

```
df <- p$data
> head(df)
  cluster_id sample_id      Freq patient_id condition
1          1      Ref1 28.263337   Patient1       Ref
2          2      Ref1 35.187287   Patient1       Ref
3          3      Ref1  3.518729   Patient1       Ref
4          4      Ref1  8.740068   Patient1       Ref
5          5      Ref1  8.967083   Patient1       Ref
6          6      Ref1  6.015891   Patient1       Ref

ggplot(df, aes(condition, Freq, group = patient_id)) +
    facet_wrap(~ cluster_id, ncol = 4) +
    geom_point() + geom_path() 
```
![image](https://user-images.githubusercontent.com/14542264/114531523-442a4300-9c4c-11eb-8fe6-a798ec6fe711.png)

**Comment by matoriab** [comment]
Thank you so very much! Just what I needed :)
