### ISSUE TITLE
plotExprs(sce) not showing all type markers

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#202]
Hi

I am trying to analyse a fcs file which has 40 markers (29 type, 9 state, 2 none). My problem is that figure 1 doesn't show all type makers. I have used the this code:

p <- plotExprs(sce, color_by = "condition")
p$facet$params$ncol <- 6
p

FCS attached.

What am I doing wrong?

Regards
Juan
[shared.zip](https://github.com/HelenaLC/CATALYST/files/6376854/shared.zip)

**Comment by HelenaLC** [comment]
```
> library(CATALYST)
> 
> fcs <- "~/Downloads/shared/ROI001.fcs"
> panel <- readxl::read_xlsx("~/Downloads/shared/panel2.xlsx")
>                                                                                       
> sce <- prepData(x = fcs, panel = panel)
> dim(sce)
[1]   35 9775
> 
> # some channels have been moved to an internal slot
> # because they are not recognized as mass channels
> names(int_colData(sce))
[1] "reducedDims" "altExps"     "colPairs"    "MPO"         "Podoplanin"  "EPCAM"      
[7] "ProSPC"      "HLADR"      
> 
> # setting FACS = TRUE fixes this
> # and there are now 40 markers
> sce <- prepData(x = fcs, panel = panel, FACS = TRUE)
> dim(sce)
[1]   40 9775
```

**Comment by algebio** [comment]
Hi Helena

Thank you very much for your answer. That solved the issue. 

Interestingly, the data come from an imaging mass cytometry file exported as fcs. I wonder why I need FACS = T, which I thought it was only for flow cytometry data. It would be great to know your opinion, so we can learn about this.

Anyhow, thank again for your great work with CATALYST.

Regards
Juan

**Comment by HelenaLC** [comment]
Hm, it seams to me this is a rare case then - in CyTOF, usually, the channel names would also contain the isotope masses (not just e.g. HLADR). These would then be used to distinguish measurement channels from e.g. time, event length etc. channels in CyTOF. Not sure why, when this is IMC data, the channels no longer contain numeric masses at all... Maybe you have some renaming setup when exporting the FCS? I don't have experimental experience here myself, so I really don't know...

**Comment by algebio** [comment]
Hi Helena

Thank you for your comment. The only info I can add, just in case anyone else is interested, is that I used IMACytE to export the data as fcs. No setting options available, just export as fcs or csv.

Regards
Juan
