### ISSUE TITLE
Storage of different UMAP or TSNE

### ISSUE THREAD

**Issue by Behind42** [HelenaLC/CATALYST#205]
Hello, 

I have a question, maybe stupid, but I didn't find out how to resolve it for now. 
I would like to store different UMAP of the same data in one single sce object, for example, UMAP with different parameters. 

I saw that putting name = "UMAP_1" for example in the runDR function was supposed to do so but then I can't find any UMAP_1 in the sce object.

If someone knows how to do this that would really help me !

Thanks

Quentin

**Comment by HelenaLC** [comment]
Reduced dims are stored in the reducedDims() slot - so you could rename the matrix in there before re-calculating. Alternatively, you can set the output names (default name=‘UMAP’) by passing this to runDR(). See scater’s ?runUMAP

**Comment by Behind42** [comment]
Hello,

Thank you, I don't know why I didn't think about that ! I renamed the UMAP as I want after calculating it, it's fine for me like that.

Quentin
