### ISSUE TITLE
Error in Isomap Using plotDR

### ISSUE THREAD

**Issue by LeleDR** [HelenaLC/CATALYST#206]
Hi!

I am pretty new here so let me know I need to put more information in my message. I have been using the CytofWorkFlow package for a few days now and this morning I was able to produce the UMAP with my data but since noon I got an error message while using the same data and the same script. It is also not working anymore with the example data and script while I was able to generate all the figures with it at the beginning of the week. :

> plotDR(sce, "UMAP", color_by = "CD4")

Error in Isomap(data, 2, min(10, data_points - 1)) :
invalid argument: data argument is required to be a N x D matrix (N samples, D features)
De plus : Warning message:
In plotDR(sce, "UMAP", color_by = "CD4") :
dimension of given data is too high (172791); used Isomap to reduce it to 2 dimensions

I got no error before this, all the figure were generated normally .
I am able to generate the heatmap using :

> plotMultiHeatmap(sce,
> hm1 = "type", hm2 = "pS6", k = "meta20",
> row_anno = FALSE, bars = TRUE, perc = TRUE)

I got no error message running : 

>sce <- runDR(sce, "UMAP", cells = 1e3, features = "type")

And I am also able to run : 
> plotCodes(sce, k = "meta20")

Can it be some kind of internal problem with a package? Should I wait?

Thank you a lot

Best

Lea

**Comment by HelenaLC** [comment]
Hm, the error doesn't look familiar to me. Is it possible you made updated some package update(s) in-between when it worked & when it didn't? My assumption is that another function called plotDR is being run (from another package), instead of CATALYST's. Could try explicitly running CATALYST::plotDR()?

**Comment by LeleDR** [comment]
Hello, Thank you very much it was indeed the problem!
