### ISSUE TITLE
plotFreqHeatmap not displaying all column annotations

### ISSUE THREAD

**Issue by Troylimyj** [HelenaLC/CATALYST#213]
Dear Helena, 

When attempting to create a frequency heatmap for a large number of samples (~60), I notice that not all my metadata is displayed as column annotation for each sample. Below is an example:

![1](https://user-images.githubusercontent.com/60615513/120562104-a8bc7f80-c3fd-11eb-970d-962dfde4a0c3.png)

For some reason I cannot work out, only "Timepoint" and "Controls" are displayed above each column. In my metadata I also included "Batch", which worked with all the other plots (tSNE/MDS), but not here. 

Thank you in advance. 

Best wishes
Troy

**Comment by HelenaLC** [comment]
Generally, heatmap annotations will include variables that are i) not numeric and ii) map uniquely to each column (sample). So, it'd be worth checking these conditions for a variable `"x"` that is not being displayed via:
```
# variable that's missing
i <- "x" 

# should return TRUE
cd <- colData(sce)
!is.numeric(cd[[i]])

# each row (sample) should have 
# exactly 1 non-zero column (variable)
table(cd$sample_id, cd[[i]])
```
Hope this helps a little. If you run this for your data, what do you get? Else, I am not sure what else might be causing the issue, but happy to have another look should the issue persist!
