### ISSUE TITLE
diffcyt analysis with own clustering

### ISSUE THREAD

**Issue by JPGranizo** [HelenaLC/CATALYST#214]
Dear @HelenaLC 

I was wondering how I can use my own clustering for diffcyt analysis? One of the parameters of my fcs files is a numeric integer value indicating the cluster number for each cell. Could you possibly advise how to integrate the cluster information into the sce object so it can be used for differential expression analysis instead of using the cluster function of the package?

Thank you very much in advance!

**Comment by HelenaLC** [comment]
Please see issue #187
