### ISSUE TITLE
plotDiffHeatmap subsetting

### ISSUE THREAD

**Issue by kmincham** [HelenaLC/CATALYST#218]
Firstly, thank you for the brilliant package.

My very minor issue is that I'm unable to subset my heatmap based on cell population.

I have generated a heatmap showing the differential signals of each marker on each annotated population as per section 7.3 of the CATALYST workflow (or section 11.2 figure 24 of the CyTOF workflow). Ideally, i would like to subset the markers into individual blocks for each cell population, to allow easier visualisation.

Would it be possible to please get some advise on how to perform this?

Thank you very much.

**Comment by HelenaLC** [comment]
Just to clearify: You want a single heatmap with vertical blocks, eg white space between groups of markers? Or separate heatmaps for each group of markers?

**Comment by kmincham** [comment]
A single heatmap with vertical blocks of cell populations separated by white spaces would be ideal. I have read through the ComplexHeatmap reference manual but I am unable to find a solution.

Apologies for the poor description.

Thank you.

**Comment by HelenaLC** [comment]
Okay. So usually vertical/horizontal splits would be defined in the `Heatmap()` call via `column/row_split`. It's always tricky to manipulate a `ComplexHeatmap` output once it's been created, but here's how:

```
library(CATALYST)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE) 

hm <- plotExprHeatmap(sce, 
    features = "type",
    by = "cluster_id")

# defined how rows/columns should be grouped together
# (I'm just doing some random groups here for demonstration...)
row_groups <- rep(seq(2), each = 10)
col_groups <- rep.int(seq(3), c(3, 3, 4))

hm@matrix_param$row_split <- row_groups
hm@matrix_param$column_split <- col_groups
hm
```
![image](https://user-images.githubusercontent.com/14542264/124893490-12224600-dfdb-11eb-917c-1728825f69c7.png)

**Comment by kmincham** [comment]
Thank you very much for your help with this - its greatly appreciated.
