### ISSUE TITLE
Size of compensation scatter plots in the shiny App

### ISSUE THREAD

**Issue by schevrie** [HelenaLC/CATALYST#22]
In the compensation tab, where people are expected to spend some time checking their compensation (Before vs after scatters), the size of the scatter plots are too big and prevent to see all the information at the same time. For instance when we draw the gate we don't see the median values are hidden. Changing the zoom on the page doesn't fix it because the plots are automatically adjusting their size to fill the whole space. Therefore it would be great if the size of those scatter plots would be adjusted to a smaller value.

**Comment by HelenaLC** [comment]
Hope it is fixed but I'm unsure as I've never had this problem. May depend on the browser and the screen?
