### ISSUE TITLE
pbMDS multiple dimensions

### ISSUE THREAD

**Issue by giopokcl** [HelenaLC/CATALYST#220]
Hi Helena,

I was wondering whether there is a quick way to visualise different components when running pbMDS(). By default it should visualise dim 1 and dim 2, but is it possible to show 3 and 4 (or different combinations)?

Many thanks for your help!

**Comment by HelenaLC** [comment]
This is currently not supported by `pbMDS()`. However, you can easily aggregate the data, compute MDS & visualise arbitrary dimensions as follows:

```
library(CATALYST)
library(scater)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

# specify variables to aggregate by
ids <- DataFrame(
    sample_id = sce$sample_id,
    cluster_id = cluster_ids(sce, "meta20"))

# compute medians by cluster-sample
pbs <- aggregateAcrossCells(sce, ids,
    use.assay.type = "exprs", 
    statistics = "median")

# compute 10 MDS dimensions
pbs <- runMDS(pbs, 
    ncomponents = 10,
    exprs_values = assayNames(pbs))

# visualize all pairs for dimensions 1-3
plotMDS(pbs, 
    ncomponents = 3,
    colour_by = "condition")
```
![image](https://user-images.githubusercontent.com/14542264/125417380-3439a7cc-3801-4f29-bf32-1f83c30a6946.png)
```
# subset dimensions 1 & 3 only
tmp <- pbs
mds <- reducedDim(tmp, "MDS")
reducedDim(tmp, "MDS") <- mds[, c(1, 3)]
plotMDS(tmp, colour_by = "condition")
```
![image](https://user-images.githubusercontent.com/14542264/125417420-c8b6cbcc-0d74-4529-a939-49de80575c58.png)

**Comment by HelenaLC** [comment]
FYI, I added support to plot the dimensions of your choice, e.g., `pbMDS(..., dims = c(1, 2))`! 

Unlike the `scater` version, where `ncomponents = 3` will plot all pairs (1,2; 1,3; 2,3), `c(1, 3)`, for example, will only plot dims. 1 against 3. Hope this will at least give some additional flexibility! 

Update is in v1.17.3 on the `master` branch, and should be available through Bioc devel within the next couple days.

**Comment by giopokcl** [comment]
Thank Helena… that’s great!! It saves running it in multiple steps from adapting the previous code you sent.

Many thanks for the useful addition!!!

Best wishes

Gio
