### ISSUE TITLE
Error in FUN(X[[i]], ...) : object 'condition' not found   while using pbMDS

### ISSUE THREAD

**Issue by franszii** [HelenaLC/CATALYST#223]
Hallo Helena, 

I'm still new to working with R and I am using CATALYST for the first time to analyze mass cytometry data. I was able to create the singlecellexperiment object.  Count and expression plots worked well using the `sce` but I am failling at plotting MDS. 

**running any of these lines:**
`pbMDS(sce_trans, feature= 'state', label_by = "sample_id")`
`pbMDS(sce_trans, color_by = "condition", label_by = "sample_id")`
**generates:** 
Error in FUN(X[[i]], ...) : object 'condition' not found

Tried a couple of things but I could not figure it out. I guess the solution might be quite simple. Thanks for any tips how to solve it.

> **conditions and sample ids:**
> `md$condition <- factor(md$condition, levels = c("SLE", "pSS", "HD"))`
>` md$sample_id <- factor(md$sample_id, levels = md$sample_id[order(md$condition)])`
> 
> **generated SCE like that:**
> `sce_trans <- prepData(fs, panel, md, features = panel$name[!is.na(panel$antigen)], transform = TRUE, panel_cols = list(channel = "name", antigen = "fcs_colname", class ="marker_class_I"), md_cols = list(file = "file_name", id = "sample_id", factors = "condition"))`
> 
> 
> **this is my SCE:**
> 
> > sce_trans
> class: SingleCellExperiment 
> dim: 33 157350 
> metadata(1): experiment_info
> assays(2): counts exprs
> rownames(33): 209Bi_CD16 142Ce_CD19 ... 172Yb_IgM 174Yb_HLA-DR
> rowData names(3): channel_name marker_name marker_class
> colnames: NULL
> colData names(2): sample_id condition
> reducedDimNames(0):
> altExpNames(0):
> 
> 
> **session info:**
> > sessionInfo()
> R version 4.0.2 (2020-06-22)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19041)
> 
> Matrix products: default
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] scater_1.18.6               ggplot2_3.3.5               CATALYST_1.14.1             writexl_1.4.0               kableExtra_1.3.4           
>  [6] readxl_1.3.1                SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0 Biobase_2.50.0              GenomicRanges_1.42.0       
> [11] GenomeInfoDb_1.26.7         IRanges_2.24.1              S4Vectors_0.28.1            BiocGenerics_0.36.1         MatrixGenerics_1.2.1       
> [16] matrixStats_0.59.0          flowCore_2.2.0             
> 
> loaded via a namespace (and not attached):
>   [1] circlize_0.4.13             drc_3.0-1                   systemfonts_1.0.2           plyr_1.8.6                  igraph_1.2.6               
>   [6] ConsensusClusterPlus_1.54.0 splines_4.0.2               BiocParallel_1.24.1         usethis_2.0.1               TH.data_1.0-10             
>  [11] digest_0.6.27               htmltools_0.5.1.1           viridis_0.6.1               fansi_0.5.0                 magrittr_2.0.1             
>  [16] CytoML_2.2.2                cluster_2.1.2               aws.signature_0.6.0         openxlsx_4.2.4              ComplexHeatmap_2.6.2       
>  [21] RcppParallel_5.1.4          sandwich_3.0-1              svglite_2.0.0               flowWorkspace_4.2.0         cytolib_2.2.1              
>  [26] jpeg_0.1-8.1                colorspace_2.0-2            rvest_1.0.0                 ggrepel_0.9.1               haven_2.4.1                
>  [31] xfun_0.22                   dplyr_1.0.7                 crayon_1.4.1                RCurl_1.98-1.3              jsonlite_1.7.2             
>  [36] hexbin_1.28.2               graph_1.68.0                survival_3.2-11             zoo_1.8-9                   glue_1.4.2                 
>  [41] gtable_0.3.0                nnls_1.4                    zlibbioc_1.36.0             XVector_0.30.0              webshot_0.5.2              
>  [46] GetoptLong_1.0.5            DelayedArray_0.16.3         ggcyto_1.18.0               BiocSingular_1.6.0          car_3.0-11                 
>  [51] Rgraphviz_2.34.0            shape_1.4.6                 abind_1.4-5                 scales_1.1.1                mvtnorm_1.1-2              
>  [56] DBI_1.1.1                   Rcpp_1.0.6                  plotrix_3.8-1               viridisLite_0.4.0           clue_0.3-59                
>  [61] rsvd_1.0.5                  foreign_0.8-81              FlowSOM_1.22.0              tsne_0.1-3                  httr_1.4.2                 
>  [66] RColorBrewer_1.1-2          ellipsis_0.3.2              farver_2.1.0                pkgconfig_2.0.3             XML_3.99-0.6               
>  [71] scuttle_1.0.4               sass_0.4.0                  utf8_1.2.1                  labeling_0.4.2              tidyselect_1.1.1           
>  [76] rlang_0.4.10                reshape2_1.4.4              munsell_0.5.0               cellranger_1.1.0            tools_4.0.2                
>  [81] cli_3.0.0                   generics_0.1.0              ggridges_0.5.3              aws.s3_0.3.21               evaluate_0.14              
>  [86] stringr_1.4.0               yaml_2.2.1                  fs_1.5.0                    knitr_1.33                  zip_2.2.0                  
>  [91] purrr_0.3.4                 RBGL_1.66.0                 sparseMatrixStats_1.2.1     xml2_1.3.2                  compiler_4.0.2             
>  [96] rstudioapi_0.13             beeswarm_0.4.0              curl_4.3.2                  png_0.1-7                   tibble_3.1.2               
> [101] bslib_0.2.5.1               stringi_1.6.2               highr_0.9                   forcats_0.5.1               lattice_0.20-44            
> [106] Matrix_1.3-4                vctrs_0.3.8                 pillar_1.6.1                lifecycle_1.0.0             jquerylib_0.1.4            
> [111] GlobalOptions_0.1.2         BiocNeighbors_1.8.2         irlba_2.3.3                 data.table_1.14.0           cowplot_1.1.1              
> [116] bitops_1.0-7                R6_2.5.0                    latticeExtra_0.6-29         gridExtra_2.3               RProtoBufLib_2.2.0         
> [121] rio_0.5.27                  vipor_0.4.5                 codetools_0.2-18            MASS_7.3-54                 gtools_3.9.2               
> [126] assertthat_0.2.1            rprojroot_2.0.2             rjson_0.2.20                withr_2.4.2                 multcomp_1.4-17            
> [131] GenomeInfoDbData_1.2.4      hms_1.1.0                   ncdfFlow_2.36.0             beachmat_2.6.4              grid_4.0.2                 
> [136] rmarkdown_2.9               DelayedMatrixStats_1.12.3   carData_3.0-4               Cairo_1.5-12.2              Rtsne_0.15                 
> [141] base64enc_0.1-3             ggbeeswarm_0.6.0

**Comment by HelenaLC** [comment]
Quick sanity check, could you run `CATALYST::pbMDS()` to assure R is making the right function call and this is not due to a namespace-clash?

**Comment by franszii** [comment]
Thanks for the response. I tried:

` CATALYST::pbMDS(sce_trans, color_by = "condition", label_by = "sample_id")`

but I still get the error:

Error in FUN(X[[i]], ...) : object 'condition' not found

Thanks a lot!

**Comment by HelenaLC** [comment]
Hm. Curious... I don't know exactly what the issue is :/ Could you print `type_markers()` & `state_markers()`?

**Comment by franszii** [comment]
> `type_markers(sce_trans)`
**gives:**
 [1] "142Ce_CD19"   "160Dy_IgG"    .... 

> state_markers(sce_trans)

**gives:**

[1] "209Bi_CD16"      "162Dy_CD8"       ....

so that looks fine I think.

It is just the pbMDS function I can somehow not make run :)
All the other functions of you package also downstream e.g the heatmaps work well. Thanks for this nice workflow!

**Comment by markrobinsonuzh** [comment]
Maybe one thing: can you run `traceback()` after you get the error?

**Comment by franszii** [comment]
it gives me this:

> traceback()
11: FUN(X[[i]], ...)
10: lapply(aesthetics[new_aesthetics], eval_tidy, data = data)
9: scales_add_defaults(plot$scales, data, aesthetics, plot$plot_env)
8: f(..., self = self)
7: l$compute_aesthetics(d, plot)
6: f(l = layers[[i]], d = data[[i]])
5: by_layer(function(l, d) l$compute_aesthetics(d, plot))
4: ggplot_build.ggplot(x)
3: ggplot_build(x)
2: print.ggplot(x)
1: (function (x, ...) 
   UseMethod("print"))(x)

**Comment by HelenaLC** [comment]
Another thought, could you store the `ggplot` object instead of plotting it directly, i.e. `p <- pbMDS(...)`. Then, post the the following: `class(p)` and `head(p$data)`.

**Comment by franszii** [comment]
> plo <- CATALYST::pbMDS(sce_trans, color_by = "condition", label_by = "sample_id")
> class(plo)
[1] "gg"     "ggplot"
> head (plo$data)
                 x           y sample_id colData(x)[m, i] n_cells
S02   -4.0410414 -0.69587047     S02              SLE     631
S03   -0.1845459 -1.57431650     S03              SLE    1172
S04   -1.4253832  0.48296867     S04              SLE    1426
S14    2.0690766 -0.93317326     S14              SLE    1486
