### ISSUE TITLE
ncol argument in plotDR does not work unless coloring by a marker

### ISSUE THREAD

**Issue by gcohenJH** [HelenaLC/CATALYST#225]
Hi Helena and the rest of the CATALYST team, thanks for the very useful package! I think I found a simple bug in plotDR.
On line 128, there is an if statement that does a variety of things, but it sets the value of facet.
```
if (all(color_by %in% rownames(x))) {
.
facet <- facet_wrap("variable", ncol = ncol)
} else if (is.numeric(df[[color_by]])) {
.
facet <- thm <- guide <- NULL
} else {
facet <- NULL
.
}
```
If color_by is set to a marker, facet is set with ncol, but otherwise its set to null.

Later on in line 190, since facet is null, the facets are added to the ggplot object, but it is without ncol set.
```
if (is.null(facet)) {
        p + facet_wrap(facet_by)
```
This results in ncol often not being passed to ggplot.

**Comment by HelenaLC** [comment]
Thanks for catching this! I Added the missing `ncol` in `facet_wrap` when facetting by a variable other than markers; v1.17.3 (available on branch `master` & Bioc devel in the next couple days).
