### ISSUE TITLE
Generate a mixed UMAP, instead of plotting samples one over the other 

### ISSUE THREAD

**Issue by paulyashna** [HelenaLC/CATALYST#226]
Dear Authors,

I had a question about the function 'plotDR()'. I have approx 50 samples, and after plotting the UMAP grouped by 'sample_id', only the samples that are taken up in the end (or lie at the end of the table) are visible on the UMAP. So instead of 50 colors (corresponding to 50 samples), only 4-5 colors are visible. Other samples are hidden below those 4-5 samples. Is there a way that the plotting functions displays the samples as mixed instead of one on top of the other?

Only for plotting is it possible to plot only e.g. 500 cells from each sample?

Any suggestions on this are appreciated.
Thanks and Regards,
Yashna

**Comment by HelenaLC** [comment]
- To plot a shuffled UMAP, you can simply randomise the order of cells in the SCE, e.g.:
```
plotDR(sce[, sample(ncol(sce))], dr = "UMAP", ...)
```
- To plot a random subset of `n` cells per sample, you can use:
```
# split cell indices by sample
cs <- split(seq(ncol(sce)), sce$sample_id)
# downsample to at most 500 per sample
cs <- lapply(cs, \(.) sample(., min(500, length(.))))
plotDR(sce[, unlist(cs)], dr = "UMAP", ...)
```
- Finally, you could combine the above into a simple wrapper such as:
```
# NULL = randomise, but don't downsample
# numeric = downsample to at most 'n'
.plotUMAP <- function(sce, n = NULL, ...) {
  cs <- seq(ncol(sce))
  if (is.null(n)) {
    cs <- sample(n)
  } else {
    stopifnot(is.numeric(n), length(n) == 1, round(n) == n, n > 0)
    cs <- split(cs, sce$sample_id)
    cs <- lapply(cs, \(.) sample(., min(n, length(.))))
    cs <- unlist(cs)
  }
  sce <- sce[, cs]
  plotDR(sce, dr = "UMAP", ...)
}
```
