### ISSUE TITLE
plotSpillmat

### ISSUE THREAD

**Issue by AvitalPo** [HelenaLC/CATALYST#227]
Hi,

I have a case where only 10 channels were used to calculate the spillover matrix. When I'm trying to plot the matrix using plotSpillmat I'm getting strange results, only 4x4 matrix is shown.
I tried to dive into the code and I see that you have two things I'm not sure I understand - 
1. Make symmetric - if I only have 10 channels that are the "spillers" and 39 channels that can be receivers I want to plot 10x39 no? Do you think it looks better to plot 39x39?
2.     At the part of the code below you are subsetting the matrix according to the indexes of the bc_chs (the channels with the beads that are the spillers), however, you are getting the indexes from the bc_chs vector and I think you should take them from the sm matrix. If I'm wrong, can you explain to me why are you doing this?
bc_chs <- chs[rowData(x)$is_bc]
bc_idx <- which(bc_chs %in% colnames(sm))
bc_rng <- seq(min(bc_idx), max(bc_idx))
sm <- .make_symetric(sm)[bc_rng, bc_rng]

Thanks and thank you for your great packages,
Avital

**Comment by HelenaLC** [comment]
Relates to #204 (in progress)
