### ISSUE TITLE
issue with prepData function

### ISSUE THREAD

**Issue by jenkinmt** [HelenaLC/CATALYST#228]
Hey,
I'm currently trying to get my data prepped for the catalyst workflow/pipeline. I have my md and panel info saved into .csv format with the proper headings for column names in each file and have my .fcs files loaded as a flowSet. 
My issue seems to be with the "features" argument of prep data. Here in my code below, I have set the features to be those channels that I do not want analyzed further:
prepData(x = "d_flowSet",panel = "data.frame2",md = "data.frame1",
        features = "Pd", "Event_length", "Ba", "Bead", "open", "Center", "Offset", "Width", "Residual",
        transform = TRUE,
        cofactor = 5,
        panel_cols = list(channel = "fcs_colname", antigen = "antigen", class =
                      "marker_class"),
        md_cols = list(file = "file_name", id = "sample_id", factors = c("condition",
                                                                   "patient_id")),
        by_time = TRUE,
        FACS = FALSE
        )
However, running this code returns the following error:
Error in prepData(x = "d_flowSet", panel = "data.frame2", md = "data.frame1",  : 
  unused arguments ("Event_length", "Ba", "Bead", "open", "Center", "Offset", "Width", "Residual")
It appears as if the channels I wish to exclude are being counted as "arguments" in the function? I was wondering what caused this/how to work around it? 
Ultimately, my goal is to be able to exclude those channels from my FCS files which I do not plan to analyze

Thank you!
Matt Jenkins

**Comment by HelenaLC** [comment]
General R syntax: Each argument in a function is separated by comma. If you specify `prepData(..., features = "a", "b", "c", ...)`, only `"a"` is taken as `features`, thus the above error (e.g., unused arguments `"b", "c"`). What you want is to pass the channels as a vector, i.e. `prepData(..., features = c("a", "b", "c", ...))`.

**Comment by jenkinmt** [comment]
thank you! ill try this now and see if I can get it to resolve

**Comment by jenkinmt** [comment]
Thanks for the help. That error message was resolved. Now, when I run prepData as below, 
files <- list.files(
  path = "~/Desktop/2021 Tet2 KO cytof analysis/CisnegWBMUnstim", pattern = ".fcs", full.names = TRUE)
      d_flowSet <- read.flowSet(files, transformation = FALSE, truncate_max_range = FALSE)
x <- "d_flowSet"
prepData(x, panel = data.frame2, md = data.frame1,
         features = c("89YDi", "141PrDi", "142CeDi", "143NdDi", "144NdDi", "145NdDi", "146NdDi", "148NdDi", "149SmDi", "150NdDi", 
                    "151EuDi", "152SmDi", "154SmDi", "155GdDi", "156GdDi", "159TbDi", "160GdDi", "162DyDi", "163DyDi", "164DyDi", 
                    "165HoDi", "166ErDi", "168ErDi", "169TmDi", "170YbDi", "171YbDi", "172YbDi", "173YbDi", "175LuDi", "176HfDi", "209BiDi"),
         transform = FALSE,
         panel_cols = list(channel = "fcs_colname", antigen = "antigen", class =
                                   "marker_class"),
         md_cols = list(file = "file_name", id = "sample_id", factors = c("condition",
                                                                                "patient_id")),
         by_time = TRUE,
         FACS = FALSE)
It returns the below error message: 
Error in .read_fs(x) : 
  all(vapply(fcs, isFCSfile, logical(1))) is not TRUE. 
It appears to be an error with the FCS files I read into d_flowSet. However when I call d_flowSet to see the files contained there, it shows me all 6 of the .fcs files that I read in, and they appear to have read in properly based on that. 

Thank you again for your help!!

**Comment by HelenaLC** [comment]
`prepData()` stars out with calling a helper function, `.read_fs()`, that will either i) read in a vector of FCS files as a `flowSet`, ii) read in FCS files in a directory as a `flowSet`, iii) convert a list of `flowFrame`s to a `flowSet`, or iv) just return a `flowSet` if the input is already a `flowSet`. 
So, in your case, it should do iv). But the error you get would appear in case of i). To figure out what's happening, I suggest you run the code [here](https://github.com/HelenaLC/CATALYST/blob/master/R/utils-preprocessing.R) line-by-line.

**Comment by HelenaLC** [comment]
Actually... you are passing `x <- "d_flowSet"`, so your input is NOT the `flowSet`, but a character, which explains the error. You should use `x <- d_flowSet` instead, or just call `prepData(d_flowSet, ...)`. Sorry, I just noticed this. 

**General comment**: Please use code chunks for code. On GitHub, code is nicely displayed & much easier to read if you enclose it with 3 back-ticks (```) on the top and bottom, and in-line code with two around it.
