### ISSUE TITLE
Error in daFrame(fs, panel, md, cols_to_use = panel$fcs_colname) :    could not find function "daFrame"

### ISSUE THREAD

**Issue by jinaanna** [HelenaLC/CATALYST#234]
Hi,

I have read the article in the F1000 research named as "CyTOF workflow: differential discovery in highthroughput high-dimensional cytometry datasets [version 3; peer review: 2 approved]".  I have tried to run the code in this article. But when I run to the code
 "# specify levels for conditions & sample IDs to assure desired ordering
md$condition <- factor(md$condition, levels = c("Ref", "BCRXL"))
md$sample_id <- factor(md$sample_id,
levels = md$sample_id[order(md$condition)])
# construct daFrame
daf <- daFrame(fs, panel, md, cols_to_use = panel$fcs_colname)",
 it just made error like this "Error in daFrame(fs, panel, md, cols_to_use = panel$fcs_colname) : 
  could not find function "daFrame"". 
I have install the package "CATALYST" and it can be libraried in R. But it seems haven't been installed because I can't find it the "help".

I really need your help and thank you very much!

Jina

**Comment by HelenaLC** [comment]
Please refer to version 4 of the article if you’re using the current Bioc release version of CATALYST. The daFrame has been deprecated since a couple of years.
