### ISSUE TITLE
Error with cluster function if transform = FALSE in prepData

### ISSUE THREAD

**Issue by thinkCara** [HelenaLC/CATALYST#237]
CATALYST is working well with my dataset but I don't want it to transform any of the channels when importing the data with `prepData`. The channels that I want to cluster on have already been transformed. When I set `transform = FALSE` then I get an error when I try to cluster. I think the cluster function is looking for the `exprs` data which doesn't exist without transforming the data. When `transform = FALSE` only `counts` data is in the sce. 
Is there a way around this? I have included a shortened version of my code below.

```
CEWfs <- read.flowSet(fcsFiles, transformation = FALSE)
# code skipped for metadata setup
sce <- prepData(
  CEWfs, 
  md = expInfo, 
  md_cols = list(factors = c("short_name", "batch", "barcodeID", "group", "tissue", "timepoint", "treatment")),
  transform = FALSE
  )
# Change the status/level of `marker_class`for the clustering markers to `type`
rowData(sce)[names(sce) %in% cluster_channels, "marker_class"] <- "type"
# perform flowsom clustering
sce <- cluster(sce, features = "type", xdim = 10, ydim = 10, maxK = 15, verbose = TRUE, seed = 1564738)
```
I have successfully run this many times without including `transform = FALSE` but as soon as I include that, I get the following error when I try to cluster:

> Error in assay(x, "exprs") : 'assay(<SingleCellExperiment>, i="character", ...)' invalid subscript 'i' 'exprs' not in names(assays(<SingleCellExperiment>))

**Comment by SamGG** [comment]
From https://github.com/HelenaLC/CATALYST/blob/3204b32336836056b2c1f604db63dad5abd323a3/R/utils-preprocessing.R#L60-L62, `assay(sce, "exprs", FALSE) <- assay(sce, "counts")` should do the trick while waiting for a better response from Helena. Check the use of the logical argument `withDimnames` if more tuning is needed.
HTH

**Comment by HelenaLC** [comment]
Internally, cluster() tries to access an assay named “exprs”. If transform = F, this doesnt exist, thus the error. If your counts already correspond to transformed data, simply set assayNames(sce) <- “exprs”. 
Apologies for the confusion and the bad implementation at the time. Ideally, there should be an argument “assay” to specify which assay slot to use, which is currently not exposed to the user. Will close the issue but add this as a todo for myself.

**Comment by thinkCara** [comment]
Thanks Helena! That worked!
Here it is in coded form if anyone else needs it.

```
# Cluster is looking for exprs and not count data. If transform = FALSE in prepData, run the following line before clustering so that cluster will run. 
assayNames(sce) <- "exprs"
## Run FlowSOM-clustering
sce <- cluster(sce, features = "type", xdim = 10, ydim = 10, maxK = 15, verbose = TRUE, seed = 1564738)
```
