### ISSUE TITLE
Integrating with Spectre Normalize for Batch Correction

### ISSUE THREAD

**Issue by ramziabb** [HelenaLC/CATALYST#239]
Has anyone integrated Spectre Normalize for batch correction (https://wiki.centenary.org.au/display/SPECTRE/Discovery+workflow+with+batch+alignment+using+CytoNorm) then the CATALYST workflow?  I am working to doing so for both cyTOF and Flow data.  Have gotten it working for the most part, now just sorting out if my transformation levels are correct and them focusing on analyzing results.

But I just wanted to reach out and see if others are using these workflows together.

Right now I am doing Spectre Normalize batch correction then writing out FCS files with:

write.files(cell.dat, file.prefix = "", divide.by = sample.col, write.csv = FALSE, write.fcs = TRUE)

I am then reading in the fcs files as my inputs into CATALYST.  It works and so I don't really feel strongly about converting directly in the code.  

Anyone has used these two workflows together?   Has it worked for you?

**Comment by tomashhurst** [comment]
Hey @ramziabb,

If you like, you can just convert the data.table at the end of your Spectre workflow into a SingleCellExperiment object and go straight into your CATALYST workflow. We were writing up short tutorial for how to do it, but we didn't end up finishing it, but we can send through a quick set of instructions?

**Comment by nilseling** [comment]
Hey @tomashhurst 
would you consider exporting a data.table <--> SingleCellExperiment conversion function in `Spectre`? Might be quite nice for interchangeable use.

**Comment by tomashhurst** [comment]
Hey Nils!! Yes absolutely, we actually have that (and for Seurat etc) in draft format we just haven't had the chance to get it online.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nilseling** [comment]
Awesome! That's really nice!

**Comment by ramziabb** [comment]
Hi guys!  Were you able to put together a short tutorial or code fragment to do this?  Right now I write out the FCS from Spectre and then back into CATALYST.

Thanks!

**Comment by denvercal1234GitHub** [comment]
Hi @tomashhurst - Could you share the tutorial to convert data.table into SingleCellExperiment object and Seurat object? 

Hi, @ramziabb -- I am also trying to analyze CyTOF and flow combing Spectre and Catalyst with batch correction. Would you be happy to share the code for batch correction part? 

My email is quang.n.nguyen@alumni.duke.edu 

Thank you!!!

**Comment by HelenaLC** [comment]
Closing as there doesn‘t seem to be an issue per se, but please feel free to continue open discussion, sharing ideas, linking relevant resources 🙏
