### ISSUE TITLE
UMAP comparison

### ISSUE THREAD

**Issue by chuancn** [HelenaLC/CATALYST#241]
I did FlowSOM clustering and UMAP using CATALYST, and tried to reproduce the dimension reduction by [umap](https://cran.r-project.org/web/packages/umap/vignettes/umap.html) package with default settings:

```
# FlowSOM, ConsensusClusterPlus, randomized seed
i <- sample(1:1000000, 1)
i
set.seed(i)
sce <- cluster(sce, features = "type", xdim = 10, ydim = 10, maxK = 20, seed = i)

# UMAP CATALYST, randomized seed
i <- sample(1:1000000, 1)
i
set.seed(i)
sce <- runDR(sce, "UMAP", cells = NULL, features = "type")

plotDR(sce, "UMAP", color_by = "meta20")


# write data matrix
dt<-as.data.frame(cbind(t(sce@assays@data@listData$exprs), Center=sce@int_colData@listData$Center,
                        Event_length=sce@int_colData@listData$Event_length, Offset=sce@int_colData@listData$Offset,
                        Residual=sce@int_colData@listData$Residual, Time=sce@int_colData@listData$Time,
                        cluster_id = sce$cluster_id))

cldt <- sce@metadata$cluster_codes[dt[,"cluster_id"],]
cldt20 <- cldt[,"meta20"]

um <- as.data.frame(reducedDim(sce))
colnames(um) <- c("UMAP1", "UMAP2")

dt <- cbind(dt, cldt20, um, sample = sce$sample_id, group = sce$condition)
rownames(dt) <- c(1:nrow(dt))

# generate data matrix for DR and clustering
mart <- sce@rowRanges@elementMetadata@listData$marker_name[sce@rowRanges@elementMetadata@listData$marker_class=="type"]
dtcl <- dt[,mart]
table(duplicated(dtcl))

# UMAP package
set.seed(i)
umap2 <- umap(dtcl)

um2 <- as.data.frame(umap2$layout)
colnames(um2) <- c("u1", "u2")
dt <- cbind(dt, um2)

ggplot(dt, aes(u1, u2, colour = cldt20)) + geom_point(size = 0.4, alpha = 0.8) + theme_minimal() + 
  theme(legend.key.height = unit(0.8, "lines")) + coord_equal() + guides(colour = guide_legend(override.aes = list(size=3))) + 
  scale_colour_manual(values = CATALYST:::.cluster_cols) + theme(panel.grid.minor = element_blank(), strip.text = element_text(face = "bold"), 
                                           axis.text = element_text(color = "black"))
```

Default parameters from umap package:

```
umap.defaults
## umap configuration parameters
##            n_neighbors: 15
##           n_components: 2
##                 metric: euclidean
##               n_epochs: 200
##                  input: data
##                   init: spectral
##               min_dist: 0.1
##       set_op_mix_ratio: 1
##     local_connectivity: 1
##              bandwidth: 1
##                  alpha: 1
##                  gamma: 1
##   negative_sample_rate: 5
##                      a: NA
##                      b: NA
##                 spread: 1
##           random_state: NA
##        transform_state: NA
##                    knn: NA
##            knn_repeats: 1
##                verbose: FALSE
##        umap_learn_args: NA
```

I got very different UMAP results (cluster annotation is the same):

CATALYST:
![image](https://user-images.githubusercontent.com/87318250/142241123-8d1adc6b-a02a-4e48-b38a-1bf71a967609.png)

umap package:
![image](https://user-images.githubusercontent.com/87318250/142241307-0e8eb70d-4a55-4c0c-8ec6-aacbb0b0de96.png)

The clustering fits much better with UMAP from CATALYST. I tried to look for the parameters in your code but could not find them. Can you let me know what magic you did in CATALYST?

**Comment by SamGG** [comment]
If I am not wrong CATALYST is calling the UMAP function from the scater package which is calling the UMAP algorithm implemented by JL Melville in the uwot package by JL Melville.
https://github.com/HelenaLC/CATALYST/blob/54bd90dedcef529b59cf13aa72a84eb63e669af9/R/runDR.R#L42
https://github.com/Alanocallaghan/scater/blob/master/R/runUMAP.R
Helena should give a more answer.

**Comment by HelenaLC** [comment]
Yes, that is correct. Thanks @SamGG

**Comment by HelenaLC** [comment]
FYI - the code above hurts me - especially this line `sce@rowRanges@elementMetadata@listData$marker_name[sce@rowRanges@elementMetadata@listData$marker_class=="type"]`. I'd highly recommend getting familiar with the `SummarizedExperiment` and `SingleCellExperiment` accessors. One this that comes with a class are replacement- and accession-methods that are meant to made your life a lot easier (and less error prone, e.g., when the structure changes underneath the above code will fail). To give an example, if I'm not mistaken, that line could be written as
```
rd <- rowData(sce)
rd$marker_name[rd$marker_class == "type"]
```
In a second step, `CATALYST` provides some could-be-useful accessors, e.g.:
```
type_markers(sce)
```
...BUT definitely go with familiarising yourself with the S(C)E ones first! :)

**Comment by chuancn** [comment]
Thanks a lot to you both @SamGG @HelenaLC . I will run a uwot tomorrow to compare.

@HelenaLC I appreciate your comment that the codes can be much more concise - just that I am a biologist with virtually no coding experience and cannot devote all my time to optimizing the codes... so I had to go for a fast, obvious but not straightforward answer. Could you maybe point to a page that summarizes all the `SummarizedExperiment` and `SingleCellExperiment` accessors? That will definitely make my life much easier.

**Comment by HelenaLC** [comment]
Of course, it was not at all intended as a criticism - my apologies if it came of as such - but rather a recommendation for the future to make things easier. Here you go: https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html and https://bioconductor.org/packages/release/bioc/vignettes/SingleCellExperiment/inst/doc/intro.html Generally, you can just google “Bioconductor PACKAGENAME” and you will find a vignette that’s always the best starting point for any package you use. 

Closing now assuming this has been resolved. Let me know if you have further issues, questions, need advice, anything, and we’ll be happy to help :)

**Comment by SamGG** [comment]
Dear @chuancn I did the same errors as you (in another package). I also tried to gather the information where it is in the object. The point is that when the developper decides to change a little bit the inner structure of the object, my code fails. That why developpers provide an interface to access whitout having to rely on the inner structure. But we have to learn the accessors and ask when one is missing. Welcome in the R world.
Thanks @HelenaLC.
Have a nice day.

**Comment by chuancn** [comment]
Thanks again to you both @HelenaLC @SamGG for your wonderful advice. I did some debugging today and found where the problem came from.

Apparently it's because `sce$cluster_id` etc. are `Factor`s, and in some cases not all the 100 clusters in FlowSOM were assigned. Don't know why this is the case, but to give an example, `sce$cluster_id` only has 96 levels (so 96 clusters) in one of the runs. By reading `sce$cluster_id`, it doesn't give the actual cluster number (1-100, 4 numbers missing in between), but the level number in the `Factor` (1-96), which leads to wrongly assigned `meta20` cluster numbers. One solution is to read `as.numeric(levels(sce$cluster_id))[sce$cluster_id]`; this gave me comparable UMAP results as generated by CATALYST. I don't find a better solution yet, but maybe you could give some advice.

While the `Factor` is quite useful, it generates unique problems with numbers for people like me who are not familiar with this type. On the other hand, when I don't use the data as `Factor`s (in this case, it's the `meta20`), plots like this will fail:

```
ggplot(dt, aes(UMAP1, UMAP2, colour = meta20)) + scale_colour_manual(values = CATALYST:::.cluster_cols)

Error: Continuous value supplied to discrete scale
```

Would be very nice to have your comments on how you deal with such issues in your practice.

Have a nice weekend.

**Comment by SamGG** [comment]
From my experience, when a cluster of a SOM is empty (I mean no element assigned to it), the grid is bigger than the complexity of the data.
My two cents.
