### ISSUE TITLE
Analysing imc data

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#243]
Hello Helena and team.

I have experience analysing suspension mass cytometry data using CATALYST. Now I'm trying to use the same pipeline to analyse imaging mass cytometry data which, after segmentation, I have transformed and input as .fcs files using the flowCore function read.flowSet(). My problem is that the resolution of my heatmaps is very poor and I find it very difficult to identify cell populations in my clusters. I have compensated the data using imcRtools (thanks again Nils) and CATALYST. I was wondering if there is any good practice guidance in terms of settings of the different functions (prepData, cluster, runDR) or anything else when using imc data? 

Regards
Juan

**Comment by nilseling** [comment]
Hi @algebio 
This doesn't see to be related to the functionality of CATALYST. Do you maybe want to move this issue to https://github.com/BodenmillerGroup/IMCDataAnalysis and we can discuss there. What do you think @HelenaLC ?
Cheers,
Nils

**Comment by SamGG** [comment]
Hi,
A figure is better than a thousand words. Do you have a tSNE/UMAP and a heatmap to show? How many cells is there in the end? What is your feeling when visualizing the FCS file with e.g. FlowJo?
Best,
Sam-not-of-the-team :-)

**Comment by algebio** [comment]
Hi Nils and Sam

I'll close this issue here and I'll post it in IMCDataAnalysis as suggested. I will add some figures as well.

Regards
Juan

**Comment by nilseling** [comment]
The issue was reopened [here](https://github.com/BodenmillerGroup/IMCDataAnalysis/issues/5)
