### ISSUE TITLE
Heatmap "Condition" Colors

### ISSUE THREAD

**Issue by ramziabb** [HelenaLC/CATALYST#244]
Any way to adjust the colors of "Condition" in the heatmap?"  These are too similar on my plots.  I couldn't tell from the arguments in plotDiffHeatmap if this was possible.

https://rdrr.io/bioc/CATALYST/man/plotDiffHeatmap.html

![image](https://user-images.githubusercontent.com/93796927/144240388-edea88b8-7b36-4a3c-96bd-cd7048d03256.png)

Thank you,
Ramzi

**Comment by HelenaLC** [comment]
Hey there. I am reaaally sorry, but this is really painful to do, as i) there is currently no argument in `plotDiffHeatmap` to pass a custom color palette for the columns annoations, and ii) manipulating `ComplexHeatmap::Heatmap`s in retrospect is all but straight forward. Here are 2 options:

1. If you don't care so much about including the patient IDs (as it looks there's no pairing here, and all are unique), you could drop this and get 2 more distinct colors for the conditions, e.g. `plotDiffHeatmap(..., col_anno = "condition")`.

2. This is ugly and I don't understand why modifying 2 values is necessary to be honest, but this works:
```
suppressPackageStartupMessages({
    library(CATALYST)
    library(ComplexHeatmap)
    library(diffcyt)
})

# construct SCE & run clustering
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

## differential analysis
design <- createDesignMatrix(PBMC_md, cols_design=3:4)
contrast <- createContrast(c(0, 1, 0, 0, 0))
ds <- diffcyt(sce, design = design, contrast = contrast, 
    analysis_type = "DS", method_DS = "diffcyt-DS-limma",
    clustering_to_use = "meta20", verbose = FALSE)
    
# display test results
hm <- plotDiffHeatmap(sce, rowData(ds$res))
cm <- ColorMapping("condition", c(Ref = "black", BCRXL = "grey"))
hm@top_annotation@anno_list$condition@color_mapping <- cm
hm@top_annotation@anno_list$condition@fun@var_env$color_mapping <- cm
hm
```
![image](https://user-images.githubusercontent.com/14542264/144248280-381adf72-0f5f-4de7-85b1-0c6d0000987d.png)

**Comment by ramziabb** [comment]
This works.  Thank you.

**Comment by ramziabb** [comment]
I made a wrapper function for plotExprHeatmap to change the colors used for the different conditions (since they are almost identical).  This changes them to Black and Red, you just have to set the names of the groups (conditions) and you can set the colors.  This is based on Helena's code, but this was you just need one line in your script instead of several lines.
`
myPlotExprHeatmap <- function
  (
    x,
    features = NULL,
    by = c("sample_id", "cluster_id", "both"),
    k = "meta20",
    m = NULL,
    assay = "exprs",
    fun = c("median", "mean", "sum"),
    scale = c("first", "last", "never"),
    q = 0.01,
    row_anno = TRUE,
    col_anno = TRUE,
    row_clust = TRUE,
    col_clust = TRUE,
    row_dend = TRUE,
    col_dend = TRUE,
    bars = FALSE,
    perc = FALSE,
    bin_anno = FALSE,
    hm_pal,
    k_pal = CATALYST:::.cluster_cols,
    m_pal = k_pal,
    distance = c("euclidean", "maximum", "manhattan", "canberra", "binary", "minkowski"),
    linkage = c("average", "ward.D", "single", "complete", "mcquitty", "median",
                "centroid", "ward.D2")
  )
  {
  hm <- plotExprHeatmap(x, features, by, k, m, assay, fun, scale, q, row_anno, col_anno, row_clust, col_clust, row_dend, col_dend, bars, perc, bin_anno, hm_pal, k_pal, m_pal, distance, linkage)
  cm <- ColorMapping("condition", c(Itacitinib = "black", Hold = "grey", Control = "red"))
  hm@left_annotation@anno_list$condition@color_mapping <- cm
  hm@left_annotation@anno_list$condition@fun@var_env$color_mapping <- cm
  hm
}
`
