### ISSUE TITLE
Order plotCounts bars

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#246]
Hello CATALYST team

Is there any way to order the bars in plotCounts? I'm trying to order them by condition but they are plotted by alphabetical order. I tried to change the order doing this: 

colData(sce)$condition = factor(colData(sce)$condition, levels = c("PREScovidNeg", "PRES","EDAD","MDAD","ODAD", "BRON","ACFF", "IPMH", "unknown"))

plotCounts ordered the bars correctly if I color by anything other than condition, but If I color by condition, the order is alphabetical.

What can I do?

Regards
Juan

**Comment by HelenaLC** [comment]
It’s a ggplot, so you simply use +scale_x_discrete(limits=c(…)) Depending on if the x-axis are samples/conditions, this should be a vector of the samples/conditions in the order you like.

**Comment by algebio** [comment]
BIG THANK YOU!!!

**Comment by HelenaLC** [comment]
Welcome :) - happy holiday season
