### ISSUE TITLE
filterSCE not working with my meta file input

### ISSUE THREAD

**Issue by Stein-ErikG** [HelenaLC/CATALYST#248]
Hi, 

I have a sce with fcs files from control and in vitro treated PBMC AML and healthy donors. In my meta file ive made a "class" column that is either AML of HD. There are also columns for filename (full path), file_name (just filename), patient_id(AML/HD id), condition (control/treated) and sample_id (patient+condition concatenated).

head(meta)
                file_name patient_id    condition                    class            sample_id
1 FLT3_BC1__c1_Casp3-.fcs       AML_1     A_Ctrl           AML            AML_1_A_Ctrl
2 FLT3_BC1__c2_Casp3-.fcs      AML_1     B_332           AML           AML_1_B_332
3 FLT3_BC1__c3_Casp3-.fcs      AML_1     C_317           AML             AML_1C_317
4 FLT3_BC1__c4_Casp3-.fcs      AML_1      D_Q              AML           AML__D_Q
5 FLT3_BC1__c5_Casp3-.fcs      AML__2    A_Ctrl         AML            AML__2_A_Ctrl
6 FLT3_BC1__c6_Casp3-.fcs      AML__2     B_332        AML             AML__2_B_332

(Ive taken avay the full path column)

I want to have the HD samples in the clustering and DR, but i also want to present just AML og HD data; i want to filter sce in class. but that does not work, nothing happens when: c <- filterSCE(sce, class != "HD")

But  c <- filterSCE(sce, condition != "C_BCI317") works perfectly. 

can you help? Im sorry if this is a trival mistake im making! I guess the question is how to add more than three columns  to colData(sce)?

**Comment by Stein-ErikG** [comment]
Well, I managed to update the colData(sce) by having the the information needed for the class column combined with the data in the patient_id column in the meta file. After prepData() i then used strsplit to create a new column in colData(). This allowed me to have the correct cell to label throughout. 

class <- as.data.frame(sce$sample_id)
sce$class <- sapply(strsplit(as.character(class $`sce$sample_id`) , "_") , "[" , 3)
sce$condition <- sapply(strsplit(as.character(class $`sce$sample_id`) , "_") , "[" , 2)

But is there a way to include more variable straight from the meta file?

**Comment by HelenaLC** [comment]
If I understand correctly, yes, you should be able to do so via the `md_cols` argument in `prepData()` as follows:
```
# default:
prepData(...,
    md_cols = list(
        file = "file_name", id = "sample_id", 
        factors = c("condition", "patient_id"))
# in your case:
prepData(...,
    md_cols = list(
        file = "file_name", id = "sample_id", 
        factors = c("condition", "patient_id", "class"))
# actually, I think only this should be sufficient,
# since only the 'factors' differ from the default: 
prepData(...,
    md_cols = list(factors = c("condition", "patient_id", "class"))
```
