### ISSUE TITLE
Clustering using principal components

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#251]
Dear Helena,

Is there a way to use cluster() with features = first ten principal components instead of type or state markers?

Thank you.

**Comment by nilseling** [comment]
Hey @algebio 
check out the [bluster](http://www.bioconductor.org/packages/release/bioc/vignettes/bluster/inst/doc/clusterRows.html) package. Maybe that helps.

**Comment by HelenaLC** [comment]
Has this been resolved?

**Comment by nilseling** [comment]
I guess this is more of a feature request where it would be nice to run `FlowSOM` clustering directly on low-dimensional embeddings. For a tutorial that I'm writing I'll have to cluster on those embeddings after batch correction using fastMNN or harmony. The bluster package provides a SOM implementation but using `CATALYST` for this would be nicer.

**Comment by algebio** [comment]
I agree, having this feature implemented in CATALYST would be much nicer.
Also, I tried bluster, as Nils suggested but my laptop couldn't handle it
due to the size of the object. I didn't have this problem using the same
dataset in CATALYST, but I don't know if the reason for this huge object is
using bluster, my fault or the different embedding.

Anyway, we decided to move on and not to do this for the time being. But as
Nils said, it would be nice to have it in future versions.

On a separate note, very soon I will finish my contract as a cytometry data
analyst and I don't know if I will ever use these tools again (which would
be a pity). I wanted to say thank you for all your help during the last
three years, you are a terrific team!

Regards
Juan

**Comment by HelenaLC** [comment]
Sorry for the (1 year) delay... but for what it's worth: I think that there are many potential steps that could easily be replace (done outside of `CATALYST`) and fed back to `CATALYST`. Here, for instance, you could simply run a PCA, cluster on the `reducedDim(sce, "PCA")`, and assign the resulting `cluster_id`s into the obeject (see vignette section on using other clusterings).
