### ISSUE TITLE
plotDiffHeatmap() issue

### ISSUE THREAD

**Issue by ElinorWing** [HelenaLC/CATALYST#252]
Hello,

I have been having an issue with PlotDiffHeatmap() in that it is ordering by patient ID rather than condition making it more difficult to visualise the differences. I followed the advice when this was posted previously in #164 and reordered the samples in experiment info but it made no difference.

```{r Fig1, echo=TRUE, fig.height=3, fig.width=4}
plotDiffHeatmap(sce, rowData(da_res2$res), all = TRUE, fdr = FDR_cutoff, top_n = 5)
```
[diffcyt_labelled_top5.pdf](https://github.com/HelenaLC/CATALYST/files/7897008/diffcyt_labelled_top5.pdf)

Please let me know if you need more information, first time raising an issue on here so I am sure I have missed something!

Thanks!

**Comment by HelenaLC** [comment]
Could you try reordering the `levels(sce$sample_id)`? I believe that is what determines the ordering in the heatmaps - but would have to try it out if that doesn't work.

**Comment by ElinorWing** [comment]
Thanks for getting back to me so quickly! 

I have tried reordering `levels(sce$sample_id)` but it only changed the order of the sample_ids, the final heatmap looked the same but with the sample_ids at the bottom in the correct order but matched to the wrong sample.

**Comment by HelenaLC** [comment]
could u please post an example heatmap of this and also the code of how you reordered the sample IDs? Otherwise it's hard for me to follow. Thanks!!

**Comment by ElinorWing** [comment]
Sorry it has taken me so long to reply! I managed to get it working - I think when I first tried I was using levels() incorrectly and it kept all of the info on the heatmap the same and only changed the sample_id labels.

This is how the heatmap looked before:
[diffcyt_labelled_top5.pdf](https://github.com/HelenaLC/CATALYST/files/8233171/diffcyt_labelled_top5.pdf)


```
> levels(sce_synt$sample_id)
[1] "RA1_PBMC" "RA1_SynT" "RA3_PBMC" "RA3_SynT" "RA5_PBMC" "RA5_SynT"
```


```
> sce_synt$sample_id <- factor(sce_synt$sample_id, levels = c("RA1_PBMC", "RA3_PBMC", "RA5_PBMC", "RA1_SynT", "RA3_SynT" ,"RA5_SynT"))
> levels(sce_synt$sample_id)
[1] "RA1_PBMC" "RA3_PBMC" "RA5_PBMC" "RA1_SynT" "RA3_SynT" "RA5_SynT"
>
>
> plotDiffHeatmap(sce_synt, rowData(da_res1$res), all = TRUE, fdr = FDR_cutoff, top_n = 5)
```


This is how the heatmap looks now:
[diffcyt_top5_after.pdf](https://github.com/HelenaLC/CATALYST/files/8233168/diffcyt_top5_after.pdf)


Thank you for your quick replies!
