### ISSUE TITLE
plotting custom cell annotation

### ISSUE THREAD

**Issue by igordot** [HelenaLC/CATALYST#255]
A lot of the plotting functions like `plotAbundances` and `plotClusterHeatmap` expect the clusters in the `cluster_codes` element generated by FlowSOM/ConsensusClusterPlus. Is there a way to plot other types of cell annotation?

**Comment by HelenaLC** [comment]
There are instructions on how to use other clusterings in the vignette [here](https://bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html#using-other-clustering-algorithms); see also issues #140 #187 ...
