### ISSUE TITLE
UMAP/Clustering Reproducibility

### ISSUE THREAD

**Issue by newmmat** [HelenaLC/CATALYST#256]
Hi Helena,

I will preface that I am not a skilled coder, but I am having issues with reproducibility of UMAP metaclustering for a dataset in CATALYST. I use seeds every time I start an analysis, but even so it seems that when I reopen the dataset with the same seed, I get a slightly different clustering within my UMAPs that are identifiable on subsequent heatmaps. I've attached an example of two analyses of the same data, where we see that not only have the Cluster IDs changed colors and order, but there have also been some changes to the clusters themselves (CD45RO highlighted as an example).

My code chunk is below, which is based off of the CATALYST HTML (I probably have an excessive number of seeds set):

#run clustering and dimension reduction
sce <- cluster(sce, seed = 100)
set.seed(100)
sce <- runDR(sce, dr = "UMAP", cells = 500)

plotDR(sce)
set.seed(100)
plotDR(sce, color_by = "meta10", facet_by = "condition", set.seed(100))

#access specific clustering resolution
table(cluster_ids(sce, "meta10"))

plotExprHeatmap(sce, features = "type", by = "cluster_id", k = "meta10",
                scale = "first", q = 0, bars = TRUE)

My questions are:

1. What can I do to ensure that cluster populations stay consistent with regards to marker expression when I revisit analyses? Am I placing my seed commands in the wrong place?

2. If possible, is there an easy way to ensure that color codes for each cluster stay consistent?

Thanks so much!

[UMAP_Reproducibility_122421.pdf](https://github.com/HelenaLC/CATALYST/files/7974884/UMAP_Reproducibility_122421.pdf)

**Comment by HelenaLC** [comment]
**1. Reproducibility**

From our [F1000Research workflow](https://f1000research.com/articles/6-748): 

> `FlowSOM` output can be sensitive to random starts. To make results reproducible, we first set a seed for random number generation prior to calling `cluster()`, and, secondly, specify a seed argument inside `cluster()`. Unfortunately, this is necessary as the `ConsensusClusterPlus()` function internally calls `set.seed()` and will, when not provided with a seed, overwrite our seed using the current system time (`set.seed(as.numeric(Sys.time()))`).

See the following example:

```
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)

one <- cluster(sce, seed = 1, verbose = FALSE)
two <- cluster(sce, seed = 1, verbose = FALSE)
identical(one$cluster_id, two$cluster_id)
# FALSE

set.seed(1)
one <- cluster(sce, seed = 1, verbose = FALSE)
set.seed(1)
two <- cluster(sce, seed = 1, verbose = FALSE)
identical(one$cluster_id, two$cluster_id)
# TRUE
```

**2. Consistent color coding**

If the clustering is consistent across different plots, the color coding will be as well! Also, you can specify a custom color palette using `+ scale_fill/color_manual(values = ...)` (for `ggplot2::ggplot`s) and via the `k/m_pal` argument for heatmaps.
