### ISSUE TITLE
Filter cells based on expression

### ISSUE THREAD

**Issue by bioguy2018** [HelenaLC/CATALYST#258]
Dear Helena,
Is there a method to filter out cells with specific expression values within Catalyst? the filterSCE() did not help in this case or maybe I couldn't make it work.

Thank you so much!

**Comment by HelenaLC** [comment]
You can use basic `SingleCellExperiment` operations for this, nothing `CATALYST`-specific. E.g., 
```
y <- exprs(sce) # get expression matrix
i <- y["CDX", ] >= 0.1 # find cells with CDX expression of at least 0.1
sub <- sce[, i] # subset the object
```

**Comment by bioguy2018** [comment]
Dear Helena,
Thanks a lot for your answer! is exprs() provided by SingleCellExperiment ? I have v1.16.0 but this function is not within the package. So I am not so sure!

**Comment by HelenaLC** [comment]
if you print the sce, which assays do you see are available? You can access an assay of choice via assay(sce, assayName)

**Comment by bioguy2018** [comment]
Dear Helena,
I have come to a confusion! There is a differnece when I run
filterSCE(sce[,assay(Merged_daf_rpheno,"exprs")[j,]>=5]
and when I do not specify the exprs explicitly!
I thought the default assay is anyway exprs so I am surprised! what does the filterSCE() actually filter then when I do not provide the slot??

**Comment by HelenaLC** [comment]
You mean there's a difference between i) `assay(sce)` and ii) `assay(sce, "exprs")`? If yes, that's of course to be expected because i) accesses the 1st available assay (here, ion counts), while ii) uses the transformed data (exprs).
