### ISSUE TITLE
Error in codes[, 1] : incorrect number of dimensions

### ISSUE THREAD

**Issue by algebio** [HelenaLC/CATALYST#259]
Hello CATALYST team

I am trying to construct a sce object from a matrix which has thousands of cells in rows and markers plus clustering, umap coordinates and metadata in columns.

I managed to do so and I can use plotDR() without using runDR() and get exactly the same umap that my colleague gets using a different software (by mine has much nicer aesthetics) 

I am trying to do the same with clustering and replicate his heatmap but when I use plotExprHeatmap(sce, by = "cluster_id",...) I get the message "Error in codes[, 1] : incorrect number of dimensions". If I use plotExprHeatmap(sce, by = "sample_id",...), it works fine and I get the heatmap.

I have built the sce in this way:
sce <- SingleCellExperiment(t(cdr))
sce@colData@listData[["cluster_id"]] <- factor(cdr$Batch.SOM.Cluster.Assignments)
sce@metadata[["cluster_codes"]][["som100"]] <- som$som100
sce@metadata[["cluster_codes"]][["meta40"]] <- som$meta40
sce@metadata[["SOM_codes"]] <- cdr$Batch.SOM.Cluster.Assignments

Probably I'm doing something very basic wrong because this is the first time I create a sce from scratch. 

Could you please help me or point me in the right direction?

Many thanks
J

**Comment by HelenaLC** [comment]
Where is `som` coming from? And is `cdr` the matrix with rows = cells and columns = markers (since you use `t` to make the SCE)? Also, from what it looks like, `cdr` contains both your measurements and `Batch.SOM.Cluster.Assignments`. The latter should NOT go into the SCE's assay data.

**Comment by HelenaLC** [comment]
Ok. Tricky to write the code without the objects, but it should look something like this:
```
markers <- c("CDA", ..., "CDZ")
y <- t(cdr[, markers])

metadata <- setdiff(names(cdr), markers)
cd <- cdr[, metadata]
cd$cluster_id <- seq_len(ncol(y))

codes <- data.frame(foo = seq_len(ncol(y)), sim)
md <- list(cluster_codes = codes)

sce <- SingleCellExperiment(
  assays = list(exprs = y),
  colData = cd, metadata = md)
```
