### ISSUE TITLE
runDR(..., cells = )

### ISSUE THREAD

**Issue by kmincham** [HelenaLC/CATALYST#260]
I'm unsure if this is an issue or a question, so apologies upfront.

When performing DR, i only want to select 50 cells/sample, as this is the maximum i can use to capture all samples equally. However, then i run

`sce <- runDR(sce, dr = "UMAP", cells = 50, features = "type")`

there is no difference in the UMAP generated compared to when i run 

`sce <- runDR(sce, dr = "UMAP", cells = 500, features = "type")`

, which should be displaying 10x the number of cells.

I ran the "Differential discovery with CATALYST" workflow on Bioconductor with 'cells = 500' (example provided) and also 'cells = 50', and still had the same issue.

Any possible guidance with this would be greatly appreciated.

Best regards
Kyle

**Comment by HelenaLC** [comment]
could you post the output of `table(sce$sample_id)`?

**Comment by kmincham** [comment]
Thanks for such a rapid response Helena.

From the CATALYST workflow on Bioconductor, i get

<img width="501" alt="Screenshot 2022-02-10 at 18 18 04" src="https://user-images.githubusercontent.com/87082215/153471261-2d513000-62b9-472b-a760-bfd0159f952b.png">

**Comment by HelenaLC** [comment]
Ah ok, sorry, I didn't read detailed enough - it is correct that both `cells = 50` and `cells = 500` will leave the `sce` dimensions unchanged (the number of cells in the object will be retained and not be affected by `runDR`). What `runDR` does is to internally downsample cells, compute the DR for that subset, and write the coordinates back into the object leaving coordinates NA for cells that weren't use. So, if you `plotDR` you should definitely see a difference. 

The motivation here is that `cells` can be used to speed-up DR, but all cells might be useful/informative for other downstream analyses (e.g., visualisation, differential testing, etc.). If you really do want to get rid of these, you can do `sub <- sce[, !is.na(reducedDim(sce)[, 1])]`.

**Comment by kmincham** [comment]
Thank you for this explanation Helena.

It still appears to me that there is no difference in the cell numbers being plotter when I `plotDR`. The figures below are for `cells = 500` and `cells = 5` (to make it more obvious than `cells = 50`).

<img width="433" alt="Screenshot 2022-02-10 at 19 16 40" src="https://user-images.githubusercontent.com/87082215/153484324-a7d72701-0d61-4c22-9400-3db96165f903.png">
<img width="435" alt="Screenshot 2022-02-10 at 19 41 08" src="https://user-images.githubusercontent.com/87082215/153484362-e3e9febe-52e9-4d3b-8ce6-2f0a63cb6641.png">

**Comment by kmincham** [comment]
I re-ran the analysis and performed `cells = 5` first and still had the same result. Thank you for your help with this tonight. If I'm unable to resolve this I'll post up here tomorrow.

**Comment by HelenaLC** [comment]
Also, if the issue persists by the end of your work-day, could you share the relevant code? I.e. the part where you run and plot the DR. Thanks!

**Comment by HelenaLC** [comment]
Finally, table(sce$sample_id, is.na(reducedDim(sce)[, 1])) should give you an overview of how many cells from each sample were used for the DR. So this might be useful spot check to do.

**Comment by HelenaLC** [comment]
Any update on this?
