### ISSUE TITLE
"subscript out of bounds" Error With "Figure 26" - Reference #242

### ISSUE THREAD

**Issue by ramziabb** [HelenaLC/CATALYST#261]
This is in reference to closed issue #242.  I added another post, but wasn't sure how to reopen that issue.

**Comment by HelenaLC** [comment]
I re-opened it & will close this one to avoid redundancy. Will get to it tomorrow, as it's quite late here. Cheers!

**Comment by ramziabb** [comment]
Thanks Helena!
