### ISSUE TITLE
Is dead cell removal part of the CATALYST pipeline

### ISSUE THREAD

**Issue by gmbambo** [HelenaLC/CATALYST#262]
Hi,

I am using the instructions from Bioconductor (https://www.bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html#introduction)
to perform Cytof analyses, I was wondering if dead cells are removed as part of the pipeline. If not, do you have any recommendations on how to remove dead cells via R?

I am performing clustering (on step 10 of the vignette) and I noticed a large number of cells in clusters that did not contain my cell surface markers, so I was curious if these were dead cells.

Thanks in advance,
Gillian

**Comment by HelenaLC** [comment]
There is no default filtering done in any step. To do this in R, you're best shot is probably the gating implemented in the `openCyto` package; having a look [here](https://f1000research.com/articles/9-1263) might help.  
Alternatively, if there's a specific cluster that is, say, CDX- (something that's not of interest), you could simply filter it out via `filterSCE(sce, k = "metaX", !cluster_id %in% c(...))`, `metaX` is the clustering to use and ... are the cluster IDs to remove.

**Comment by ramziabb** [comment]
Another suggestion is to use manual gating to gate on Live Singlets, then export FCS files and use those as your inputs.

**Comment by gmbambo** [comment]
Thank you both! I am working on using the link provided to perform the gating. I have a lot of fcs files so an automated way if preferred.

**Comment by gmbambo** [comment]
> Another suggestion is to use manual gating to gate on Live Singlets, then export FCS files and use those as your inputs.

Thanks! When I initially tried using flowjo, I didnt have the option to export as FCS files just the .wsp or CSV. If you have any pointers/link, that would be awesome.

**Comment by ramziabb** [comment]
Just gate down to singlets, then negative for you live dead stain.  Then apply to all your samples.  Then do a quick QC check.  Then to output them right click the Live Singlets gate in your project and select , Export / Concatinate Populations, format CSV Channel Values, select the parameters (all compensater probably, or just select the compensated by hand and get rid of FSC or whatever you don't need).

Then you can use those as your input into CATALYST workflow.  I don't include my Live/Dead or Fsc /Ssc etc at all in the files I input to CATALYST.

Just ask if that isn't clear.  it does take a little bit of tinkering to be honest.

**Comment by ramziabb** [comment]
Actually just read through this:

https://wiki.centenary.org.au/display/SPECTRE/Exporting+data+from+FlowJo+for+analysis+in+Spectre

:)
