### ISSUE TITLE
Some markers not appearing in the results

### ISSUE THREAD

**Issue by fcomnozz** [HelenaLC/CATALYST#264]
Hi Helena, 

First of all, thank you so much for your amazing work!

I am using your package (through CyTOF workflow - https://bioconductor.org/packages/release/workflows/html/cytofWorkflow.html) in order to assess the immune status of a group of patients. However, while exploring the results generated from the SingleCellExperiment object, I found out that some markers were missing, like CD3 or CD8. 

By exploring the SCE, I realized that these specific markers appear in the field "int_colData - listData", while the others don't. Why is the function making that sort of split? I checked if the names of the correspondent fluorophores were different in my "panel" metadata file, but that wasn't the problem.

Thank you in advance and congratulations for your work.

Best regards,

Francisco

Session info:

> R version 4.1.2 (2021-11-01)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.4 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
> 
> Random number generation:
>  RNG:     Mersenne-Twister 
>  Normal:  Inversion 
>  Sample:  Rounding 
>  
> locale:
>  [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                  LC_TIME=es_ES.UTF-8           LC_COLLATE=en_US.UTF-8       
>  [5] LC_MONETARY=es_ES.UTF-8       LC_MESSAGES=en_US.UTF-8       LC_PAPER=es_ES.UTF-8          LC_NAME=es_ES.UTF-8          
>  [9] LC_ADDRESS=es_ES.UTF-8        LC_TELEPHONE=es_ES.UTF-8      LC_MEASUREMENT=es_ES.UTF-8    LC_IDENTIFICATION=es_ES.UTF-8
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] CATALYST_1.18.1             SingleCellExperiment_1.16.0 SummarizedExperiment_1.24.0 Biobase_2.54.0             
>  [5] GenomicRanges_1.46.1        GenomeInfoDb_1.30.1         IRanges_2.28.0              S4Vectors_0.32.3           
>  [9] BiocGenerics_0.40.0         MatrixGenerics_1.6.0        matrixStats_0.61.0          flowCore_2.6.0             
> [13] xlsx_0.6.5

**Comment by HelenaLC** [comment]
Since you mention "fluorophores", I suppose setting `FACS = TRUE` in `prepData()` should resolve this. Please see related issues #207 #193 #178 etc.
