### ISSUE TITLE
Error in plotExprHeatmap

### ISSUE THREAD

**Issue by ramziabb** [HelenaLC/CATALYST#265]
Helena,

Is there an error in plotExprHeatmap when you specify by = "both"?  I see the clauses for speficying "sample_ID", but it looks like "cluster_id" may be caught in an else statement and then if it goes into the "both" clause it throws an error:

Error in .check_args_plotExprHeatmap(args) : 
  length(.get_features(u$x, u$features)) == 1 is not TRUE

I am trying to do the heatmap by cluster and condition:
plotExprHeatmap(sce, features = "state", by = "both", k = "merging1", row_anno = TRUE)

Thanks a lot,
Ramzi

**Comment by HelenaLC** [comment]
Nope, not an error. If you make the x and y axis into variables (cluster and sample), there’s no axis left for features, so you can only plot one at a time. All state features only work if ‘by’ is not both, leaving a free axis for the features.

**Comment by HelenaLC** [comment]
Check out plotMultiHeatmap to handle this, ie generate mutiple heatmaps side by side for many features.

**Comment by ramziabb** [comment]
Thanks!
