### ISSUE TITLE
Sub Clustering Sample

### ISSUE THREAD

**Issue by ramziabb** [HelenaLC/CATALYST#268]
After the initial clustering, has anyone done subclustering - reclustering with just cells from a handful of selected clusters?  If so, can they please provide a code sample?

Thank you!
Ramzi

**Comment by HelenaLC** [comment]
See issue #266 - in general, I'd recommended searching the closed issues.

**Comment by ramziabb** [comment]
Ugh - I am sorry I wasted your attention.  yesterday was crazy and I haven't used much GitHub and  . . . I neglected to search.

Apologies and thanks for the link.

**Comment by HelenaLC** [comment]
All good, no problem ✌️
