### ISSUE TITLE
Large data / RAM issue

### ISSUE THREAD

**Issue by LogIN-** [HelenaLC/CATALYST#272]
Hello,

first of all I must give big thanks to the developers of this R package and for the workflow publication that is published.

I am having one issue with using prepData function.
I guess that I have a bit too much files and my RAM gets all used while prepData is processing all the FCS files.
I have 128GB of ram and are trying to load 90 files that have around 50GB all together.

I would be a nice if some-kind of sequential processing support for many/large files could be integrated in future.

Or maybe there is some workaround already that we could use?

**Comment by LukaTandaric** [comment]
Dear LogIN-,

While I do agree with the fact that you may be able to shrink the size of your dataset, I would like to elaborate on purisuto's 2nd bullet point. I had the same issue while analyzing a large dataset, even though my computer is equipped with 32GB of physical RAM. What fixed my problem was enabling the pagefile (virtual RAM), and setting it to its maximum of 4 x (physical RAM) (128 GB in my case). Although the program I ran chewed through almost the entire pagefile, the code did execute successfully in the end.

Have a look at this online guide on how to enable and adjust the pagefile: [https://www.tomshardware.com/news/how-to-manage-virtual-memory-pagefile-windows-10,36929.html](https://www.tomshardware.com/news/how-to-manage-virtual-memory-pagefile-windows-10,36929.html)

What the pagefile basically is is space on your disk that is set aside as "slow RAM" while your actual RAM deals with prioritized tasks.

If the 128 GB of ram you have is physical, you can theoretically set your pagefile size to 512GB if you so wish, and have the empty space for it on your disk. However, the memory on your HD/SSD that has been used by the pagefile does not become available again until you restart your system. Additionally, repeated writing of data onto an SSD causes it to degrade faster, so keep that in mind if you have an SSD.

Perhaps your workplace has access to a powerful computer you could use?

My computer runs Windows 10, so I unfortunately have no experience in changing this setting on a Mac, but I'm sure there is a guide for that as well.

Regards.
Luka

**Comment by HelenaLC** [comment]
My intuition answer is that this would require something like a delayed backend for FCS, which is beyond CATALYST. E.g., we have this for scRNA-seq data, where counts are stored as .hdf5 or similar, but there’s no way of gettinf around reading in the data as is (unless flowCore et al. implement methods to handle this) - at least once. Afterward, one could write intensities/counts to another format & use existing delayed matrix infrastructure (supported in Bioc and SingleCellExp already). Hope that makes sense & interesting point!

**Comment by SamGG** [comment]
If it helps https://github.com/RGLab/ncdfFlow
