### ISSUE TITLE
plotDiffHeatmap - Remove Sample Names?

### ISSUE THREAD

**Issue by ramziabb** [HelenaLC/CATALYST#275]
Is there a way to remove the sample names from heatmaps?  Like the below but getting rid of the text Ref 1-8 and BCRXL1-5?

![image](https://user-images.githubusercontent.com/93796927/164292700-366c52f3-6048-48c2-ae40-f0f011e96812.png)

**Comment by HelenaLC** [comment]
This should do the trick:
```
library(CATALYST)
library(diffcyt)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

design <- createDesignMatrix(PBMC_md, cols_design = 3:4)
contrast <- createContrast(c(0, 1, 0, 0, 0))
ds <- diffcyt(sce, 
  clustering_to_use = "meta20",
  design = design, contrast = contrast, 
  analysis_type = "DS", method_DS = "diffcyt-DS-limma")
df <- rowData(ds$res)

hm <- plotDiffHeatmap(sce, df)
hm@column_names_param$show <- FALSE
hm
```
![image](https://user-images.githubusercontent.com/14542264/164293928-d1cf7823-d410-4d08-81cc-6c1839a77527.png)

Generally, to modify `ComplexHeatmap::Heatmap` objects after creation, my best guess is to play with altering `@` and `$` and see what autocompletion gives.

**Comment by ramziabb** [comment]
You are fast, thank you.
