### ISSUE TITLE
Change point size in tSNE plotDR?

### ISSUE THREAD

**Issue by tessbrodie** [HelenaLC/CATALYST#276]
Dear Helena,

Thanks for your great pipeline and I was wondering if it is possible to change the point size for the tSNE and UMAP dimensionality reduction graphs in CATALYST?  We tried to do 

plotDR(sceU, dr = "TSNE", color_by = "mm", pt.size = 1.25)

with no luck.  Is there a way to do this?
Thanks for your time and help,
Best,
Tess

**Comment by HelenaLC** [comment]
Yes, indeed, the point `size` argument is currently not exposed to the user... You can easily modify any graphics parameters downstream, however, also including, for example, transparency (`alpha`) or `shape`, as follows (this goes for any object of call `ggplot`):
```
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- runDR(sce, dr = "UMAP", cells = 100)
p <- plotDR(sce, color_by = "CD7")
p <- plotDR(sce, color_by = "CD7")
q$layers[[1]]$aes_params$size <- 2
patchwork::wrap_plots(p, q)
```
![image](https://user-images.githubusercontent.com/14542264/165278993-75ac3be3-725a-4280-a319-ce32b091db73.png)

**Comment by tessbrodie** [comment]
Thanks so much for the quick and helpful response, but when I run this, I get the following Error:

p <- plotDR(sceU, dr = "TSNE", color_by = "mm")
q$layers[[1]]$aes_params$size <- 2

Error in `*tmp*`$layers : object of type 'closure' is not subsettable

Could you help me with this?
Best,
Tess

**Comment by SamGG** [comment]
Typo: the 2nd plot should be stored in q.

```
q <- plotDR(sce, color_by = "CD7")
q$layers[[1]]$aes_params$size <- 2
```

**Comment by tessbrodie** [comment]
Amazing!  Thanks so much, I should have noticed that,
Best,
Tess
