### ISSUE TITLE
Is it possible for prepData to take intensity data in data.frame/matrix and metadata

### ISSUE THREAD

**Issue by lengfei5** [HelenaLC/CATALYST#278]
Hi there, 

Thank you for such a great package and I have just a naiv questions regarding the prepData.
Is it possible for prepData to take the intensity data in data.frame/matrix as input together with metadata ?
I am asking this because my current flow cytometry data from our collaborators is one big .csv file together with metadata.

Thank you.

Best,
Jingkui

**Comment by HelenaLC** [comment]
No, `prepData` does not take a count/expression matrix as input. However, it should be straightforward to directly construct a SCE using the `SingleCellExperiment` constructor. Tricky to come up with the exact code without knowing what your data looks like, but you should do something like
- split the measurement data & metadata into separate table
- transform the former into a matrix via `as.matrix`
- construct a table of appropriate format for `metadata(.)$experiment` info (see the example data for inspiration)
- assign `"type"/"state"/"none"` in `rowData(.)$marker_class` to specify type/state/irrelevant markers
Happy to help if you're struggling with this! If so, please post something like `head(your data)`.

**Comment by lengfei5** [comment]
Dear @HelenaLC , 

Thanks so much for your prompt answer and this is really amazing. 

Here is how my intensity matrix and metadata look like:
![Screen Shot 2022-05-02 at 9 53 13 AM](https://user-images.githubusercontent.com/24827756/166202313-8fce587e-3aa4-4d2a-9def-b9ae9910e7d0.png)

Each row of the metadata is for one cell. 

If I directly construct SCE object with the data and metadata, 
how do I transform the data, like what your `preData` function does ?
In addition,   the "type"/"state"/"none" in `rowData(.)$marker_class`, what do they mean ? 
in my case, I have just 5 protein intensities. 

Thanks again.

Best,
Jingkui

**Comment by HelenaLC** [comment]
type/state is meant to distinguish between markers for subpopulation annotation & those that might be subject to state changes across conditions (i.e., type vs functional markers). Type markers are, by default, used for clustering. And there are some plots that default to using type/state markers. However, all functions also allow to input any features you want so, in your case, just assign something so the object is legit and you can include all features for clustering/visualizations anyways. The transformation is just plain arcsinh, i.e.:
```
# default cofactor for CyTOF 
# (think this is higher for FACS?)
cf <- 5 
# here, x = input SCE with raw data
# stored in assay "counts"
y <- assay(x, "counts")
y <- asinh(sweep(y, 1, cf, "/"))
assay(x, "exprs", FALSE) <- y
```

**Comment by lengfei5** [comment]
Cool and thank for the great help.
All best,
Jingkui

**Comment by HelenaLC** [comment]
Uw. Close the issue if you you got it all figured out (ideally posting your solution as it might be useful to others as well) or otherwise be back for questions/issues you might run into.
