### ISSUE TITLE
daFrame function not found

### ISSUE THREAD

**Issue by fycamu** [HelenaLC/CATALYST#279]
Dear HelenaLC,
I installed the Catalyst package in R 4.2.0 but get an error message when I try to use the daFrame function: "Error in daFrame(d_flowSet, marker_info, experiment_info) : 
  could not find function "daFrame" "
Do you have any advice how to solve this?

Thank you very much!
Lauriane
![Screenshot 2022-05-03 at 13 36 37](https://user-images.githubusercontent.com/81626607/166445917-16f83742-cf80-4ffd-8a79-ce4dd987b123.png)

**Comment by SamGG** [comment]
The daFrame class been removed and the preprocessing pipeline rewritten to use the SingleCellExperiment class instead.
Install a recent Bioconductor (`BiocManager::version()`) and reinstall CATALYST.
HTH

**Comment by fycamu** [comment]
Thank you very much, I will change to SingleCellExperiment then.

**Comment by SamGG** [comment]
To be clear, CATALYST did the change internally. You will directly benefit of this change when you install the latest version of CATALYST.
Best.

**Comment by fycamu** [comment]
Thank your for the precision, I had it run and it worked.
Best
