### ISSUE TITLE
Question about select specific # of events

### ISSUE THREAD

**Issue by Rhodnius** [HelenaLC/CATALYST#280]
Hi Helena,

Thanks for developing the package!

I am using the package right now and I am wondering if there is a way to sample random events for each analyzed sample (for example n=5000) during the preprocessing steps, after creating the flowSet and preparing the data with `prepData`.

Have a nice day,

Juan C.

**Comment by SamGG** [comment]
Hi,
Did you read and test https://github.com/RGLab/flowCore/issues/170 ?
Best,
Samuel

**Comment by HelenaLC** [comment]
If I understand correctly, you want to subset the SCE (after `prepData`), not the FCS files (raw data)? If so, you can do this using base R, e.g.
```
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)

# split cell indices by sample
idx <- seq_len(ncol(sce))
idx <- split(idx, sce$sample_id)

# downsample to at most 'n' events per sample
n <- 600
idx <- lapply(idx, \(.) {
  n <- min(n, length(.))
  sample(., n)
})

# subset object
sub <- sce[, unlist(idx)]
table(sub$sample_id)
```
...which gives the below, as two sample have less than `n` events in my example...
```
table(sub$sample_id)
>  Ref1   Ref2   Ref3   Ref4 BCRXL1 BCRXL2 BCRXL3 BCRXL4 
    600    438    600    600    528    600    563    600 
```
