### ISSUE TITLE
Dot plot of the cells coloured by cluster

### ISSUE THREAD

**Issue by fycamu** [HelenaLC/CATALYST#282]
Hello,

Thank you very much for developing this helpful package. 
I have two questions:
- is it possible, for each sample, to make a dotplot of the cells coloured by their cluster_id, with for example in the x axis intensities for channel1 and in the y axis intensities for channel2?

- how do you deal with batch effects when analysing samples acquired on different days?

Thank you very much,
Lauriane

**Comment by HelenaLC** [comment]
**Scatter plot with cells colored by cluster**
Sure, (1) the `plotScatter` function provides a wrapper to plot channels against one another with point colored by cell metadata variables of interest (e.g., sample, condition, cluster). Alternatively, you can construct a `data.frame` of expression and cell metadata, and use `ggplot` to create a plot to your liking. Minimal reproducible example of both below:
```
library(CATALYST)
library(ggplot2)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)

# (1) using 'CATALYST::plotScatter'
plotScatter(sce, 
  chs = c("CD3", "CD7"), 
  color_by = "meta10")

# (2) using 'ggplot2::ggplot'
codes <- cluster_codes(sce)
i <- match(sce$cluster_id, codes[[1]])
df <- data.frame(
  check.names = FALSE,
  t(assay(sce, "exprs")), 
  colData(sce), codes[i, -1])
ggplot(df, 
  aes(CD3, CD7, col = meta10)) + 
  geom_point()
```
**Dealing with batch effects**
There are various methods available to correct for this, e.g.,[CytofRUV](https://doi.org/10.7554/eLife.59630), [CytoNorm](https://doi.org/10.1002/cyto.a.23904), and [Schuyler et al.](https://doi.org/10.3389/fimmu.2019.02367). These aren't implemented in `CATALYST`, but could easily be incorporated into the workflow as an additional step when applicable.

**Comment by fycamu** [comment]
Thank you very much!!
