### ISSUE TITLE
Annotate on the UMAP instead of just in the legend

### ISSUE THREAD

**Issue by FRLab** [HelenaLC/CATALYST#287]
Hi all,

Do you know if there is any way to plot on the UMAP the name of the clusters instead of just having colors in the legend. 
When you have a lot of clusters if can be difficult to see who is who just with colors.

Thanks a lot in advance,

Quentin

**Comment by HelenaLC** [comment]
Something like this should work ... in case you are faceting, things get a little more tricky: You'll have to `aggregate` by both the cluster ID & the variable(s) faceted by. 

```r
library(CATALYST)
library(ggplot2)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose = FALSE)
sce <- runDR(sce)

plt <- plotDR(sce, color_by = "meta12")

df <- plt$data
df <- aggregate(
  x = df[c("x", "y")], 
  by = list(meta12 = df$meta12), 
  FUN = mean)

plt + geom_label(
  aes(x, y, label = meta12),
  data = df, show.legend = FALSE)
```
![image](https://user-images.githubusercontent.com/14542264/174745358-5ded3a24-bab9-4009-9a96-207a7378f558.png)

**Comment by purisuto** [comment]
Thanks! I got it to work by:

`p + geom_label(data = df, aes(x, y, label = z) , show.legend = FALSE, inherit.aes = FALSE)`
