### ISSUE TITLE
plotPbExprs - statistical analysis

### ISSUE THREAD

**Issue by rebecca1a** [HelenaLC/CATALYST#288]
Hi ihere, 

Does anyone know how I can export the data generated by plotPbExprs to a csv file or alternatively how to run an annova on the data generated and display significance values (I'm comparing three cohorts)? 

Thanks for your help!

**Comment by SamGG** [comment]
Hi,
You should try to extract the data using something like (see https://stackoverflow.com/questions/25378184/extract-data-from-a-ggplot):
```
theplot <- plotPbExprs(your_arguments)
thedata <- layer_data(theplot)
```
List the structure of thedata using `str(thedata)` as there are many facets, and pick up the data you need.
Alternatively, if you are familiar with R, the code is the following of plotPbExprs is the following.
Best.
https://github.com/HelenaLC/CATALYST/blob/f0b44fffbefcfc3ef47e2be511259fae7f1ca032/R/plotPbExprs.R#L101-L127

**Comment by HelenaLC** [comment]
Huh, I didn't know about `layer_data()` and have been using `.$data` instead to extract the `data.frame` underlying `ggplot`s. Thanks Sam!
