### ISSUE TITLE
Compensation issue for dot plots display and file save

### ISSUE THREAD

**Issue by AlexBouz** [HelenaLC/CATALYST#29]
Hi,

I tried using the compensation tool from the web app catalystlite, and the dot plot display tends to disappear after uploading a fcs file (12MB) using nnls method (see screenshots). Any recommendation to solve this issue?
![before](https://user-images.githubusercontent.com/37419030/37486830-13da1eee-2866-11e8-9223-695b0a92eb23.png)
![after](https://user-images.githubusercontent.com/37419030/37486837-1a0a7278-2866-11e8-95b1-1e823d3ff41e.png)

**Comment by HelenaLC** [comment]
Closing this as the Shiny app is no longer supported. While we regret any inconvenience this decision might cause, we feel strongly that interactive data preprocessing (using a GUI) is inefficient, especially for evermore frequent large-scale data, and irreproducible, thereby defeating the purpose of using R in the first place. We have thus decided to focus our efforts towards maintaining and further developing the package's (non-GUI) functionality.
