### ISSUE TITLE
Using Catalyst functions without cluster_codes

### ISSUE THREAD

**Issue by singlecellfan** [HelenaLC/CATALYST#290]
Hi,

I have some data which I have already clustered/annotated and only recently stumbled upon this awesome package. I have created an sce object, however all the Catalyst functions are dependent on cluster_codes. 

I guess I could perform a new clustering using the "cluster" function, but then I would need to re-annotate all the populations.
Therefore, is it possible to still use the functions without having the cluster_codes available? 

Thanks a lot in advance!

**Comment by HelenaLC** [comment]
Yes, please see [here](https://www.bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html#using-other-clustering-algorithms) for how to incorporate custom annotations into the workflow.
