### ISSUE TITLE
diffcyt differential expression model with patient_id as random effect only returns NA p values

### ISSUE THREAD

**Issue by singlecellfan** [HelenaLC/CATALYST#292]
Hi,

I have followed the tutorial and so far all differential expression analyses worked if I did not specify a random variable.
This is how the ds_formula2 looks for me.

![Screenshot 2022-07-25 at 18 28 54](https://user-images.githubusercontent.com/79158757/180828317-c9470455-5962-4c3e-942f-b5e0bef5ebd9.png)
 
`diffcyt(sce, 
                   formula = ds_formula2, contrast = contrast,
                   analysis_type = "DS", method_DS = "diffcyt-DS-LMM",
                   clustering_to_use = "merging_all", verbose = FALSE)`

And this is what I get as a result. All p values are shown as "NA"

![Screenshot 2022-07-25 at 18 32 21](https://user-images.githubusercontent.com/79158757/180828970-44f76d58-04f8-490c-99fd-fb23e0c6cc11.png)

Has this occured before? I am not sure what the problem might be, as the differential expression works fine without specifying a random effect.

Thanks!

**Comment by HelenaLC** [comment]
While `CATALYST` and `diffcyt` try to interact with each other, they are separate packages. I recommend posting this issue here https://github.com/lmweber/diffcyt as @lmweber might be more knowledgeable to answer this.
