### ISSUE TITLE
Change channel names in sce

### ISSUE THREAD

**Issue by purisuto** [HelenaLC/CATALYST#294]
Is there a way to change the channel names in an sce similar to `markernames(fs)` for flowset?

**Comment by HelenaLC** [comment]
By channel names you mean those in the style of `(Di)123Abc` where 123 = mass and Abc = metal? In any case, have a look at `rowData(sce)`, which should contain the channel and antigen names, as well as any other metadata associated with the measurement parameters. These can simply be overwritten using base R commands, e.g., `rowData(sce)$column_name <- new_value`.

**Comment by purisuto** [comment]
Thanks for the reply.  I want to change the name of an antigen (e.g. "CD159c" to "NKG2c"). 

`rowData(sce)` gives a DFrame which seems to have the field I want to change `rownames` but if I enter `rn <- rowData(sce)$rownames`, it returns `NULL`.  Could you provide the code to perform this change? (sorry I'm relatively new to R).

**Comment by HelenaLC** [comment]
For consistency, I'd do the following (minimal example from the `prepData()` help page):
```
# construct SCE
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)

# specify new antigen names
new <- letters[seq_len(nrow(sce))]

# do the overwrite 
rownames(sce) <- new
rowData(sce)$marker_name <- new
```
