### ISSUE TITLE
Downsampling SCE for plotClusterExprs()

### ISSUE THREAD

**Issue by purisuto** [HelenaLC/CATALYST#298]
Hello all,

A member from our group wrote this code for downsampling an SCE.  It is useful to make plotClusterExprs() run faster with large SCEs (>5gb).  Helena, could you possibly add the ability to maintain the same cluster order (histogram order of rows) when running plotClusterExprs() with slightly different data?

Kind Regards,
David Priest

# Sub sample an sce
```{r}
subSCE <- function (sce, n_cells = 500, my_seed = 1234)

{
  
  
  set.seed(my_seed) # Subsetting depends on the seed
  
  # make a list of ids
  cell_ids = c(1:length(sce$sample_id))
  sce$Barcode = cell_ids
  
  #https://bioinformatics-core-shared-training.github.io/cruk-summer-school-2020/scRNAseq/html/02_Pseudotime_Analysis.nb.html

# Careful. replace = TRUE re-samples any samples with less cells than n_cells.
  testo <- colData(sce) %>%
    data.frame() %>%
    group_by(sample_id) %>%
    sample_n(n_cells, replace = TRUE) %>%
    pull(Barcode)
  
  tmpInd <- which(colData(sce)$Barcode %in% testo)
  sce.subset <- sce[,tmpInd]
  
  sample_id_list = levels(sce$sample_id)
  
  # Check that it worked
  # ncol(sce)
  # ncol(sce.subset)
  # length(sce$sample_id[sce$sample_id ==sample_id_list[1]])
  # length(sce.subset$sample_id[sce.subset$sample_id ==sample_id_list[1]])
  
  return(sce.subset)
}
```

**Comment by HelenaLC** [comment]
1. I don't think it's possible to retain the same cluster order with different data in all cases; hierarchical clustering (`hclust`) is performed on the pseudobulks (default: median expression) of the given cells on-the-fly (i.e., internally, within the plotting function). So different cell subsets could, in principle, change the order; but there is no way to prevent this from happening during the plot's generation. However, one could overwrite the cluster-order afterwards if this is really something you want; or simply turn off the reordering/clustering altogether.

2. If I may, here is a simpler version of the above: 
```r
# max. number of cells to retain per sample
n <- 100 
# split cell indices by sample
idx <- split(seq(ncol(sce)), sce$sample_id)
# downsample to at most 'n' cells per sample
# (I would not! sample with replacement here, 
# as you are essentially duplicating cells; 
# instead, use at most as many cells as there are)
idx <- lapply(idx, \(.) sample(., min(n, length(.)))
# subset the data
sub <- sce[, unlist(idx)]
```

**Comment by SamGG** [comment]
Great answer.
It is possible to impose a cluster ordering to a heatmap (at least technically by writing code). If I reformulate the statement of Helena, the question is "how relevant the pre-ordered clustering is?" since it was computed on a different dataset. If the clustering is computed on the whole dataset or by bootstrap (there might exist methods), then such a clustering is representative and could be imposed.
Managing large datasets is still challenging at some points of the workflow IMHO.

**Comment by purisuto** [comment]
Thanks for that.  Yes resampling low-cell samples was not ideal.  Hclust can be turned off for purposes of verifying the histograms of downsampled SCE.
