### ISSUE TITLE
In prepData.R which function is used for arcsinh transformation?

### ISSUE THREAD

**Issue by rohitfarmer** [HelenaLC/CATALYST#299]
In prepData.R at line 325 `if (transform) .transform(sce, cofactor) else sce` which arcsinh transformation function is used? Is it the base R function `asinh()`? Is there any other script that has the code? Thanks!

**Comment by SamGG** [comment]
If you query "transform" in the text input at the top left corner of this Github page, the answer will point to the code of the function `.transform`. So it is simply `asinh()`, or to be complete `asinh(x/cofactor)`, `sweep()` does not matter.
Best.
https://github.com/HelenaLC/CATALYST/blob/f0b44fffbefcfc3ef47e2be511259fae7f1ca032/R/utils-preprocessing.R#L76-L103

**Comment by HelenaLC** [comment]
Exactly, thanks @SamGG. It's essentially base R's `asinh()`, with a few extras (cofactor, input and output assay name for the SCE, and support for both forward- and backward-transformation = going from counts to expression and vice versa). Side note: internal helpers/utilities in `CATALYST` are prefixed with a dot (i.e. `.function`); you can view them within R via the triple-colon operator (i.e., `:::.function`).

**Comment by rohitfarmer** [comment]
Thank you, @SamGG and @HelenaLC, for your explanation; it's helpful. I asked because I transformed the same data with the base asinh(x/cofactor) outside the pipeline, and the values seem to be different. If I export the data from SCE to a data frame (post clustering) and try to find an overlap between the externally transformed data and the data from the clusters. It doesn't match. Besides asinh() transformation, are the values changing during or after the clustering?

**Comment by rohitfarmer** [comment]
So, I figured it out. It had something to do with the formatting/rounding of the values. I had to explicitly do this `mutate_at(vars(all_of(markers)), ~ as.numeric(format(round(., 6))))` on both the datasets to find an overlap. I am basically trying to find a concordance between the manually gated cell populations and automated clusters on the same data.

**Comment by SamGG** [comment]
If you look for concordance of the MMI profiles obtained by both methods, you could build a heatmap (and clustering) of both (or more) clusterings. Then you scan each node (by eye) and check if it contains a cluster of both clusterings.
Gondois-Rey et al 2016 https://pubmed.ncbi.nlm.nih.gov/27059253/

Alternatively, you compute the contingency table of both clusterings (only two), ie the count of event shared by a cluster of clustering A and a cluster of clustering B. Then you reorder it using Hungarian algorithm that moves the highest counts on the diagonal (of the square or the rectangle table) which points which cluster of clustering A match to which cluster of clustering B. Finally you look at the off diagonal counts, which highlight mismatch or clusters that could be merged.
Weber et Robinson 2016 https://pubmed.ncbi.nlm.nih.gov/27992111/
