### ISSUE TITLE
CATALYST light: 'Application unexpectedly exited'

### ISSUE THREAD

**Issue by votti** [HelenaLC/CATALYST#30]
Currently the CATALYSTlight version (http://imlspenticton.uzh.ch:3838/CATALYSTLite/) crashes upon opening on Chrome and Firefox on Ubuntu 17.04:
![catalyst_light_error](https://user-images.githubusercontent.com/3743016/38633840-1e13f694-3dc1-11e8-8ed0-0cbce7e95e2f.png)

Please let me know if you need any other details!

Update: This is the error message from the Javascript console:
```
shiny-server.js:238 Wed Apr 11 2018 19:49:27 GMT+0200 (CEST): Connection opened. http://imlspenticton.uzh.ch:3838/CATALYSTLite/
shiny-server.js:224   
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'server-concatenation.R': No such file or directory
Warning: Error in file: cannot open the connection
Stack trace (innermost first):
    39: file
    38: source
    37: server [/home/Shared/Rcode/CATALYSTLite/CATALYST/inst/shinyGUI/server.R#11]
     1: runApp
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'server-concatenation.R': No such file or directory

shiny-server.js:238 Wed Apr 11 2018 19:49:43 GMT+0200 (CEST): Connection closed. Info: {"type":"close","code":1000,"reason":"Normal closure","wasClean":true}
```

**Comment by markrobinsonuzh** [comment]
It is back online now.

**Comment by PBHsieh** [comment]
Hi,
I also use the CATALYSTlight version (http://imlspenticton.uzh.ch:3838/CATALYSTLite/) and crash after uploading .fcs files on Chrome:

![Screenshot](https://user-images.githubusercontent.com/29281658/90243249-227c8000-de61-11ea-9cf8-1455cf543874.png)
![Console](https://user-images.githubusercontent.com/29281658/90243253-23adad00-de61-11ea-8a1e-8a0aab88a719.png)

help.....
