### ISSUE TITLE
Error with unsupervised clustering

### ISSUE THREAD

**Issue by rmbarricarte** [HelenaLC/CATALYST#302]
Good afternoon,

First of thanks a lot for the CATALYST, we use it all the time for our CyTOF analysis and publications!. We have already been using it for 3 years and just this week we started getting an error in all our lab computers that we had never gotten before when running the unsupervised flowSOM clustering part:
> sce <-cluster(sce, features= 'type', xdim=10, ydim=10, maxK=20, seed=1234) 
Error in cluster.default(sce, features = "type", xdim = 10, ydim = 10,  : 
  only implemented for resamples objects

We tried to run some data that we analyzed last week without any issues using the same scripts but the problem persisted.

I was wondering if someone else has gotten this error and if so, how ti fix it.
Thanks a lot!
ruben

**Comment by SamGG** [comment]
The first result in Google for "only implemented for resamples objects" is https://stats.stackexchange.com/questions/277244/error-in-cluster-defaultid-only-implemented-for-resamples-objects. It sounds that there is a conflict of package, that the order of loading package matters and that a package has overwritten the definition of some functions. Did you add a package in the list of packages of your script? More generally, did you change something?
Best.

**Comment by HelenaLC** [comment]
Hey, if this is resolved, please close the issue, thanks! Else, have you tried explicitly calling `cluster` from `CATALYST`'s NAMESPACE, i.e., via `CATALYST::cluster(...)`?

**Comment by rmbarricarte** [comment]
Sorry, I thought I did. After all it was an issue with a new OS operating system messing up some dependencies. Thanks a lot!
