### ISSUE TITLE
Error during debarcoding and compensation process

### ISSUE THREAD

**Issue by cipheLab** [HelenaLC/CATALYST#31]
Hello,
I tried to use the CATALYST tool to compensate FCS files but this error message appeared :
``Warning: running command '"zip" -r9X "C:\Users\egregori\AppData\Local\Temp\RtmpQL6PkQ\file1f6022726862.zip" "141Pr_01_comped.fcs" "catalyst-concat_comped.fcs" ' had status 127``

I also tried to debarcode my multiplexed file and this message appeared (see the attached file)
![image1](https://user-images.githubusercontent.com/37363841/38735434-1474909e-3f29-11e8-821e-44c777ef26c6.png)

What can I do to fix it ?

Thank You
Ahlam

**Comment by HelenaLC** [comment]
This should be fixed now.
