### ISSUE TITLE
Plotting manually assigned clusters on tSNE

### ISSUE THREAD

**Issue by Tregwiz** [HelenaLC/CATALYST#311]
Hi,
Thanks for providing such a great pipeline for flow cytometry analysis.
My issue is simpler to a previous post: https://github.com/HelenaLC/CATALYST/issues/174 .
Apologies if this issue would be better placed in that thread, I was unsure whether you would see any further comments as that thread is marked as closed.
Basically, I completed FLOWSOM clustering usually Catalyst and from the 18 clusters I obtained, I reduced these to 10  by manually assigning specific clusters to the same new cluster:

old_cluster <- c("1", "2", "3", "4","5", "6", "7", "8","9", "10", "11", "12","13", "14", "15", "16","17", "18")
new_cluster <- c("a", "a", "b", "b","c", "d", "e", "a","f", "g", "d", "h","i", "g", "i", "i","c", "j")
df <- data.frame(old_cluster, new_cluster)
sce <- mergeClusters(sce, k = "meta18", table = df, id = "merge10")

I am however unsure how to visualise these on the tSNE plot using plotDR, as I am unsure what to write in the color_by= "" argument. 

Any help would be greatly appreciated. Thanks.

**Comment by HelenaLC** [comment]
plotDR(sce, color_by=“cluster_id”, k=“merge10”) should do the trick. Have you read the function documentation? If it’s not clear from there, I’m open to feedback and improving it, thanks.

**Comment by Tregwiz** [comment]
Hi Helena,
Thanks a lot for your prompt reply.
Unfortunately that is the code I had tried previously, however it returns the following:
Error in plotDR(sce, color_by = "cluster_id", k = "merge_10") : 
length(reducedDims(x)) != 0 is not TRUE

**Comment by HelenaLC** [comment]
Well, you need to runDR() first to get the UMAP… sry, was assuming that was clear.

**Comment by Tregwiz** [comment]
Hi Helena,
Thanks for your reply.
Sorry I should have been clearer, I have previously done runDR() to generate the t-SNE, and can plot the FLOWSOM generated clusters on here using plotDR(sce, color_by = "meta18"), however when I try to plot the manually merged clusters using plotDR(sce, color_by = "cluster_id", k = "merge_10") it returns length(reducedDims(x)) != 0 is not TRUE .
Best wishes,
Gabriel

**Comment by HelenaLC** [comment]
Aha, I see, thanks for clarifying! What would really help is: could you please post the output of the following commands: `sce` and `names(cluster_codes(sce))` (right before the error occurs), thanks!

**Comment by Tregwiz** [comment]
Hi Helena,
sce returns the following: 

class: SingleCellExperiment 
dim: 15 407149 
metadata(5): experiment_info chs_by_fcs cluster_codes SOM_codes
  delta_area
assays(2): counts exprs
rownames(15): CD64 PDL1 ... CD206 CD86
rowData names(4): channel_name marker_name marker_class
  used_for_clustering
colnames: NULL
colData names(4): sample_id condition patient_id cluster_id
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):

names(cluster_codes(sce)) returns (apologies for having a few different merging names): 

[1] "som100"   "meta2"    "meta3"    "meta4"    "meta5"    "meta6"   
 [7] "meta7"    "meta8"    "meta9"    "meta10"   "meta11"   "meta12"  
[13] "meta13"   "meta14"   "meta15"   "meta16"   "meta17"   "meta18"  
[19] "meta19"   "meta20"   "merging1" "merging"  "merging2" "merge"   
[25] "merge10"

**Comment by HelenaLC** [comment]
Yes, so as you can see, the `reducedDimNames` slot is empty, meaning there are no dimensionality reductions in the object, hence the error you're getting. Here's a couple things I'd like you to do/try:
- Please post the output of your `sessionInfo()` with every issue, so we can rule out version-specific causes that might have already been resolved.
- Are you absolutely positive you ran `runDR()`? If so, can you check if there are reduced dimensions in the SCE before running `mergeClusters()`? Because if they were there and are dropped, that'd indeed be a bug.
- If none of these leads to a hint towards solving this, could you post the code you ran up to this point? Ideally only relevant parts, e.g., `prepData()`, `cluster()`, `runDR()`, `mergeClusters()` and `plotDR()` (but the full code you have in your script, I mean).

**Comment by Tregwiz** [comment]
Hi Helena,
Really sorry there was actually an error on my part previously. I had accidentally renamed my sce as tsne by running 
tsne<- runDR(sce, dr = "TSNE", cells = 2100, features ="type")

So tsne contains the dimensionality reduction rather than sce.

tsne returns:

class: SingleCellExperiment 
dim: 15 407149 
metadata(5): experiment_info chs_by_fcs cluster_codes SOM_codes delta_area
assays(2): counts exprs
rownames(15): CD64 PDL1 ... CD206 CD86
rowData names(4): channel_name marker_name marker_class used_for_clustering
colnames: NULL
colData names(4): sample_id condition patient_id cluster_id
reducedDimNames(1): TSNE
mainExpName: NULL
altExpNames(0):

names(cluster_codes(tsne)) returns:

[1] "som100"  "meta2"   "meta3"   "meta4"   "meta5"   "meta6"   "meta7"   "meta8"   "meta9"   "meta10" 
[11] "meta11"  "meta12"  "meta13"  "meta14"  "meta15"  "meta16"  "meta17"  "meta18"  "meta19"  "meta20" 
[21] "merge10"

Now running plotDR(tsne, color_by ="cluster_id", k="merge10"), it returns the tSNE plot however it plots 100 different cluster IDs, rather than the 10 (from "merge10") I was expecting:

![image](https://user-images.githubusercontent.com/118558025/203527428-af295f1a-69dc-4b7d-bf13-59d74e0fd0d6.png)

**Comment by HelenaLC** [comment]
Okay, so we're making progress. Could you post the table you used for merging? And, maybe the output of `table(clsuter_codes(tsne, "merge10"))`?

**Comment by HelenaLC** [comment]
Aha, finally got it! The plot above helped a lot, because `CATALYST` rarely uses default colors; there's a custom and consistent color palette for clusters across functions. I made a mistake earlier in that `plotDR` does not have a `k` argument (see `?plotDR`). Instead, the clustering identifier should be passed directly to `color_by`, i.e., `plotDR(sce, color_by = "merge10")` and that's it :)

**Comment by Tregwiz** [comment]
Hi Helena,
Thanks for your message. Yes this has solved it. Sorry I feel a bit silly as this was the original code line I used but with sce as x instead of tsne (which contained the dimensionality reduction). At least we got there in the end - thanks a lot for your help.
