### ISSUE TITLE
Changing data point label size on MDS plot 

### ISSUE THREAD

**Issue by Tregwiz** [HelenaLC/CATALYST#314]
Hi,
Are you aware of a way to change the size of the data point labels on the MDS plot? The default label size is too big and results in the labels not being displayed due to excess overlap. I have been able to change the font size of all of the other components on the MDS plots using the default arguments for ggplot e.g. p + font("xy.text", size = 12), however this method doesn't allow for a data point label argument.
Thanks.

**Comment by HelenaLC** [comment]
A little hacky, but setting the `size` at `.$layers[[2]]$aes_params` should do the tricky:
```
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
plt <- pbMDS(sce, by = "sample_id", features = "state")
plt$layers[[2]]$aes_params <- list(size = 1)
```
![image](https://user-images.githubusercontent.com/14542264/210414277-cbd9031e-4b21-4a60-a267-10568afbc6eb.png)
![image](https://user-images.githubusercontent.com/14542264/210414318-c1150130-e456-4d39-9c7b-7eb490f9d74f.png)
In principle, any `ggplot` can be post-modified in this way, that is, by finding and setting/overwriting the corresponding `aes_params` and/or `geom_params` of a given `layer` (comes in useful when packages create plots a certain way but do not/cannot expose arguments to control all possible aesthetics for all possible layers ;)

**Comment by Tregwiz** [comment]
Hi Helena,
Thanks ever so much - that is super helpful.
