### ISSUE TITLE
plotExprHeatmap function doesn't give output figure

### ISSUE THREAD

**Issue by juniajvs** [HelenaLC/CATALYST#317]
Hello,

First of all, thank you so much for developing CATALYST, it is a great tool for CYTOF analysis.

I have been successfully using the plotClusterHeatmap (although it is deprecated) & plotExprHeatmap in my analysis, but today I encountered an issue with them. They seem to run without a problem since I get no errors in my console, but none was able to give me a plot. 

Is there a lower bound for the total number of cells needed in order to  successfully run the function? I have about 6,500 cells on the clusters I would like to plot a heatmap.

Thank you so much!

**Comment by HelenaLC** [comment]
Hm. Could you please 1. post the output of your `sessionInfo()`; 2. assign the output of `plotExprHeatmap()` (e.g., `hm <- plotExperHeatmap(sce, ...)`) and do something like `class(hm)`, `hm@matrix`, ...; and, 3. assure there are no active graphic devices running (e.g., via `graphics.off()` and `dev.off()`). --  If none of these does the trick I'm really not sure what's going wrong.

**Comment by HelenaLC** [comment]
Closing as this seems to be resolved. Feel free to reopen/continue the discussion if not!
