### ISSUE TITLE
How to use plotClusterHeatmap for other clustering algorithms

### ISSUE THREAD

**Issue by JingAnyaSun** [HelenaLC/CATALYST#318]
Hi Helena,

Hope you are well. 
I want to use other clustering method for my CyTOF data instead of just flowSOM, is it possible to do a bit modification and use plotClusterHeatmap for plotting? If so, how do you suggest to do it? I noticed that this function is for flowSOM, as k is set to 'metaK', and I could not figure it out. Your help is highly appreciated! Thanks

Best,
Jing

**Comment by HelenaLC** [comment]
Please see the section on [Using other clustering algorithms](https://bioconductor.org/packages/release/bioc/vignettes/CATALYST/inst/doc/differential.html#using-other-clustering-algorithms) in the vignette.
