### ISSUE TITLE
Use of deprecated language

### ISSUE THREAD

**Issue by gnzacevedo** [HelenaLC/CATALYST#321]
Hello, 

Just bringing up a warning message being output when running `plotExprs()` about usage of deprecated notation in the context of ggplot:

`Warning: The dot-dot notation (`..ndensity..`) was deprecated in ggplot2 3.4.0.`
`ℹ Please use `after_stat(ndensity)` instead.`
`ℹ The deprecated feature was likely used in the CATALYST package.`

The function still works, but it's likely to start running into issues in the future. I'm using CATALYST v. 1.22.0 and ggplot2 v. 3.4.0.
Thank you for your hard work, it is much appreciated!

Gonzalo.

**Comment by HelenaLC** [comment]
Thanks for pointing this out! Warnings easily get overlooked as they don't show until one actively checks or the package fails to be built. -- should be resolved by now.
