### ISSUE TITLE
Change the cofactor used in arcsinh transformation for a selection of channels.

### ISSUE THREAD

**Issue by Stein-ErikG** [HelenaLC/CATALYST#326]
Hi, 

I have a dataset with some channels that has a weak signal. I would like to test how the data looks if i reduce the cofactor in the arcsinh transformation. I have no idea on how to do this, preferably directly on a sce that has been constructed. Alternatively, is there a way to modify this during prepData? 

Any help is greatly appreciated :)

**Comment by HelenaLC** [comment]
Please see the ?prepData documentation regarding the ‘cofactor’ parameter.
