### ISSUE TITLE
Error in GetChannels(fsom, colsToUse)

### ISSUE THREAD

**Issue by klutzzzOOyyyq** [HelenaLC/CATALYST#328]
hello , there is an error when I run cluster, I found the same error as issue 289, but it didn't solved.
when I run : sce <- cluster(sce, features = "type",+xdim = 10, ydim = 10, maxK = 20, seed = 1234)
it shows:
o running FlowSOM clustering...
Error in GetChannels(fsom, colsToUse) : 
  Marker ^\QSIRPα (CD172a)\E$ could not be found

i have checked my panel, there is SIRPα (CD172a),but I don't know why there is \Q before and \E after.
thank you very much

**Comment by SamGG** [comment]
Hi, \Q and \E are computer tags for matching marker names.
α is not the same as a
there is space after α
These slight differences could explain the error.

**Comment by klutzzzOOyyyq** [comment]
> Hi, \Q and \E are computer tags for matching marker names.
> α is not the same as a
> there is space after α
> These slight differences could explain the error.

sorry ,in my panel that is α not a, so the problem is still there ...

**Comment by HelenaLC** [comment]
Could you perhaps post your panel `data.frame` here (prior to running `prepData(...)`), and the `rowData(sce)`? This is more of a `read.FCS`/excel issue than `CATAYST`-specific, i.e., something's off with how the channel names are being read in.
