### ISSUE TITLE
tSNE contour coloured by density

### ISSUE THREAD

**Issue by PKLiverpool** [HelenaLC/CATALYST#331]
Hi there,

Really appreciating this tool and the comment forum, very very useful.

Just wondering whether there's similar functionality to cytobank in terms of colouring a tSNE plot by contour/cell density?

![image](https://user-images.githubusercontent.com/127304195/226190596-e47d00c0-cfec-449c-83cf-967fb3dbdeb6.png)

Any ideas would be much appreciated.

Cheers
Paul

**Comment by HelenaLC** [comment]
Not so much a `CATALYST`-specific question, I suppose... But just to say: No, `plotDR` does not do this. But you should be able to reproduce plots such as the ones above using `ggplot` by i) extracting a `data.frame` of the t-SNE coordinates (and, if needed, marker expression and cell metadata), and ii) using `geom_density_2d()` or `geom_density_2d_filled()`. Alternatively, there's also the [`schex`](https://www.bioconductor.org/packages/release/bioc/html/schex.html) package, which might offer an interesting way of visualising.
