### ISSUE TITLE
Merging/combining reclustered clusters into original SCE

### ISSUE THREAD

**Issue by shanh1** [HelenaLC/CATALYST#338]
Hi there,

Apologies for all the enquiries recently! Thank you for all your support thus far.

I have reclustered one of my clusters from an original SCE object (cluster 19) as it contained naive cells mixed in with other T cells and I wanted to separate it from the main SCE clusters. Upon re clustering, I can see there are sub clusters that are not naive and belong in the original SCE population. Is there any way I can take a subset of the sub clusters and combine them back into the original SCE?

Could I remove cluster 19 from my original SCE (by filterSCE()), recluster and then add the subclusters that are not naive back into the original SCE?

Thank you kindly,

Shan

**Comment by HelenaLC** [comment]
I am generally happy to help, but if you are struggling with basic R/`SingleCellExperiment` operations (also issue #337), I suggest you consolidate some online resources/tutorials to familiarize yourself with manipulating the data structures being used; or/and consulting a bioinformatician for help. GitHub issues are meant for software-related issues/bugs/feature requests, or detailed methodological inquiries, and I have to reserve my time to answer these. Qs regarding subsetting/joining data are usually answered by browsing the web yourself, and can be posted elsewhere if all fails.
