### ISSUE TITLE
Using R 3.6.3, CATALYST does not seem to let me order samples NOT by_time

### ISSUE THREAD

**Issue by lucia1106** [HelenaLC/CATALYST#343]
Hello sorry for the multiple questions!
I have created a sce using a simple md table with columns: fcs_filename, pt_id, sample_id, condition
My condition column contains: "Screening", "Treatment"
My sample_id column looks like: "Screening1", "Screening2", "Treatment1", "Treatment2"; where "Screening1" and "Treatment1" are paired samples

I am using on older version of R 3.6.3
When I try to plotCounts(sce) there is no group_by argument available, therefore the samples are not in order.
I think looking into it, it seems they could be ordered by_time.
My version of prepData also does not contain a function to specify by_time = FALSE.

Is there an easy way round to re-order my samples NOT by_time, but by sample_id or by condition (ideally I want all the screening samples together, and all the treatment samples together?)
The inability to re-order the samples in the sce by sample_id or condition is also affecting my DiffHeatmaps later in the analysis, as again all the columns are in a random order and I am struggling to re-order them to all be Screening on the left and Treatment on the right.

Many thanks!

**Comment by HelenaLC** [comment]
We are now at R 4.3, and a lot has changed/improved over the years. I can no longer change/update older package versions. Please update your software. The daFrame has been deprecated for years.
