### ISSUE TITLE
Mac ARM64 binary not available

### ISSUE THREAD

**Issue by EmD0kusha** [HelenaLC/CATALYST#345]
I am to install but not run the library on ARM64 chip Mac, a fix would be greatly appreciated

**Comment by kbruton** [comment]
Has anyone found a solution to running the library on an arm64 Mac? 

Like EmD0kusha, I am able to install CATALYST while running RStudio for the x86_64 platform, but can't load the library. 

> Error: package or namespace load failed for ‘CATALYST’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/png/libs/png.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/png/libs/png.so, 0x0006): tried: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/png/libs/png.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.2/Resources/library/png/libs/png.so' (no such file), '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/png/libs/png.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by purisuto** [comment]
I can confirm that I was able to compile from source and run on an M1 macbook pro.  There may be a few steps required to get `gcc` working properly, but it's definitely possible.  ChatGPT is probably helpful to work through the issues.
