### ISSUE TITLE
CATALYST::pbMDS produced plots with cluster cells clumped together on 1 side?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [HelenaLC/CATALYST#350]
Hi there, 

Thanks for the package. 

I performed the clustering and visualise using the code below, but as you can see the clusters are clumped together on 1 side at 0 for MDS dim.1 Is this a technical error?

Thank you for your help. 

```
CATALYST::pbMDS(F37_channelCD3CD8_fcs_data_sce, shape_by = "manualInspect_strangeFCS", size_by = T, k="meta25", by="both")
```

<img width="701" alt="Screenshot 2023-06-21 at 16 06 05" src="https://github.com/HelenaLC/CATALYST/assets/62179082/e9a36326-30e9-4bc7-a3d2-3cb36d6ac2ce">

<img width="704" alt="Screenshot 2023-06-21 at 16 06 28" src="https://github.com/HelenaLC/CATALYST/assets/62179082/12de0130-3252-46c1-acbc-a9fe68e1e950">

**Comment by HelenaLC** [comment]
I cannot answer this question, and it doesn't look like an issue on `CATALYST`s end. Basically there is one outlier (cluster 9, can't tell the shape...), which causes all other points to appear "squeezed" the 1st MDS dimension. But what's causing this / what's off with those cells will need investigation...

Issues posted on GH are meant to be related to software-related inquiries, bug reports, potential feature requests etc., and I reserve (my free) time to lend users support as best is possible. However, for help interpreting the data I suggest other platforms, or consulting with a colleague / bioinformatician, or similar.
