### ISSUE TITLE
Subset out of bounds when creating single cell experiment

### ISSUE THREAD

**Issue by Tregwiz** [HelenaLC/CATALYST#354]
Hi,
Possibly I have made a really obvious mistake but I am getting the error message in the title when I try and create my single cell experiment and I can't work out why. Here is the code and the traceback:

sce2 <- prepData(GO2, panel3, md4, features = panel3$fcs_colname, cofactor = 150)

4.
stop("Subset out of bounds", call. = FALSE)
3.
fs[match(md[[md_cols$file]], ids)]
2.
fs[match(md[[md_cols$file]], ids)]
1.
prepData(GO2, panel3, md4, features = panel3$fcs_colname, cofactor = 150)

Thanks.

**Comment by HelenaLC** [comment]
Please provide more information when posting issues, and include relevant outputs. E.g., the output of your `sessionInfo()`, `head(panel3)` and `head(md4)`, what is `GO2`, etc. It's hard to understand the issue / help when I don't know what your data looks like.

**Comment by HelenaLC** [comment]
closing due to insufficient information and inactivity.
