### ISSUE TITLE
Error when generating spillover matrix

### ISSUE THREAD

**Issue by jk33gan** [HelenaLC/CATALYST#36]
I was able to successfully upload and deconvolute my single stains but when I attempt to generate the spillover matrix, I receive the following error message: 

unused argument (isotope_list = vals$isotope_list)

I am using the CATALYST Shiny

UPDATE:
I received the following error message
Warning: Error in .local: unused argument (isotope_list = vals$isotope_list)
  83: CATALYST::plotSpillmat
  80: func
  79: origRenderFunc
  78: output$plotSpillmat
   2: runApp
   1: CATALYST::launchGUI

**Comment by jmw86069** [comment]
If I may offer a suggestion based upon issue #35, a brief recap of that thread:
* the workaround in that thread was to use the "devel" branch of this repository, then
* define `custom_isotope_list` which includes a single entry for BCKG=190.
* I then noticed some CATALYST generic functions were not yet updated to use a custom `isotope_list`.

The error you got suggests you're already using this HelenaLC/CATALYST "devel" branch,
and encountered the error related to the generic functions not using `isotope_list`. I 
forked the repository and prepared a workaround that we have been using. It adds 
`isotope_list` as an optional parameter to the rest of the generic functions as needed.

To install the "devel" branch from my forked R CATALYST repository:
```R
devtools::install_github("jmw86069/CATALYST", ref="devel");
```

Once installed, when using the CATALYST Shiny app, you need to define
`custom_isotope_list` first, then run `launchGUI()` as such:
```R
custom_isotope_list <- c(CATALYST::isotope_list, list(BCKG=190));
CATALYST::launchGUI();
```

When the Shiny app loads, you'll see a message in the bottom-right corner
"Using custom isotope list", or "Using default isotope list".

The obvious caveat is that I would recommend using the HelenaLC/CATALYST
repository once the official changes have been made.

Hope this helps!
