### ISSUE TITLE
Unable to download FCS files from Shiny post-normalization, compensation and debarcoding

### ISSUE THREAD

**Issue by jk33gan** [HelenaLC/CATALYST#37]
James' solution for my first post (i.e. issue #36) worked perfectly. Thanks James!

I have been able to successfully complete the compensation but when I go to download the compensated FCS files, my browser says that it failed and there is no file. This same issue occurs when I normalize or debarcode. However I am able to successfully download FCS files post-concatenation.

**Comment by jmw86069** [comment]
I believe we also encountered this issue, and found the problem for our
scenario as well. I had it on my to-do list to post an issue suggesting
an addition to CATALYST documentation to prevent the same from happening.

We encountered this issue when running CATALYST shiny app, trying to
export figures which are packaged as a ZIP file, which requires Windows
"Rtools" and specifically the `ZIP.exe` executable. In our case, the
environmental variable PATH did not include the `Rtools/bin` path, therefore
`ZIP.exe` was not found. Any step that places `ZIP.exe` into the `PATH` will
resolve the issue. In principle, installing "Rtools" should also have updated
the `PATH`, however my guess is that running the installation without
Windows Administrator privileges caused that step to fail.

In our case, we did not have Administrator privileges on the Windows machine,
so we could not update the `PATH` variable. Normally, that would be done in
Windows Settings. However the `PATH` can be updated within R. For the steps
below, the Rtools path is `C:/Rtools/bin`.

```R
newPath <- paste0(
   "C:/Rtools/bin",
   ":",
   Sys.getenv("PATH"));
Sys.setenv(PATH=newPath);
```

Specifically, that command adds the `Rtools/bin` entry as the first location,
prepended to the existing PATH. It does nothing fancy like checking to
make sure the location is not already there, but it shouldn't cause a
problem either way.

For ease of use, we added those lines to our user `.Rprofile` file, located
in the user Documents directory. I believe that's the first place R looks for
a `.Rprofile` file whenever starting an R session. The drawbacks to using
`.Rprofile` are that the file is hidden, and is machine-, and user-specific.
So if you use another Windows machine, you need to remember and perform the
same workaround.

Here are the proposed changes to the CATALYST documentation:

> For users running CATALYST on MS Windows machines, verify that the command
**ZIP** can be run from the command prompt.
>
> * Run "command" or "cmd" to open a command-line prompt in Windows.
> * Try to run the command:
> `ZIP`
> * If you see an error "command not found" or something to that effect,
it means your `PATH` environment variable does not include the path
to the Rtools installation.
 > * Verify the path to Rtools, which is usually `C:/Rtools/bin`
 > * Add these lines to the beginning of your R script, or to your
`.Rprofile` file, usually located in the user Documents directory.
```R
newPath <- paste0(
   "C:/Rtools/bin",
   ":",
   Sys.getenv("PATH"));
Sys.setenv(PATH=newPath);
```
> * To test within R, run this command:
```R
    system("ZIP")
```
>    * If you see an error message "command not found" or similar, it means
    the `PATH` does not include a location containing the `ZIP.exe` file.

I'm glad the other workaround helped you! I'm preparing a pull request
to send my (minor) changes back to the **HelenaLC/CATALYST** repository,
so they are included in the "official" CATALYST build from then on.

**Comment by jmw86069** [comment]
I apologize, but after running through these steps again
myself on a new Windows machine, I realize there is a typo
in the `PATH` commands. Here are the corrected R commands
I added to the `.Rprofile` file:

```R
newPath <- paste0(
   "C:\\Rtools\\bin",
   ";",
   Sys.getenv("PATH"));
Sys.setenv(PATH=newPath);
```

Note the use of `\\` backslashes, and the semicolon delimiter `;`
instead of colon `:`.

**Comment by jk33gan** [comment]
Once again, you were a huge help, thanks James!
After installing R tools as with admin privileges, we were able to successfully download the Zip generated by the compensation module.

**Comment by amerji93** [comment]
Hi,

I am facing a similar problem using the R Shiny app on Chrome on Mac. Any help is appreciated. Thank you.

**Comment by HelenaLC** [comment]
Closing this as the Shiny app is no longer supported. While we regret any inconvenience this decision might cause, we feel strongly that interactive data preprocessing (using a GUI) is inefficient, especially for evermore frequent large-scale data, and irreproducible, thereby defeating the purpose of using R in the first place. We have thus decided to focus our efforts towards maintaining and further developing the package's (non-GUI) functionality.
