### ISSUE TITLE
How to increase the default colour scheme of CATALYST?

### ISSUE THREAD

**Issue by zoqaiyum** [HelenaLC/CATALYST#371]
Hello, 

I ran an Rphenograph analysis on a subset of single cells (from a mass cytometry experiment) and obtained 33 clusters. I wanted to use the default colour scheme from CATALYST to annotate the different colours in a code like this: 

`catalystcols <- CATALYST:::.cluster_cols`

However, this gives me a character (catalystcols) containing only 30 different colour values. Is there any way to expand the default colour palette of CATALYST so that 3 more colours could be added?

Many thanks.

**Comment by SamGG** [comment]
Hi,
I think that Helena and Mark chose these colors carefully in order to achieve the best possible distinction to the eye. Finding distinct colors is not an easy task. When I need an alternative to this selection or more colors, I use [I want hue](https://medialab.github.io/iwanthue/).
HTH
