### ISSUE TITLE
Combining several SCE elements into one

### ISSUE THREAD

**Issue by MargolinGaby** [HelenaLC/CATALYST#373]
Hello Helena,
please kindly suggest the optimal way to combine several SCE objects (cell populations) into one SCE object.
I have subset 13 cell populations from original SCE object created from CYTof into 13 SCE objects. I have cleaned them.
Now I would like to combine / merge them back into one SCE object.

I tried to combine them using cbind, but got the following ERROR :
> sce3test <- cbind(sce05C_B_cells, sce05C_CD16_mDCs)
Error in FUN(X[[i]], ...) : 
  column(s) 'marker_class' in ‘mcols’ are duplicated and the data do not match 

I couldn't attach here RDS files so I zipped few of them.
[Output.zip](https://github.com/HelenaLC/CATALYST/files/13215643/Output.zip)
please advise how to solve this error or use different option.
your prompt reply is highly appreciated
Gaby

**Comment by MargolinGaby** [comment]
I assume that the error is due the difference of type and state markers in each of 13 clusters,
I'll try to redefine it to be as original

**Comment by HelenaLC** [comment]
Yeah, I think you got it - simply setting `rowData(sce)$marker_class <- NULL` on all SCEs, combining them, and resetting the slot should solve it.

**Comment by MargolinGaby** [comment]
Yes, I did it and now, I have a new error while cbind()..:

*Error in FUN(X[[i]], ...) :   column(s) 'used_for_clustering' in ‘mcols’
are duplicated and the data do not match,*
in this case shall I set  rowData(sce)$used_for_clustering <- NULL ( or
FALSE)?

thank you so much for your prompt reply

**Comment by MargolinGaby** [comment]
Dear Helena,
Can you please kindly reply to me on the open issue #374?
thank you,
Gaby
