### ISSUE TITLE
Installation of CATALYST not working

### ISSUE THREAD

**Issue by AdrienSchv** [HelenaLC/CATALYST#376]
Hello, 

I am trying to install Catalyst but unfortunately, it does not work.

I am using :

MacBookPro M1 Max Sonoma 14.1
R 4.3.2
BiocManager 1.30.22 / BioConductor 3.18

When I put : 
`devtools::install_github("HelenaLC/CATALYST", dependencies = TRUE)`

I get the following messages after processing : 

```r
ERROR: dependency ‘scater’ is not available for package ‘CATALYST’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/CATALYST’
Warning messages:
1: In i.p(...) :
  installation of package ‘flowWorkspace’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘scuttle’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘openCyto’ had non-zero exit status
4: In i.p(...) : installation of package ‘ggcyto’ had non-zero exit status
5: In i.p(...) : installation of package ‘scater’ had non-zero exit status
6: In i.p(...) :
  installation of package ‘/var/folders/5s/ysbt4brn7xv6v7gy8gdp91rw0000gn/T//RtmpP43CS4/file145826380afe0/CATALYST_1.24.0.tar.gz’ had non-zero exit status`

``` 
I tried installing each packages separately but I get the same messages and in the end, Catalyst is not installed.

Could someone help me fixing this issue ? 

Thank you very much,
Adrien Schvartz

**Comment by markrobinsonuzh** [comment]
Hi @AdrienSchv,

First, `BiocManager::install("CATALYST")` is the canonical way to install (release version of) the package. Please try that, as it is supposed to also manage the dependencies (.. of course, it may end up in the same error you see above).

It might be also worth checking this:

```
BiocManager::version()
BiocManager::valid()
```

.. for me:

```
> BiocManager::version()
[1] ‘3.18’
> BiocManager::valid()
[1] TRUE
```

Cheers, Mark

**Comment by AdrienSchv** [comment]
Hi @markrobinsonuzh 

Thank you very much for your quick reply.

```r
> BiocManager::version()
[1] ‘3.18’
> BiocManager::valid()
[1] TRUE
``` 

And as you said, `BiocManager::install("CATALYST")` returns the same message : 

```r
> BiocManager::install("CATALYST")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.2 (2023-10-31)
Installing package(s) 'CATALYST'
also installing the dependencies ‘scuttle’, ‘scater’

Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘scuttle’
Do you want to attempt to install these from sources? (Yes/no/cancel) Yes
installing the source packages ‘scuttle’, ‘scater’, ‘CATALYST’
...
ld: warning: search path '/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0' not found
ld: warning: search path '/opt/gfortran/lib' not found
ld: library 'gfortran' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [scuttle.so] Error 1
ERROR: compilation failed for package ‘scuttle’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/scuttle’
ERROR: dependency ‘scuttle’ is not available for package ‘scater’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/scater’
ERROR: dependency ‘scater’ is not available for package ‘CATALYST’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/CATALYST’

The downloaded source packages are in
	‘/private/var/folders/5s/ysbt4brn7xv6v7gy8gdp91rw0000gn/T/RtmpP43CS4/downloaded_packages’
Old packages: 'Matrix'
Update all/some/none? [a/s/n]: 
a

Warning messages:
1: In install.packages(...) :
  installation of package ‘scuttle’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘scater’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘CATALYST’ had non-zero exit status

``` 

I tried to put more messages so that I could make it easier to spot the error.

Thank you very much, 
Cheers,
Adrien

**Comment by markrobinsonuzh** [comment]
Hi @AdrienSchv,

I don't have a M1 mac, but what a colleague suggested recently to someone else who was struggling with compile errors with M1 was to:
1. install the x86 version of R even though you have an M1 mac (n.b.: both are at https://stat.ethz.ch/CRAN/bin/macosx/)
2. do a fresh install of (binary) packages on this version of R

There might be a slight performance hit for doing this .. not taking full advantage of the M1 processor .. but my same colleague tells me that he doesn't notice much.

Hope that might work.

**Comment by AdrienSchv** [comment]
Thank you very much Mark !!!!
It works !!
You can thank your colleague as well 😊

Have a VERY nice day !

Best regards,
Adrien

De : markrobinsonuzh ***@***.***>
Date : mercredi, 8 novembre 2023 à 17:24
À : HelenaLC/CATALYST ***@***.***>
Cc : AdrienSchv ***@***.***>, Mention ***@***.***>
Objet : Re: [HelenaLC/CATALYST] Installation of CATALYST not working (Issue #376)

Hi @AdrienSchv<https://github.com/AdrienSchv>,

I don't have a M1 mac, but what a colleague suggested recently to someone else who was struggling with compile errors with M1 was to:

  1.  install the x86 version of R even though you have an M1 mac (n.b.: both are at https://stat.ethz.ch/CRAN/bin/macosx/)
  2.  do a fresh install of (binary) packages on this version of R

There might be a slight performance hit for doing this .. not taking full advantage of the M1 processor .. but my same colleague tells me that he doesn't notice much.

Hope that might work.
