### ISSUE TITLE
How to identify/visualize co-expression (correlation) between markers?

### ISSUE THREAD

**Issue by WilliamMWei** [HelenaLC/CATALYST#379]
Hi,
Thank you so much for the tool. 

Could you give me some pointers on packages/functions to identify/visualize the co-expression (correlations) between markers or of one marker with every other markers?

Thank you so much for your help.

**Comment by HelenaLC** [comment]
Two things come to mind: 1) this is nothing `CATALYST`-related per se, but can be done using basic R infrastructure, e.g., pulling out the expression matrix and using a plotting library of your choice such as `ggplot2`; 2) `CATALYST` does have the `plotScatter()` function to visualize biscatter plots of expression, optionally coloring cells by metadata of interest; however, for more customized/specialized plots I'd recommend option 1).
