### ISSUE TITLE
Subset or filter out cells based on UMAP coordinates

### ISSUE THREAD

**Issue by vmkalbskopf** [HelenaLC/CATALYST#380]
Hi there

The UMAP has some small clusters with cells I would like to remove from further analyses, circled in this picture:
<img width="1593" alt="clusters_to_remove" src="https://github.com/HelenaLC/CATALYST/assets/22935643/feae5230-54b0-4afa-8639-3bdc9c9ddf9e">

Can you point me in the right direction to accomplish this?

**Comment by SamGG** [comment]
Using the x and ycoordinates of the UMAP, define boxes to exclude those regions. The red region is defined by something like:
```
in_red = x_umap > 5 & x_umap < 7 & y_umap > 7  & y_umap < 10
in_violet = up_to_you
in_blue = up_to_you
kept = !in_red & !in_violet & !in_blue
# then filter the inital sce object, somtehing like sce_filtered = sce[,kept]
```
Helena will correct my errors :-)
Hope this help.

**Comment by HelenaLC** [comment]
Agreed, the above should do the job; though I would recommend against filtering based on UMAP coordinates in any case.

**Comment by SamGG** [comment]
I mainly agree with Helena. Removing these "cells" without understanding what they represent is not scientific, in my opinion. My experience has taught me that it's always useful/important to characterize (even coarsely) what we put in the trash.
