### ISSUE TITLE
Compensation

### ISSUE THREAD

**Issue by PhillipSsekamatte** [HelenaLC/CATALYST#386]
Dear Helena, 
How would you perform compensation of flow cytometry datasets using CATALYST?

**Comment by HelenaLC** [comment]
You wouldn’t. The package was originally developed for CyTOF data. While most visualizations and analyses are applicable to FACS, the compensation is not, as it relies on single-stained beads for spillover and background signal estimation. I’d suggest looking into the florCore package instead, which is a long-standing framework for FACS analysis in R.
