### ISSUE TITLE
Is rowData and colData switched in the clustering part of the differential vignette?

### ISSUE THREAD

**Issue by Sandyna** [HelenaLC/CATALYST#387]
- `rowData`:
  - `cluster_id`: cluster ID as inferred by `r BiocStyle::Biocpkg("FlowSOM")`. One of 1, ..., K.
- `colData`:
  - `marker_class`: factor `"type"` or `"state"`. Specifyies whether a marker has been used for clustering or not, respectively.

Both in the github vignette and in the Bioconductor vignette. Example pictures from the Bioconductor vignette seem to be flipped versions of the ones I get when I follow the vignette. In the code it's the other way around, which looks to be the correct way; rowData contains used_for_clustering and colData contains cluster_id. 
Is this a mistake, or am I not understanding something correctly?

**Comment by HelenaLC** [comment]
Ugh, apologies, this is indeed a typo - as for any `SummarizedExperiment`-derived class, `SingleCellExperiment`s have rows = features and columns = parameters, here markers and cells, respectively. Thus, cell/observation metadata are `colData`, and marker/parameter metadata are `rowData`. I'll fix this with the next reasonable bug fix/version update; thank you for catching this after half a decade!

**Comment by HelenaLC** [comment]
Resolved on devel.
