### ISSUE TITLE
plotAbundances Adjusts Stacked Bar Width According to Grouping

### ISSUE THREAD

**Issue by LukaTandaric** [HelenaLC/CATALYST#388]
Dear Helena,

I would like to use plotAbundances to visualize the the overall differences in the metacluster proportions between multiple groups of samples. If I do not make `group_by` NULL, i.e. when I use this function:

```
plotAbundances(
    my_SCE,
    k = "my_metacluster_merging",
    by = "sample_id",
    group_by = "survival",
    col_clust = FALSE
    )
```

the plot comes out like this:

![image](https://github.com/HelenaLC/CATALYST/assets/115447412/adbf23d0-96df-45f7-9d92-b89744bed37c)

where each of the N groups gets one Nth of the width of the plot, resulting in the stacked bar plots in each of the groups having different widths. This gives ridiculously disproportioned graphs the more unequal the numbers of group members is, e.g.: 

![image](https://github.com/HelenaLC/CATALYST/assets/115447412/2e53a653-2f24-4904-90a9-771d97f4fa4a)

Is it possible to keep the grouping, but have all stacked bar plots have the same width? In other words, is it possible to keep the increased spacing between groups, but not make the width of the plot each group takes proportional to the number of groups?

Kind regards.
Luka

**Comment by HelenaLC** [comment]
Not very "elegant", but you could try temporarily setting `sample_id`s to `group_id`s to achieve the desired result (if I understood correctly). Minimal example below:
```
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose=FALSE)

plotAbundances(sce, 
    k="meta8", 
    by="sample_id",
    group_by="condition")
```
![image](https://github.com/HelenaLC/CATALYST/assets/14542264/2193e15d-f409-4823-a4d2-e8d83ea51bba)

```
tmp <- sce
tmp$sample_id <- tmp$condition
plotAbundances(tmp, 
    k="meta8", 
    by="sample_id",
    group_by="condition")
```
![image](https://github.com/HelenaLC/CATALYST/assets/14542264/7a56a9f4-6cda-482c-afc8-b78f8edbad27)

**Comment by LukaTandaric** [comment]
Dear Helena,

thank you for your prompt response. While your suggestion does indeed make the width of the stacked bar plots equal between groups, it does so at the cost of unifying all of the data within each group, removing insight into intra-group variability. What I am looking for is a way to keep the stacked bar of each sample separate and visible, but have all stacked bars of equal width. Something like this I threw together in MS Paint:

![image](https://github.com/HelenaLC/CATALYST/assets/115447412/d965cb36-5085-4554-8b8f-73141aa01efc)

**Comment by HelenaLC** [comment]
Aha, apologies, misunderstood the Q - so this is a purely aesthetically thing if I understand correctly. It's actually a `ggplot`-related issue; by default `facet_wrap(..., scales="free_x")`, which is used here, adjust bar widths such that each panel has the same overall width. You can overwrite the faceting as follows to achieve the desired result (`space="free"` is the key here):

```
library(ggplot2)
library(CATALYST)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose=FALSE)

sub <- filterSCE(sce, !sample_id %in% c("Ref1", "Ref3")) # subset for demo
plt <- plotAbundances(sub, k="meta8", by="sample_id", group_by="condition") 
plt + facet_grid(~ condition, scales="free_x", space="free")
```
![image](https://github.com/HelenaLC/CATALYST/assets/14542264/46794522-0720-46dd-8106-b491d99fc234)
