### ISSUE TITLE
plotClusterHeatmap

### ISSUE THREAD

**Issue by SaskiaFreytag** [HelenaLC/CATALYST#39]
Are you sure that the plotClusterHeatmap plots the clusters in the right order on the right hand side of the plot? It seems strange to me that the frequencies of supposedly highly abundant clusters are very low in all samples. But maybe I misunderstand the intention of the plot.
 
![screenshot 2018-08-07 16 53 22](https://user-images.githubusercontent.com/9170680/43759441-9cb29d7c-9a62-11e8-97f4-682e8b7e81bf.png)

**Comment by SaskiaFreytag** [comment]
This may be a better example of what I am referring too.

![screenshot 2018-08-07 17 02 58](https://user-images.githubusercontent.com/9170680/43759828-c5592e34-9a63-11e8-9e31-6ffa60dfe88f.png)

**Comment by HelenaLC** [comment]
The right-hand side heatmap shows the relative frequency of a given cluster in each sample (columns sum to 1). The purpose of this is to detect differences in relative cluster abundances b/w conditions. The absolute abundance of e.g. cluster 2 is independent of how high it's relative frequencies are in each sample. For example, cluster 9 is small (0.9% of cells), but 40% of those cells are in sample BCRXL1 and 30% in BCRXL2. Hope this clarifies things(?).

**Comment by markrobinsonuzh** [comment]
I guess it depends what version was used.  There was an earlier bug with incorrect ordering that was fixed at https://github.com/HelenaLC/CATALYST/pull/38 .. @HelenaLC was this merged into BioC release/devel?

**Comment by SaskiaFreytag** [comment]
I will download the github version and give it a try. I will let you know whether I get a different result.

**Comment by HelenaLC** [comment]
I don't think it's a bug, but maybe I'm mistaken? I just looked at the code and it makes sense to me.

**Comment by SaskiaFreytag** [comment]
So the github version gives me the right answer! Thank you. 
![screenshot 2018-08-07 17 34 51](https://user-images.githubusercontent.com/9170680/43761345-384c1b28-9a68-11e8-8bbb-603513dfc04a.png)
