### ISSUE TITLE
MDS plot

### ISSUE THREAD

**Issue by galvaresborges** [HelenaLC/CATALYST#392]
I am encountering an error when trying to generate the MDS plot on the Bodenmiller dataset, following the CyTOF workflow (https://bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html). The error message is:
```{r plot-mds, fig.cap = "MDS plot for the unstimulated (Ref) and stimulated with BCR/FcR-XL (BCRXL) samples obtained for each of the 8 healthy donors in the PBMC dataset. Calculations are based on the median (arcsinh-transformed) marker expression of 10 lineage markers and 14 functional markers across all cells measured for each sample.  Distances between samples in the plot approximate the typical change in medians. Numbers in the label names indicate patient IDs."}
pbMDS(sce, color_by = "condition", label_by = "sample_id")
```
**Error: [matrixStats (>= 1.2.0)] useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE. See also ?matrixStats::matrixStats.options**

Could someone please help me resolve this issue?

**Comment by HelenaLC** [comment]
Yeah, I believe this isn't a `CATALYST` issue as all examples and unit tests are running smoothly; closing for now, but happy to pick it up if it remains an issue.
