### ISSUE TITLE
Exporting raw expression values

### ISSUE THREAD

**Issue by kmincham** [HelenaLC/CATALYST#398]
Hello,

Thank you for a great package.

I would like to export the raw transformed marker expression values from a sce (post-clustering) for integration with a separate dataset.  I have accessed the raw "exprs" data (which i believe are the raw marker values) but i am unsure how to correctly merge this data with the metadata so i can identify each sample.

Could you please provide some guidance on this if possible (using the BRC example dataset).

Thank you.

**Comment by HelenaLC** [comment]
If I understand correctly, basic R and `SingleCellExperiment()` handling should do, e.g.:

```
es <- assay(sce, "exprs")
cd <- colData(sce)
dr <- reducedDim(sce, "UMAP")
...
df <- data.frame(t(es), cd, dr, ..., check.names=FALSE)
```

Let me know if this is what you meant or need further assistance - cheers!

**Comment by kmincham** [comment]
Thank you very much for this - it's exactly what i was trying to do.
