### ISSUE TITLE
Sample method blurb for CATALYST?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [HelenaLC/CATALYST#399]
Hi there, 

Thank you for a great package! 

The tutorial at https://bioconductor.org/packages/release/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html#data-preprocessing is very useful already, but I wonder if there might exist a sample blurb for the clustering and differential expressed protein analysis workflow for `CATALYST`?

Thank you again!

**Comment by HelenaLC** [comment]
Hey! Thanks for the compliment. Can you be a little more specific, i.e., what do you mean exactly by „blurb“? By now, there are 2 vignettes & 3 publications associated with the methodology in CATALYST

**Comment by denvercal1234GitHub** [comment]
Thank you for your response, Helena. 

I am writing my method section for my paper that uses CATALYST to cluster flow data, and I was just wondering if there is a sample description of workflow adapted for flow data that I could compare with how others who have used the package for flow data describe the different steps. 

Most publications using `CATALYST` understandably describes mass spec workflow, e.g., https://doi.org/10.1016/j.isci.2024.109882 or https://doi.org/10.1016/j.isci.2024.109032, and tbh they are quite too brief. 

I will adapt these mass spec ones for my method writeup, but just wondering.

**Comment by denvercal1234GitHub** [comment]
Thank you Helena. This is very useful!
