### ISSUE TITLE
T cell Subpopulation Percentage Showing as Zero in Differential Analysis Despite Presence in Clustering Results

### ISSUE THREAD

**Issue by TongzhenXu** [HelenaLC/CATALYST#401]
Hi! I am currently working on analyzing my SCE data, specifically focusing on the CD4+ T cell subpopulations. After clustering, my data shows five distinct subpopulations: CD4+ T naive, CD4+ Tcm, CD4+ Tem, CD4+ Temra, CD4+ Teff, and an "Other" group. However, when I proceeded to perform differential analysis on these subpopulations, I noticed an issue.

Despite having successfully identified the CD4+ Temra subpopulation during the clustering step, the subsequent differential analysis shows that the percentage of CD4+ Temra cells is zero in every sample. I am uncertain what could be causing this discrepancy, as the CD4+ Temra subpopulation was clearly present in my initial clustering results.

Could you please help me understand why the percentage of CD4+ Temra cells is being reported as zero in the differential analysis? Any insights or suggestions for troubleshooting this issue would be greatly appreciated.

Thank you for your assistance.

Best regards,
Tongzhen

![image](https://github.com/user-attachments/assets/86ae5ad9-f89c-4216-ac13-bf7c4c6ca304)

![image](https://github.com/user-attachments/assets/7c83a24a-5ecb-4d77-af8f-f2c109975226)

![image](https://github.com/user-attachments/assets/fc711718-29e1-4ca5-b10b-751f9a653263)

**Comment by HelenaLC** [comment]
This is more of an issue for diffcyt than CATALYST, these are different packages. My guess is, though, that the cluster isn’t represented across >= 2 samples per condition, so that NA p-values are being reported. You can check this via table(sce$sample_id, cluster_ids(sce, “merging1”).
