### ISSUE TITLE
NRS scores - extract values?

### ISSUE THREAD

**Issue by alb16626** [HelenaLC/CATALYST#402]
Hello, 

Thank you so much for developing this package. I'm using the plotNRS function to select the best markers to retain when designing a smaller panel for a different instrument. I'm wondering if there is a way to extract the NRS scores into a data frame so I can display this information in table format rather than a plot. Thanks!

**Comment by HelenaLC** [comment]
Sure! You can extract the data underlying any ggplot using

p <- ggplot()
df <- p$data

**Comment by alb16626** [comment]
Amazing, thank you so much!
