### ISSUE TITLE
Filtering with CATALYST

### ISSUE THREAD

**Issue by feanaros** [HelenaLC/CATALYST#407]
Dear @HelenaLC , thank you for your great package! 
I have a question for you.
I have some .fcs files already normalized with beads and debarcoded. I want to keep only CD45+ cells filtering out the others.
I followed your workflow but I didn't see any filtering step that allow to keep only specific cells. Could you suggest me a way to do it?
BEST
F.

**Comment by HelenaLC** [comment]
Try checking out `filterSCE()` (assuming you have identified a CD45+ cluster already?).

**Comment by feanaros** [comment]
Hi, thank you for your response. CD45 Is expressed everywhere, so there Is not a specific cluster. I Need It as control, removing that cells that don't express It. So I don't want tò remove a specific cluster, but I Need tò perform a sort of gating, excluding cells that are not viable and not express the marker.

**Comment by HelenaLC** [comment]
Alright. In that case I'd recommend checking out `flowWorkspace`, which supports gating. Alternatively, you could follow the `CATALYST` workflow (i.e., do unsupervised clustering); typically CD45- cells would form a separate subpopulation (say, cluster `X`), which you could remove via `filterSCE(sce, cluster_id != "X")`. See Fig. 6 in our [workflow](https://f1000research.com/articles/6-748), for example, where cluster 2 appears to be CD45-, and was annotated as "surface-" downstream.

**Comment by feanaros** [comment]
Ok, perfect. I've already found a sort of cluster that express few CD45 cells and some Foxp3. It could be the cluster I'd like to remove, because Is not specific for anything. But on the other way, i want to do a double check doing the same analysis with those cells removed "a priori". Thank you for your help!
