### ISSUE TITLE
Clustering and resulting UMAPs keep changing in every re-run of the analysis

### ISSUE THREAD

**Issue by nbahti** [HelenaLC/CATALYST#409]
Hello,

Thanks a lot for a wonderful tool.

I have a problem with reproducing the same clusters and their locations on the UMAPs in every rerun of my codes with "cluster" and "runDR" commands althout I use the same seed number for randomizations involved. I don't know if it is expected or not.  For example you can see the umaps below for the 2 runs of codes in separate times/days. For the selected meta18 clusters, UMAP structure is similar but it seems the cluster assignment of some cells are changing everytime I run "cluster" command (with the same seed = 1). Accordingly, plotExprHeatmap also give differing heatmaps (slight, but with crucial changes for us). Can you help with this issue? 

![image](https://github.com/user-attachments/assets/12a25846-0ac6-452b-a22a-f5cad5f57508)

**Comment by HelenaLC** [comment]
Yes, so... both UMAP and the clustering implemented here are stochastic algorithms. You can set the seed for random number generation in R via `set.seed(123)` (always, independent of any software package). Unfortunately, there is an internal `set.seed()` call in the clustering method itself, which is why we also pass a seed to that in `cluster()`. We explain this in our workflow [here](https://f1000research.com/articles/6-748#:~:text=be%20sensitive%20to-,random%20starts,-15.%20To%20make), also copy pasting the corresponding section here for completeness:

> [FlowSOM](https://bioconductor.org/packages/3.9/FlowSOM) output can be sensitive to random starts [15](https://f1000research.com/articles/6-748#ref-15). To make results reproducible, we first set a seed for random number generation prior to calling cluster(), and, secondly, specifcy a seed argument inside cluster(). Unfortunately, this is necessary as the ConsensusClusterPlus() function internally calls set.seed() and will, when not provided with a seed, overwrite our seed using the current system time (set.seed(as.numeric(Sys.time())))

**Comment by nbahti** [comment]
Thank you for your quick response.

Yes, I understand and I followed the instructions from your workflow. I always use set.seed() outside regardless of the cluster command's internal workings, but still it seems the results are still not the same when re-running.

**Comment by SamGG** [comment]
If the result is not robust when changing the seed, I would not bet on it.
If you trust such a result, the next step is to check if the cluster of interest makes sense using bi-parametric plots.

**Comment by HelenaLC** [comment]
I get @SamGG's point regarding results changing with different seeds indicating non-robustness. However, I am still confused as to why results would change if you're fixing the seed. Sorry to ask - but are you sure you're doing this in the corresponding code chunks, and there is no caching or similar? Never seen such significant changes with the same seed. UMAPs are the same as far as I can tell, so it's gotta be the clustering step.

**Comment by nbahti** [comment]
Here is my code snippet:

![image](https://github.com/user-attachments/assets/5c156f1c-5a87-4c78-8d17-70c01bb1d60e)


Inspired by [this](https://stackoverflow.com/questions/5696381/r-clustering-results-are-different-everytime-i-run) , I have run some testing and the clustering (and cell assignments) don't seem to change in every run:

![image](https://github.com/user-attachments/assets/b9a60207-9838-4cfa-b4e4-0bacbba1cd27)
![image](https://github.com/user-attachments/assets/d013bea9-064b-41b7-bccf-f33e0d872f0a)

**Comment by HelenaLC** [comment]
Alriight, that is good news/as it should be! Still not clear how the clusterings displayed in the two UMAPs you sent originally came about. Any clue as to what might have been done differently there? You mentioned also `plotExprHeatmap` gives slightly different results, but this wouldn't be the case if clusterings are `all.equal()` as tested above.
