### ISSUE TITLE
improperly encoded FCS file with Catalyst

### ISSUE THREAD

**Issue by PaulineMaby** [HelenaLC/CATALYST#41]
Hello,

@zbjornson suggested me to share the problem I encountered with Catalyst here.

I compensated cyTOF data with CATALYST. 
For most of my samples it worked perfectly. 
Nevertheless, for some FCS files, I obtained strange resulting FCS files, with many events at zero (as expected), but also many negative events and events with extremely high values. No more cell population could be visualized (see picture).

When I re-write the FCS files with updatePanel (on R) after running the compensation it seems to correct this problem.

Out of curiosity, I still wonder if someone has already experienced such a problem and how did they solve it?

Pauline
![capture d ecran 2018-09-17 a 16 13 45](https://user-images.githubusercontent.com/43345587/45630292-b0466980-ba98-11e8-9f51-ec3f8f54aef1.png)

**Comment by PaulineMaby** [comment]
Dear all,

PROBLEM IS SOLVED

If you ever get a similar problem as I had, I wanted to let you know that when I normalized FCS files with Matlab before running Catalyst it made catalyst work perfectly.

Pauline

**Comment by zbjornson** [comment]
That suggests that your input files were encoded incorrectly, or that they were encoded in an unusual way that flowcore's reader can't handle, and Matlab's writer fixed that. Did these come straight off of a CyTOF/Helios? If you want to upload one of the problematic FCS files here, I'm happy to take a look. You'll have to put the FCS file in a ZIP in order to upload it to GitHub.

**Comment by PaulineMaby** [comment]
It happened with FCS files coming straight off an Helios and with FCS files normalized with Fluidigm's algorithm. I cannot upload a FCS file, may I send it by email?

**Comment by zbjornson** [comment]
This was an issue with flowCore that has been fixed there. The invalid file that @PaulineMaby sent me contains `$BYTEORD|4,3,2,1|$BYTEORD|1,2,3,4|` (among other duplicate values), which explains the weird display.

Duplicate header values came up in several other contexts recently (http://cytoforum.stanford.edu/viewtopic.php?f=3&t=1089&p=3219&hilit=fcs#p3219, http://cytoforum.stanford.edu/viewtopic.php?f=3&t=565&hilit=fcs&start=20, https://github.com/JinmiaoChenLab/cytofkit/issues/41 for example).

Shameless plug: this issue can be quickly detected using our FCS file validator here: https://primitybio.github.io/fcs-validator/ (https://github.com/primitybio/fcs-validator/)

> Keyword $BYTEORD occurs 2 times. Keywords must occur exactly once. Note: this may actually reflect an unescaped delimiter preceding this keyword.
