### ISSUE TITLE
Modifying the point size in plotDR

### ISSUE THREAD

**Issue by Shuaiwei-Wang** [HelenaLC/CATALYST#414]
Hi,

I generated an UMAP picture by using 'plotDR(sce, "UMAP", color_by = "meta20", facet_by = "condition")'. 

Is it possible to modify the point size in the UMAP? I would like to use smaller size.

Thanks.

**Comment by HelenaLC** [comment]
Ui, yeah, I'm really sorry that argument isn't exposed - you can always modify post rendering via:
```
library(CATALYST)
data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce, verbose=FALSE)
sce <- runDR(sce, dr="UMAP", cells=100)

p <- plotDR(sce, color_by="meta12")
p
p$layers[[1]]$aes_params$size <- 2 # this
p
```
![image](https://github.com/user-attachments/assets/f3c8fa73-97c6-455c-86d7-1015156a2dcc)
![image](https://github.com/user-attachments/assets/5c287ea4-50ef-4515-8794-5595a18e8857)

**Comment by Shuaiwei-Wang** [comment]
Thank you so much!
