### ISSUE TITLE
error in cluster

### ISSUE THREAD

**Issue by SamWell16** [HelenaLC/CATALYST#415]
Hi 
I was trying to run "cluster" on my sce object but blocked by this error.:

Error in cluster.default(sce, xdim = 10, ydim = 10, maxK = 20, seed = 1234) : 
  only implemented for resamples objects

I would really appreciate it if you could help with that

**Comment by HelenaLC** [comment]
Could you try CATALYST::cluster()? Looks like it might be calling another function

**Comment by SamWell16** [comment]
You are always amazing me with your prompt response. That fixed the issue.

Greatly appreciated!

**Comment by HelenaLC** [comment]
Check out `filterSCE()` to exclude a specific cluster; something like `filterSCE(sce, k="meta20", cluster_id != ...)` should do the trick. Also, if you're just removing one cluster, I'd say there is no need to recluster. If, for example, you were to subset T cells or myeloids separately, then yes, one might want to recluster different subsets using different features (if the data is sufficiently high-plex to resolve higher-res. subpopulations).
