### ISSUE TITLE
GUID is not a required keyword

### ISSUE THREAD

**Issue by SamGG** [HelenaLC/CATALYST#42]
Hi,
Thanks for your package. I didn't used it yet, but I was interested in the concat function (I already wrote my own and wondering if it is worth switching to your). The GUID and ORIGINALGUID are not required by FCS 3.1 and I think the same applies to FCS 3.0. IMHO your code may break when those keywords don't exist. I noticed that all the other calls to write.FCS works on the input ile name not the GUID.
Best,
Samuel
https://github.com/HelenaLC/CATALYST/blob/1a8aff0a39be74fbb1ca7281f72ba3112d408c52/R/concatFCS.R#L38
http://www.isac-net.org/images/stories/documents/Standards/fcs3.1_normativespecification_20090813.pdf

**Comment by SamGG** [comment]
FILENAME is not required neither.
https://github.com/HelenaLC/CATALYST/blob/1a8aff0a39be74fbb1ca7281f72ba3112d408c52/R/compCytof.R#L87

I saw FCS file from Cytof without those 3 keywords.

BTW paste0 is useless at https://github.com/HelenaLC/CATALYST/blob/1a8aff0a39be74fbb1ca7281f72ba3112d408c52/R/compCytof.R#L88-L89

**Comment by HelenaLC** [comment]
Thanks sam for pointing these out- FCS files are really tricky to me... This is fixed with the next release!
