### ISSUE TITLE
Compensation with pre-acquired spillover matrix not working in Shiny

### ISSUE THREAD

**Issue by vkwoodco** [HelenaLC/CATALYST#44]
I have used the compensation tab in the Shiny app to create a spillover matrix from controls and apply this to compensate a single fcs file without problem and downloaded the resultant spillover matrix as a CSV.  I want to use this matrix to compensate further files with the 'use pre-acquired spillover matrix' option, however although the CSV loads in fine and I can see the spillover matrix, when I click compensate to apply this the uploaded fcs file it doesn't seem to work.  The button itself changes so that it is not possible to click on it again but nothing happens and there is no error message in the terminal, just constant 'Listening on http.....' message indefinitely.  

I am running CATALYST version 1.5.3.23 with the additional line 'custom_isotope_list <- c(CATALYST::isotope_list, list(BCKG=190))' before launching the GUI.  R version is 3.5.0 

Has anybody else experienced the same problem and is there anything I can do other than create the matrix again from scratch for every new file I want to compensate?  Many thanks.

**Comment by HelenaLC** [comment]
Closing this as the Shiny app is no longer supported. While we regret any inconvenience this decision might cause, we feel strongly that interactive data preprocessing (using a GUI) is inefficient, especially for evermore frequent large-scale data, and irreproducible, thereby defeating the purpose of using R in the first place. We have thus decided to focus our efforts towards maintaining and further developing the package's (non-GUI) functionality.
