### ISSUE TITLE
Regularize values issues for normCytof function

### ISSUE THREAD

**Issue by mtrussart** [HelenaLC/CATALYST#46]
Hi,
I would like some feedbacks on the normCytof function. I am getting an error on the regularise.values and I don't understand what it means (see below).
As a result I am having issue with the normalised data that I obtained, could you please help me with it? 

norm_ff1=normCytof(x=ff1, y="dvs", k=80, out_path = NULL,remove=F)
Identifying beads...
Computing normalization factors...
Warning message:
In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values

Thanks so much,
Marie

**Comment by HelenaLC** [comment]
Please let me know if this was or was not resolved by the resent fixes :)

**Comment by mtrussart** [comment]
Sorry I didn't reply to that, I just saw it, I was getting the notification to an old email address
