### ISSUE TITLE
concatFCS fails when file_num = TRUE

### ISSUE THREAD

**Issue by sellth** [HelenaLC/CATALYST#47]
When trying to concatenate a flowSet using concatFCS and file_num set to true the function fails with an error.

`Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 55, 54`

I identified this as the problematic function call: 
```
df <- data.frame(list(
            name=colnames(es),
            desc=ds,
            range=maxs,
            minRange=mins,
            maxRange=maxs-1))
```
While the actual data matrix "es" gets extended by one column (fileNum) in an earlier code segment the description vector "ds" inherits the original columns from the original flowSet input. This creates a mismatch of row numbers when trying to create the data frame.

**Comment by HelenaLC** [comment]
Thank you for bringing this to my attention! I've pushed a fix to resolve this & it should be available in both the devel and release version of `CATALYST` with the next Bioc build.
