### ISSUE TITLE
Splitting concatenated files after normalization

### ISSUE THREAD

**Issue by sarahhcarl** [HelenaLC/CATALYST#49]
Hi Helena,

I'm using CATALYST in R to apply bead normalization and then de-barcode some CyTOF samples. My samples were run in three pools of 20 barcodes each, with two pools run on one day and another on a different day. If I run them through the normalization separately, I can see a pretty significant batch effect based on the day they were acquired.

My thought to (at least partly) correct for this was to concatenate the three files first, then apply bead normalization to all of them together, then split them again and de-barcode each separately. However, I'm just not sure how to implement the splitting. I know there is a `split()` function in flowCore, but when you concatenate files using `concatFCS`, does it store a variable indicating which original file each cell came from? I haven't been able to find one. 

Thanks for your help,
Sarah

**Comment by HelenaLC** [comment]
Hi Sarah,
Two suggestions/options:

1) You could try normalising all files to one reference file. That is, using the argument `norm_to` in `normCytof()` and see how that looks like.
2) When specifying `file_num = TRUE` in `concatFCS()` an additional column storing the file numbers will be added which could then be used to split the data after normalisation.

Let me know if this makes sense and if one/both of these work, or if you have any further questions/difficulties!

Cheers,
Helena

**Comment by sarahhcarl** [comment]
Hi Helena,

Thanks a lot for the suggestions! I think the second one is exactly what I was looking for, but I might also try the first and compare.

Cheers,
Sarah

**Comment by sarahhcarl** [comment]
Hi Helena,

When I try to run `concatFCS()` with `file_num = TRUE`, I get the following error:

```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 67, 66
```

All three of my flow frames have 66 parameters. I am guessing the 67 comes from the new file number column? Any idea how to deal with this?

Cheers,
Sarah

**Comment by HelenaLC** [comment]
This was also bought up by someone else recently, thank you! It's fixed now.
