### ISSUE TITLE
plotClusterHeatmap

### ISSUE THREAD

**Issue by ShannonSzeto** [HelenaLC/CATALYST#52]
Hi, I noticed when the colname of x ( daFrame) starting with number, it will cause error while calling this line in plotClusterHeatmp:
`d <- stats::dist(med_exprs[, type_markers(x)])
`
because when generating `med_exprs` (the line before) will add "X" in the colname.
Is it possible to add "`check.names = FALSE`" in the line before?

Thanks very much,
Shannon

**Comment by HelenaLC** [comment]
Added `check.names = FALSE` there, and also a bunch of other places (anywhere where a `data.frame` includes the `exprs` matrix). Thanks for bringing this to my attention!
