### ISSUE TITLE
Issue with arcsinh transformation for flow cytometry data

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [HelenaLC/CATALYST#53]
Hi,
I am writing because I have an issue related to the transformation process.
I test the correct co-factor using Cytobank to compare to the original appearance in FlowJo. Most of the times, I have to use different co-factors (1000, 1500 or higher) for different channels and not the default value (150). I was wondering if it is possible use a different co-factor value for each channel when I create daFrame.

Thanks!

**Comment by HelenaLC** [comment]
To my knowledge, this is not "typically" done. If you are working with flow cytometry data (which I am not familiar with) I can suggest trying the following work-around:

```
# create the `daFrame`
# this will apply a acrsinh-transformation with cofactor 5
daf <- ...

# reverse transformation
exprs0 <- sinh(expos(daf)) * 5

# transform each channel with desired cofactor
cfs <- c(100, 150, 50, ...)
exprs <- sapply(seq_len(ncol(exprs0)), 
    function(i) asinh(exprs0[, i]) / cfs[i])

# replace the `daFrame`'s expression matrix 
exprs(daf) <- exprs
```

**Comment by DomenicoSkyWalker89** [comment]
thanks a lot for fast answer,
 i've tried to do this but the replase function (exprs(daf) <- es) don't replace the old matrix with the new. In daFrame using **exprs(daf)** i see the old exprs matrix yet.

**Comment by HelenaLC** [comment]
Yes, my apologies. This is because there's no replacement method `exprs<-` for the `daFrame` class. The brute-force solution is: `daf@assays$data$exprs <- ...`. This will certainly work; but be cautious, as there's no checking for neither correct number of rows and columns nor correct row and column names. So, make sure to maintain the correct expression matrix format!

**Comment by DomenicoSkyWalker89** [comment]
Thank you soooooo much.

**Comment by DomenicoSkyWalker89** [comment]
Hi @HelenaLC ,
thanks for your great job.
I would just ask you if in the next version of CATALYST will be possible change the value of single cofactors using an integrated function?

Thanks.

**Comment by HelenaLC** [comment]
Yes, this will be possible with the next release directly with the `prepData` function! I'm in the process of finalizing the next release; the official release day for Bioc 3.11 (and R 4.0 around the same time) is April 24th!

**Comment by DomenicoSkyWalker89** [comment]
Great!!

**Comment by DomenicoSkyWalker89** [comment]
Hi Helena,
i installed the new CATALYST version as you suggested.

After the creation of sce object i noticed that 2 markers that i would use (IgM, IgD) weren't present in the sce. I saw them in the slot sce@int_colData@listData.
Any suggestion about this issue?

![image](https://user-images.githubusercontent.com/53559811/83891984-48452480-a74e-11ea-8e2e-8a7400adf281.png)

![image](https://user-images.githubusercontent.com/53559811/83892113-77f42c80-a74e-11ea-94d2-b3a7891bb53c.png)


thanks,
Domenico

**Comment by HelenaLC** [comment]
Setting 

for (i in seq_along(fs)) 
    keyword(ff[[i]], “$CYT”) <- “FACS”

should resolve this.

**Comment by DomenicoSkyWalker89** [comment]
Sorry but does not work.

**Comment by DomenicoSkyWalker89** [comment]
Hi Helena,
you think that the problem is due by the keyword $CYT that specify the name of cytometer?

Thanks,
Domenico

**Comment by HelenaLC** [comment]
Yes, see also #103

**Comment by DomenicoSkyWalker89** [comment]
Ok now i understand!
You are always the best, thanks a lot.

Domenico
