### ISSUE TITLE
SCE no longer has an explicit reducedDim slot in Bioc-devel

### ISSUE THREAD

**Issue by LTLA** [HelenaLC/CATALYST#54]
This means that any `@reducedDims` call will fail for `daFrame`'s overridden `reducedDim()` getters and setters, because no such slot exists anymore in the class definition.

The proper approach is to use the getters/setters exported by _SingleCellExperiment_ via `callNextMethod()`, which are guaranteed to work (or at least give advance notice when they change). Downstream packages and code should never be accessing slots of an upstream class.

I don't even see why you need to override the default getters. Just let samples be columns - as they should be, for any SE subclass - and everything will work fine. If you must have samples in the rows, then you probably shouldn't be using an SE in the first place.

**Comment by bioguy2018** [comment]
Hello, I have encountered an issue during running the function runDR() which I guess due to the same problem! 
When I run the function it can not find reducedDims and returns me with:
Error in reducedDimNames(x) : no slot of name "reducedDims" for this object of class "daFrame"

Is there a temporary fix for it or should I downgrade my package?

**Comment by HelenaLC** [comment]
Thanks Aaron,
I agree 100% with having samples as columns. The reason for the whole mess of overwriting accessors and wrapping scater functionality was that, to my knowledge, all cyto data is stored in reveres dimensions... 
Looking back, I realize that the current setup is not sustainable, unstable, and also a pain(!) from a developers point of view. 
I have come to the (I think reasonable) decision to use the SCE class, expecting that the cyto community is smart enough to work with having columns = samples. That fix should only take a day or so of work, and remove loads of superfluous functions.

**Comment by SamGG** [comment]
Sorry to come in the discussion, but I heard "community" and felt "involved".
The classical storage of cyto data is transposed with regards to the SingleCellExperiment class. I don't think a transposition is a big deal for the community.
What is not so clear to me is to define what a sample is. For cytometry, a sample is set of cells. In the SCE class definition, a column is a cell. What Id didn't get yet is how should I represent a bench experiment made of dozen of biological samples which consist in thousands of cells themselves?

**Comment by HelenaLC** [comment]
Closing this; CATALYST 1.9.8+ / Bioc 3.10 resolves this by removing the `daFrame` class and replacing it with a classical `SingleCellExperiment`.

**Comment by SamGG** [comment]
Nice. I will give a try in the next weeks.
