### ISSUE TITLE
daFrame not working

### ISSUE THREAD

**Issue by vivek-verma202** [HelenaLC/CATALYST#59]
Hi Helena!

I am trying to use the workflow as described at: https://f1000research.com/articles/6-748 for flow cytometry data. This requires creating daFrame, however:

> daf <- daFrame(fs, panel, md, cols_to_use = panel$fcs_colname, cofactor = 150)
Error in .local(x, panel, md, ...) : 
  all(ids %in% md[[md_cols$file]]) is not TRUE

***I have cross checked to make sure that the file names listed in the md$file_name column matches those in the flowSet***

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] DT_0.8                    magrittr_1.5              plotly_4.9.0             
 [4] htmltools_0.3.6           gridExtra_2.3             ggplot2_3.2.1            
 [7] shinyBS_0.61              shinyjs_1.0               shinydashboard_0.7.1     
[10] shiny_1.3.2               CATALYST_1.8.6            readxl_1.3.1             
[13] openCyto_1.22.2           flowWorkspace_3.32.0      ncdfFlow_2.30.1          
[16] BH_1.69.0-1               RcppArmadillo_0.9.700.2.0 flowCore_1.50.0          
[19] devtools_2.2.0            usethis_1.5.1            

Thank a lot!
Vivek
PhD - candidate (McGill University)

**Comment by bioguy2018** [comment]
Hi,
You have to really make sure that the filenames that you have in the md are really matching with the filenames that flowset read. 
to check the file names you can use the below code
keyword(flowset, "FILENAME")

**Comment by mamchaye** [comment]
Hello,
I unfortunately have the exact same problem, checked multiple times that the filenames were matching, and keyword(flowset, "FILENAME") (adapted to my data of course) gives me the right filenames, but with a "NULL" below, is it normal (still very new at all this, sorry if the question is stupid)?
If that's not the problem, any idea what else could be wrong?

Thanks for your help!

**Comment by HelenaLC** [comment]
The `daFrame` does the following:
```
ids <- c(keyword(fs, "FILENAME"))
        if (is.null(unlist(ids)))
            ids <- c(fsApply(fs, identifier))
``` 
i.e., when `FILENAME`s are unspecified, the `identifier`s are checked. Then
```
stopifnot(all(ids %in% md[[md_cols$file]]))
```
If your "NULL" is a NULL, this will not raise an error. If it is a character, i.e. your console prints "NULL", it will cause an error. E.g.,
```
stopifnot(all( NULL  %in% "x")) # silent
stopifnot(all("NULL" %in% "x")) # error
```
If this indeed the issue, you could quite simply replace your `flowSet` filenames or identifiers accordingly, e.g.
```
# provided that the sample order in the metadata table 
# is identical to the sample order in the `flowSet`:
for (i in seq_along(fs))
  identifier(fs[[i]]) <- metadatat$file_name[i]
```

**Comment by brentocarrigan** [comment]
Just to add a comment: I was having the same fault and one issue was that the filenames were a character vector list of identifiers `fsApply(flowSet, identifier)` but a factor in the metadata table `md$file_name` - possibly coerced by the notorious `stringsAsFactors` argument when importing a csv `read.csv`. 

Ensuring they were both character vectors, not factors, fixed that bug for me.

**Comment by louiskatorze** [comment]
Hej,
I am having a similar problem like in the first post of the thread when I run the prepData function: 
`sce <- prepData(fs,panel,md)`
It returns: **all(ids %in% md[[md_cols$file]]) is not TRUE**
There is no eror  if I exclude the md file.
I am running newest R 4.0.2 and all packages are updated. I have succesfully tried the Bodenmiller_BCR_XL_flowSet data set from HDCytoData package but my own data does not work. I have 6 fcs files exported from FlowJo. I have basically prepared the md and panel files according to the example data with "file_name" "sample_id" etc.

I have also checked that all the names are the same but I guess the error is before that anyway:
`keyword(fs,"FILENAME")
fsApply(fs, identifier) 
md$file_name`

I am quite new to these packages so I don't know what to do anymore. Is there maybe a work around?

Here is my code:
#read panel with isotope/marker
`md <- "metadata_samples.xlsx"`
`md <- read.xlsx(md,1,stringsAsFactors=FALSE)`
`head(data.frame(md))`

#read in metat data for panel
`panel <- "panel.xlsx"`
`panel <- read.xlsx(panel,1,stringsAsFactors=FALSE)`
`head(data.frame(panel))`

#get a vector of file names from metadata file
`file.names <- dplyr::pull(md,var=1)`

`fs <-read.flowSet(file.names,path=".",truncate_max_range = FALSE,transformation=FALSE)`

#check if all column names from panel are in the facs files
`all(panel$fcs_colname %in% colnames(fs))`

#create sce
`md_cols = list(`
  `file = "file_name", `
 ` id = "sample_id",factors = c("patient","tissue"))`

`panel_cols = list(channel = "fcs_colname", `
                  `antigen = "antigen", class = "marker_class")`
`sce <- prepData(fs,panel,md)`

best, Louis

**Comment by HelenaLC** [comment]
This is being discussed at #129.
