### ISSUE TITLE
Could not find function "daFrame"

### ISSUE THREAD

**Issue by JimboMahoney** [HelenaLC/CATALYST#62]
Hi there!

I followed the workflow from the Robinson paper before they implemented the changes.

I'm now trying with the new V3 code and falling at the first hurdle. Whilst I've come across this problem (of not being able to find a function) before, I cannot solve this one.

Essentially, it seems like the CATALYST package is installed, yet the daFrame() function still cannot be found for some reason.

Here's the initial output from my `sessionInfo()`

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] CATALYST_1.9.8

In case you need it, here is the rest:

> loaded via a namespace (and not attached):
>   [1] readxl_1.3.1                backports_1.1.5             circlize_0.4.8              drc_3.0-1                  
>   [5] plyr_1.8.4                  igraph_1.2.4.1              ConsensusClusterPlus_1.49.0 lazyeval_0.2.2             
>   [9] shinydashboard_0.7.1        splines_3.6.1               flowCore_1.51.7             BiocParallel_1.19.1        
>  [13] fda_2.4.8                   GenomeInfoDb_1.21.2         ggplot2_3.2.1               TH.data_1.0-10             
>  [17] digest_0.6.21               htmltools_0.4.0             magrittr_1.5                CytoML_1.11.9              
>  [21] cluster_2.1.0               ks_1.11.5                   openxlsx_4.1.0.1            limma_3.41.17              
>  [25] ComplexHeatmap_2.1.0        RcppParallel_4.4.4          matrixStats_0.55.0          R.utils_2.9.0              
>  [29] sandwich_2.5-1              flowWorkspace_3.33.9        colorspace_1.4-1            rrcov_1.4-7                
>  [33] ggrepel_0.8.1               haven_2.1.1                 dplyr_0.8.3                 crayon_1.3.4               
>  [37] RCurl_1.95-4.12             jsonlite_1.6                hexbin_1.27.3               graph_1.63.0               
>  [41] zeallot_0.1.0               survival_2.44-1.1           zoo_1.8-6                   glue_1.3.1                 
>  [45] flowClust_3.23.0            gtable_0.3.0                nnls_1.4                    zlibbioc_1.31.0            
>  [49] XVector_0.25.0              GetoptLong_0.1.7            DelayedArray_0.11.8         ggcyto_1.13.2              
>  [53] car_3.0-3                   IDPmisc_1.1.19              Rgraphviz_2.29.0            shape_1.4.4                
>  [57] SingleCellExperiment_1.7.11 BiocGenerics_0.31.6         DEoptimR_1.0-8              abind_1.4-5                
>  [61] scales_1.0.0                mvtnorm_1.0-11              Rcpp_1.0.2                  plotrix_3.7-6              
>  [65] xtable_1.8-4                viridisLite_0.3.0           clue_0.3-57                 openCyto_1.23.5            
>  [69] foreign_0.8-72              mclust_5.4.5                FlowSOM_1.17.3              stats4_3.6.1               
>  [73] tsne_0.1-3                  DT_0.9                      httr_1.4.1                  htmlwidgets_1.5.1          
>  [77] RColorBrewer_1.1-2          pkgconfig_2.0.3             XML_3.98-1.20               R.methodsS3_1.7.1          
>  [81] flowViz_1.49.3              reshape2_1.4.3              flowStats_3.43.8            tidyselect_0.2.5           
>  [85] rlang_0.4.0                 later_1.0.0                 munsell_0.5.0               cellranger_1.1.0           
>  [89] tools_3.6.1                 ggridges_0.5.1              shinyBS_0.61                stringr_1.4.0              
>  [93] yaml_2.2.0                  zip_2.0.4                   robustbase_0.93-5           purrr_0.3.2                
>  [97] RBGL_1.61.0                 mime_0.7                    R.oo_1.22.0                 compiler_3.6.1             
> [101] rstudioapi_0.10             plotly_4.9.0                curl_4.2                    png_0.1-7                  
> [105] tibble_2.1.3                pcaPP_1.9-73                stringi_1.4.3               forcats_0.4.0              
> [109] lattice_0.20-38             Matrix_1.2-17               shinyjs_1.0                 vctrs_0.2.0                
> [113] lifecycle_0.1.0             pillar_1.4.2                GlobalOptions_0.1.1         data.table_1.12.4          
> [117] cowplot_1.0.0               bitops_1.0-6                corpcor_1.6.9               httpuv_1.5.2               
> [121] GenomicRanges_1.37.16       R6_2.4.0                    latticeExtra_0.6-28         promises_1.1.0             
> [125] KernSmooth_2.23-15          gridExtra_2.3               rio_0.5.16                  IRanges_2.19.16            
> [129] codetools_0.2-16            MASS_7.3-51.4               gtools_3.8.1                assertthat_0.2.1           
> [133] SummarizedExperiment_1.15.9 rjson_0.2.20                mnormt_1.5-5                multcomp_1.4-10            
> [137] S4Vectors_0.23.25           GenomeInfoDbData_1.2.1      parallel_3.6.1              hms_0.5.1                  
> [141] ncdfFlow_2.31.3             grid_3.6.1                  tidyr_1.0.0                 carData_3.0-2              
> [145] Rtsne_0.15                  shiny_1.3.2                 Biobase_2.45.1              base64enc_0.1-3            
> [149] ellipse_0.4.1  

Please let me know if you can tell what's wrong or you need more information.

Thanks!

**Comment by HelenaLC** [comment]
If you have a look at the package vignette, the `daFrame` class has been replaced by a classical `SingleCellExperiment` (SCE). Thus, the `daFrame` constructor function has been removed. Instead, you can prep a SCE from your `flowSet`, panel, and metadata table using the `prepData` function. [Otherwise, all functions still exist, but some function argument names may have changed.]
