### ISSUE TITLE
plotDR and facet_wrap

### ISSUE THREAD

**Issue by JimboMahoney** [HelenaLC/CATALYST#66]
Hi there!

I'm trying to recreate the workflow from the [V3 CyTOF paper](https://f1000research.com/articles/6-748).

I've had to make numerous changes to the code to get it to work so far, but I'm stumped with facet_wrap with plotDR.

The paper has this:

`plotDR(daf, "UMAP", color_by = "meta20", facet = "sample_id")`

And I've changed it to this, which at least executes without an error:

```
plotDR(daf3, color_by = "meta20") +
  facet_wrap("sample_id",ncol = 4)
```

However, the output only seems to be one sample - BCRXL1.

Any ideas what I'm doing wrong?

If it makes a difference (and it might!), the daf3, which is produced from either runTSNE or runUMAP (from scater package) is itself created by my own method of subsampling the original data (to get realistic / fast DR runtimes).

e.g. the method from the V3 paper:

`daf <- runDR(daf, "UMAP", rows_to_use = 1000)`

No longer works, so I'm using my own workaround:

```
# Get lowest number of cells
MinCellNumber <- min(daf@metadata$experiment_info$n_cells)

# Generate Random Cells list up to 10,000 but no larger than smallest dataset
RandomCells <- sample(1:MinCellNumber,min(MinCellNumber,10000))

#tSNE
daf3 <- runTSNE(daf[,RandomCells],exprs_values = "exprs")
```

daf3 is thus the dataset I'm trying to facet_wrap.

Thanks for any advice!

**Comment by HelenaLC** [comment]
The issue is as follows: 
Let's say the smallest sample has 250 cells, i.e., `MinCellNumber = 250`.
Then, `sample(1:MinCellNumber, min(MinCellNumber,10000))` samples `min(MinCellNumber,10000)) = 250` cells from `1:MinCellNumber`, which is 1, 2, ..., 250. Thus, you are only sampling from the first 250 cells, which are the `BCRXL1` sample only.

Sample-wise sampling inside `plotDR` is implemented as:
```
# split cells by sample
cells_by_sample <- split(seq_len(ncol(daf)), rowData(daf)$sample_id)

# for each sample, sample min(Ni, N_max) cells, where Ni = # of cells in sample i
N_max = 1000
cells_to_use <- sapply(cells_by_sample, function(cs) {
    Ni <- length(cs)
    sample(cs, min(Ni, N_max))
})
```

I doubt the sampling is causing any runtime issues. If anything, I would recommend to go down to less cells.

PS: Also note the recent Bioc 3.10 release where the `daFrame` classes has been replaced by a classical `SingleCellExperiment`, which facilitate many many things & allow for better interaction with Bioc infrastructure, e.g., `scater` :)

**Comment by JimboMahoney** [comment]
Thanks Helena!

That makes sense.

Splitting cells by sample isn't working though - it looks like my daFrame doesn't have the sample_id column?

`rowData(daf)$sample_id`

> NULL

`rowData(daf)`

> 
> DataFrame with 24 rows and 3 columns
>           channel_name marker_name marker_class
>            <character> <character>     <factor>
> CD3     CD3(110:114)Dd         CD3         type
> CD45     CD45(In115)Dd        CD45         type
> pNFkB   pNFkB(Nd142)Dd       pNFkB        state
> pp38     pp38(Nd144)Dd        pp38        state
> CD4       CD4(Nd145)Dd         CD4         type
> ...                ...         ...          ...
> pLat     pLat(Er170)Dd        pLat        state
> IgM       IgM(Yb171)Dd         IgM         type
> pS6       pS6(Yb172)Dd         pS6        state
> HLA_DR HLA-DR(Yb174)Dd      HLA_DR         type
> CD7       CD7(Yb176)Dd         CD7         type

Here is how I constructed it:

`daf <- prepData(fs, panel, md) `

**Comment by HelenaLC** [comment]
Okay, I guess I was confused with your code from above where you had `daf` as a variable name. It looks like you are using the newer version of CATALYST, where the `daFrame` has been replaced by a `SingleCellExperiment`. Consequently, now rows = markers and columns = cells; the sample IDs will then be in the `colData`, i.e., `colData(sce)$sample_id` or simply `sce$sample_id`

Please check the following:
```
installed.packages()["CATALYST","Version"] # is this 1.10 ?
sce <- prepData(fs, panel, md)
class(sce) # is this a `SingleCellExperiment`?
```
If so, then adjust the above accordingly:
```
# split cells by sample
cells_by_sample <- split(seq_len(ncol(sce)), colData(sce)$sample_id)
```

However, note that this is **exactly** what `runDR`/`plotDR` do already. So you could simply use `runDR(sce, dr = "UMAP", cells = 500, features = type_markers(sce))` to run the dim. red. on max. 500 cells per sample using the type markers only.

**Comment by JimboMahoney** [comment]
Hi Helena,

Many thanks!

Yes, I was using the new SCE and had also noticed the dimension flip!

Thanks for your advice on runDR - that has worked as has facet_wrap now that the samples are subsampled properly!

Please feel free to close this.
