### ISSUE TITLE
Problems using `runDR` with UMAP

### ISSUE THREAD

**Issue by sameetmehta** [HelenaLC/CATALYST#69]
Hi,
I keep getting error 

        Error in (function (X, n_neighbors = 15, n_components = 2, metric = "euclidean",  :
          unused argument (subset_row = c("CD45", "CD1d", "CD19", "CD127", "CD69", "CD16", "CD8a", 
        "CD11c", "IL.17A", "CD66a", "CD86", "CD123", "TNFa", "TIM.3", "TIGIT", "CD279", "CD183", 
        "Anti.pStat3", "GM.CSF", "CD14", "CD80", "FoxP3", "CD56", "CD45RO", "IFNg", "IL.10", "CD27", 
        "CD154", "CD25", "CD3", "CD185", "CD15", "IL.8", "HLA.DR", "CD184", "CD4", "CD11b"))

When I checked the code in `scater::runUMAP`, it seems that there is no `subset_row`, but there is a `feature_set`.  I think that is where the error is coming from.  Can you please let me know if it fixes the error.

Sameet

**Comment by HelenaLC** [comment]
When I check `?scater::runUMAP` it is `subset_row`. What version of `scater` / Bioconductor are you running? I suggest running `BiocManager::install(version = "3.10")` to make sure all is up to date.

**Comment by sameetmehta** [comment]
Hi,

Yes, please close the issue, I was using one version earlier.  After getting the latest version, it works.

Thank you for writing an excellent piece of software.

Best,
