### ISSUE TITLE
Saving plotYields output when plotly=FALSE

### ISSUE THREAD

**Issue by sarahhcarl** [HelenaLC/CATALYST#72]
Hi Helena,

I'm trying to use CATALYST in an automated pipeline to process FCS files, and I came across a problem with the `plotYields()` function. I would like to specify where to save the plots using the `out_path` parameter, and I am running it with `plotly=FALSE`, since I just want to generate static images. However, when I try to run it I get the following error:

```
> plotYields(x=re, which=c(0), out_path="/home/common/data/example_data", plotly=FALSE)
Error in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'
```

If I set `plotly=TRUE` then it generates a .html file in the correct directory, but that file appears to be empty.

Ideally I would love to be able to save the plots simply as .png or .pdf, as with the plots generated by the `normCytof()` function.

Thanks for the help!
Best,
Sarah

**Comment by HelenaLC** [comment]
Before I look into this, could you quickly tell me which version of CATALYST you are using? Thanks!

**Comment by sarahhcarl** [comment]
Sure, it's 1.8.6 I see that's not the most recent version, so I will update it. Do you know if this has been fixed in the latest version?

**Comment by sarahhcarl** [comment]
Just to confirm, I get the same issue with CATALYST version 1.10.0.

Cheers,
Sarah

**Comment by HelenaLC** [comment]
Thanks Sarah, this was indeed a bug. Basically, `plotly = FALSE` was using `save_html()` and .html as a file extension. Now, when `plotly = FALSE`, the plots are stored via `pdf()...dev.off()` with .pdf extension. 

I just pushed this fix, so it may take a couple days to build on the Bioc server. For an immediate update, please use `devtools::install_github("HelenaLC/CATALYST", ref = "RELEASE_3_10")`. 

*Closing this issue now but feel free to reopen it should the issue persist.
