### ISSUE TITLE
plotClusterHeatmap issue with median values of the second heatmap of hm2 of specific markers

### ISSUE THREAD

**Issue by mtrussart** [HelenaLC/CATALYST#75]
HI,

I am having some troubles understanding the median values of the second heatmap using the plotClusterHeatmap function when plotting hm2 for a specific marker using the code below:
`plotClusterHeatmap(daf, hm2 = "pERK", k = "meta20", draw_freqs = TRUE,fun="mean")`

I show you attached an example with a higher median value for the marker "pERK" for the specific cluster 16 for the sample "Tr110_3086".

<img width="785" alt="Screen Shot 2019-11-28 at 4 35 04 pm" src="https://user-images.githubusercontent.com/13964902/69779980-087d0d80-11fe-11ea-9073-b1fb600f581f.png">

When I compute aside the mean "pERK" values across two samples Tr110_3086 and Tr110_3091 for the same marker, the highest value isn't the one from the sample Tr110_3086, they do not correspond the heatmap plot.  See the code below to compute it:

`tmp110_3086=daf[sample_ids(daf)%in%c("Tr110_3086"),]
tt=tmp110_3086[cluster_ids(tmp110_3086)==16,'pERK']
mean(exprs(tt))`

mean(exprs(tt))
[1] 0.1606875

`tmp110_3091=daf[sample_ids(daf)%in%c("Tr110_3091"),]
tt2=tmp110_3091[cluster_ids(tmp110_3091)==16,'pERK']
mean(exprs(tt2))`

mean(exprs(tt2))
[1] 0.1724135

Could you please help me with that? Here below is the entire code:

<img width="712" alt="Screen Shot 2019-11-28 at 4 35 51 pm" src="https://user-images.githubusercontent.com/13964902/69779795-55141900-11fd-11ea-86c5-56ba719f1450.png">

Cheers
Marie

**Comment by HelenaLC** [comment]
Shown are not the ‘raw’ means, but scaled means using 5/95%-quantiles as boundaries to make the values easier to compare. Eg, if 1 mean were 10 and all others 0.1, the heatmap would be all blue except for 1 darkred bin. 
To plot the raw means nevertheless, use scale=FALSE.

**Comment by mtrussart** [comment]
Hi Helena,
My problem is not the actual values but the fact that there is a "red square" on the heatmap for pERK, suggesting that the highest mean value for cluster 16 is for the sample "Tr110_3086". However when I compute the corresponding mean values for this sample "Tr110_3086" and another sample "Tr110_3091", it doesn't match, it's not in fact the highest mean value. 
Does that make sense?

**Comment by HelenaLC** [comment]
Out of curiosity- could you post the plot with scale=FALSE, fun=“mean”?

**Comment by mtrussart** [comment]
Yes of course, here is the plot with 
`plotClusterHeatmap(daf, hm2 = "pERK", k = "meta20", draw_freqs = TRUE,fun="mean",scale=FALSE)`

<img width="876" alt="Screen Shot 2019-11-30 at 3 18 44 pm" src="https://user-images.githubusercontent.com/13964902/69895493-e1047d00-1384-11ea-9762-9a76effcc229.png">

**Comment by HelenaLC** [comment]
Hey Marie, stupid me, I had an aha moment on the airplane ;) Here's the issue:
`cluster_ids()` accesses the `colData()$cluster_id` column by default, which contains the 100 clusters from `FlowSOM`. The heatmap, however, is on the 20 metaclusters - cluster ID 16 here does not equal cluster ID 16 in the 100 SOM clusters. 
If you recompute the above means using `cluster_ids(daf, k = "meta20")` you should obtain the same result as in the heatmap (I hope)!

**Comment by mtrussart** [comment]
HI Helena,
That's great I did it now and it's working well. Thanks so much for your help and your aha moment!
See you soon at BioCAsia!
