### ISSUE TITLE
plotNRS issue, Error in svd

### ISSUE THREAD

**Issue by Sheseira** [HelenaLC/CATALYST#77]
Hi, 

I managed to define my SingleCellExperiment, however now when executing plotNRS I get the following error message:

`Error in svd(x, nu = 0, nv = k) : infinite or missing values in 'x'`

I'm not sure however at what point svd is called and if there is anyway to bypass the function resulting in the beforementioned error.

**Comment by HelenaLC** [comment]
Apologies for the 2 month late response... Unfortunately, without a minimal reproducible example or any data I can neither reproduce or fix this error. Would you be able to share an RDS object and a few lines of code that lead up to this error message? Thanks.

**Comment by HelenaLC** [comment]
This same error has been brought to my attention by another user including a reproducible example- this is fixed with the upcoming release.

**Comment by Sheseira** [comment]
Thankyou for your reply.

I have another question. I was wondering the following. I did make a MDS
plot, but i would like to know what is actually on the axis?
What are the separating factors? Or how can I find out what the dominant
separating factor is?

Thankyou in advance.

Sheseira

**Comment by HelenaLC** [comment]
Dear Sheseira, I don’t think this type of information is returned for MDS plots (could be wrong)... however, it is included for PCA. So, you could 1) aggregate the data yourself (there’s also a hidden function CATALYST:::.agg() that you could try) and 2) run prcomp()- this will return a 2d embedding (x & y coords similar to mds) and the loadings in each dimension. There’s lots of details on PC loadings online!
