### ISSUE TITLE
[shiny normalizer] Warning: Error in arrangeGrob: argument "p2" is missing, with no default

### ISSUE THREAD

**Issue by esimonds** [HelenaLC/CATALYST#78]
Thanks for the great work on the CATALYST package. I encountered an error in the shiny GUI normalizer on my system:

```> launchGUI()
Loading required package: shiny

Attaching package: ‘shinydashboard’

The following object is masked from ‘package:graphics’:

    box

Need shinyjs help? You can ask any Shiny-related question in the RStudio Community forums:
	https://community.rstudio.com/c/shiny

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following object is masked from ‘package:flowCore’:

    show

The following objects are masked from ‘package:methods’:

    removeClass, show


Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:flowCore’:

    filter

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout


Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable


Listening on http://127.0.0.1:5073
Warning: Error in arrangeGrob: argument "p2" is missing, with no default
  189: arrangeGrob
  188: CATALYST:::.arrangeSmoothed
  187: <reactive:smoothedBeads> [server-normalization.R#375]
  185: .func
  182: contextFunc
  181: env$runWith
  174: ctx$run
  173: self$.updateValue
  171: smoothedBeads
  168: renderPlot
  166: func
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$plot_smoothedBeads
    2: runApp
    1: launchGUI
```

This error occurs after gating and pressing "Apply" and the browser does not create the line plots showing un-smoothed vs. smoothed data. However, it does proceed with showing the Mahalanobis distance plots.

I used a small (115MB) FCS file for testing and uploaded the same file to http://imlspenticton.uzh.ch:3838/CATALYSTLite/ . On the UZH server, I did not get the error, so this may be due to my specific package or OS versions. I've attached sessionInfo() as a txt file here:

[sessionInfo.txt](https://github.com/HelenaLC/CATALYST/files/4089532/sessionInfo.txt)

I've isolated the error to line 375 in server-normalization.R, which calls the .arrangeSmoothed function without properly defining the arguments to the function. I'll try to submit a pull request fixing the bug.

Original code (v1.11.0 from GitHub):
`
CATALYST:::.arrangeSmoothed(p1, p2, shiny=TRUE)"
`
New proposed code:
`
CATALYST:::.arrangeSmoothed(p1=p1, p2=p2, shiny=TRUE) # fix bug "Warning: Error in arrangeGrob: argument "p2" is missing, with no default"
`

**Comment by esimonds** [comment]
Pull request added:
#79

**Comment by arnaudmgh** [comment]
> Closing this as the Shiny app is no longer supported. 

I recommend updating https://catalyst-project.github.io/, which still references the launchGUI function, and gives an error when the function is called.
