### ISSUE TITLE
Differential Expression Testing Between Clusters [REQ]

### ISSUE THREAD

**Issue by grhogg** [HelenaLC/CATALYST#83]
Hello, 

I apologize for flooding you with questions! I was wondering if there was an implementation for testing differential expression of markers between clusters as opposed to between conditions. Say I want to compare the median marker expression of cluster 7 to the average of all the other clusters combined and test for significance. Or if I wanted to compare median marker expression of cluster 7 and compare it to just the average median marker expression of cluster 8 and 9 and test for significance.

Thank you so much for your help!

**Comment by SamGG** [comment]
While Helena will bring you a clear answer, testing one clusters vs all others is published as MEM
https://my.vanderbilt.edu/irishlab/2019/06/marker-enrichment-modeling-mem-v3-on-github/

**Comment by HelenaLC** [comment]
No worries about "flooding" us with questions- I appreciate they are posted on GitHub, and not sent via email. So thanks for that!
Following Mark's suggestion, here's a minimal example of how you can use `scran`'s `findMarkers` function to do this. I recommend checking out the function's documentation if you want more details! E.g., you can also easily test for markers in each cluster that are differential against all other clusters, or differential against any or some other clusters; see below.
```
library(CATALYST)
library(scran)
library(SingleCellExperiment)

data(PBMC_fs, PBMC_panel, PBMC_md)
sce <- prepData(PBMC_fs, PBMC_panel, PBMC_md)
sce <- cluster(sce)

# - 'groups' specifys the cell grouping to be compared,
#   here, we want to compare clusters
# - 'block' takes into account that
#   cells come from different samples
# - 'test.type = "wilcox"' compares medians,
#   'test.type = "t"' compares means

# (using 20 metaclusters)
# cluster 7 against all other clusters 
findMarkers(
    x = assay(sce, "exprs"),
    block = sub$sample_id,
    groups = cluster_ids(sce, "meta20") == 7,
    test.type = "wilcox")

# cluster 7 against clusters 8 and 9
sub <- filterSCE(sce, k = "meta20", cluster_id %in% 7:9)
findMarkers(
    x = assay(sub, "exprs"),
    block = sub$sample_id,
    groups = cluster_ids(sub, "meta20") == 7,
    test.type = "wilcox",
    # assure that markers differential 
    # against both clusters; default is "any"
    pval.type = "all") 

# cluster X against all clusters != X
findMarkers(
    x = assay(sce, "exprs"),
    block = sce$sample_id,
    groups = cluster_ids(sce, "meta20"),
    test.type = "wilcox",
    # find markers differential against all other clusters
    pval.type = "all") 
    # for markers differential against 
    # any other cluster, use 'pval.type = "any"'
```

**Comment by SamGG** [comment]
Great! Thanks for pointing such a use of scran package.

**Comment by grhogg** [comment]
Awesome! Thank you guys so much for your help!
