### ISSUE TITLE
Concatenate flowframes without time column [REQ]

### ISSUE THREAD

**Issue by danxfreeman** [HelenaLC/CATALYST#86]
I tried using the `ConcatFCS` function to concatenate flowframes in a flowset but got this message, even when setting `by_time = F`:

`Error in es[inds, timeCol] : subscript out of bounds`

The time column was filtered out before the FCS files were handed to me so I wish there was a way to use this function without it

**Comment by HelenaLC** [comment]
* `by_time` specifies whether the data should be ordered by acquisition time stored in `keyword(flowSet, "$BTIM")`. Here, time does not refer to event times (parameter `Time` or similar), but the actual time each acquisition happened (e.g, 12:05:32). `by_time` thus determines the *sample* not *cell* order. Cells are by default ordered according to the `Time` parameter. 
* There was nevertheless a bug when this was missing, so thanks! I modified the function to take the cell order as is when the `Time` parameter is missing.
* With the R 4.0.0 and Bioc 3.11 release coming up there's a lot of development going on and this change will be available with the next release; until then you could try adding a parameter `Time = 1, 2, 3, ...` and removing it after concatenation. Sorry for the inconvenience!
