### ISSUE TITLE
How to construct a contrast matrix for multiple-variable and designated comparisons

### ISSUE THREAD

**Issue by mimisikai** [HelenaLC/CATALYST#88]
My first try on diffcyt comes back with this error:
`res_DA = diffcyt(CD154_sce, clustering_to_use = "meta20",
+                   analysis_type = "DA", method_DA = "diffcyt-DA-edgeR",
+                   design = design, contrast = contrast)
using SingleCellExperiment object from CATALYST as input
using cluster IDs from clustering stored in column 'meta20' of 'cluster_codes' data frame in 'metadata' of SingleCellExperiment object from CATALYST
calculating features...
Error in calcMedians(d_se) : 
  all(sapply(medians, function(m) { .... is not TRUE`

I cannot conclude that's some problems from my data or because of contrast table, which is most confused part. So I extent my question to how to make a contrast matrix for complicated design. 

I have two variables, Time and Group. Time has 4 levels (1,2,3,4),  Group has 3 levels (A, B, C)
When making a design table, what I did is: 
`design = createDesignMatrix(ei(sce), cols_design = c("Group", "Time"))`
But I'm stuck on how to make a contrast matrix. 

A few comparison I desire, 
(1) comparing Time within Group, e.g. A_1 vs A_2, A_1 vs A_3 et.al.
(2) comparing Groups at the same Time point, e.g. A_1 vs B_1, B_1 vs C_1 et.al.

Could you give a suggestion on how to make such matrix? 

Thanks.

**Comment by HelenaLC** [comment]
(1) To compare between time points using only a single group, I suggest you subset the group of interest and then set up separate contrasts for each comparison. I.e.
```
 # subset group A 
sub <- sce[, sce$Group == "A"]
ei <- metadata(sub)
ei <- ei[ei$Group == "A", ]

# drop no longer existent factor levels
# to avoid potential complications
ei$Group <- droplevels(ei$Group)

# specify design & contrast matrices
design <- createDesignMatrix(ei, cols_design = "Group")
contrast2vs1 <- createContrast(c(0, 1))
contrast3vs1 <- createContrast(c(0, 2))
diffcyt(...)
```

(2) Similar to above, subset the time point of interest and set up separate contrast for each group comparison.

**Comment by mimisikai** [comment]
I try but the same error still occurs. It may not the contrast's issue

using SingleCellExperiment object from CATALYST as input
using cluster IDs from clustering stored in column 'meta20' of
'cluster_codes' data frame in 'metadata' of SingleCellExperiment object
from CATALYST
calculating features...
Error in calcMedians(d_se) :
  all(sapply(medians, function(m) { .... is not TRUE

**Comment by HelenaLC** [comment]
I don’t think this is a CATALYST issue. I suggest you file an issue / get in touch with Lukas (@lmweber). I believe this error came up before with the `diffcyt` package, but I’m not sure how to fix it...

**Comment by mimisikai** [comment]
You're right. Thanks!
