### ISSUE TITLE
package ‘CATALYST’ is not available (for R version 3.6.3)

### ISSUE THREAD

**Issue by EDYAC** [HelenaLC/CATALYST#94]
Hello everyone,
I'm trying to install CATALYST but i'm getting an error that it's not available for R version 3.6.3,
any idea what I should do?
Than you

**Comment by HelenaLC** [comment]
What command are you using to install it?

**Comment by markrobinsonuzh** [comment]
Just to also say, the canonical instructions for installing the (release version of the) package are here:
https://bioconductor.org/packages/release/bioc/html/CATALYST.html

```if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("CATALYST")```

But of course, that requires you to have the "right" version of R (this changes yearly) and the right version of R/Bioconductor (this changes every 6 months), which you can read about here:
https://bioconductor.org/install/

**Comment by EDYAC** [comment]
Hi, I have installed R version 3.6.1 and now it's working. 
Thank you so much
