### ISSUE TITLE
could not find symbol "use.names" in environment of the generic function

### ISSUE THREAD

**Issue by hrkg52** [HelenaLC/CATALYST#95]
Hello,
When I create the daframe, I receive this error :

**Error in rowData(object) : 
  could not find symbol "use.names" in environment of the generic function**

Do you know why it happens ?

Thanks in advance.

**Comment by HelenaLC** [comment]
The `daFrame` class has become obsolete with Bioconductor v3.10; please update your software:
```
# this should be 3.10
BiocManager::version()

# if it is not, use 
BiocManager::install(version = "3.10")

# to check your current library is up to date
BiocManager::valid()
```
General instructions can also be found here: https://bioconductor.org/install
