### ISSUE TITLE
Error in hclust 

### ISSUE THREAD

**Issue by mimisikai** [HelenaLC/CATALYST#99]
The same data saved previously reload into work environment, run cluster and plot heatmap by plotClusterHeatmap, feed back with this error:
Error in hclust(d, method = "average") : 
  NA/NaN/Inf in foreign function call (arg 10)

Apparently, some missing values in my data give the hard time to hcluster, however, I look around the data, do not have any clue where the NA value from. May I have your input here? 
I can show the data if you think that part will be suspicious. Thanks.

**Comment by markrobinsonuzh** [comment]
@mimisikai check this Issue, which had the same error:
https://github.com/HelenaLC/CATALYST/issues/98

And, as always, give more details about your problem .. `sessionInfo()`, `traceback()`, the full command you called and some details of the inputs you gave it.

**Comment by mimisikai** [comment]
Thanks, Helena.
Once I give the "type" for markers, the problem's solved. But, I wonder
even I specify the "feature" with marker names, that doesn't work?
Joe
